import type { Question } from '@/domain/quiz'

/**
 * Questions construites à partir des faits vérifiés de syntheseB.pdf — voir
 * ./facts.ts. Chaque question cite son/ses factIds (page exacte du PDF).
 */
export const SYNTHESE_B_QUESTIONS: Question[] = [
  // --- vehicule-technique ---
  {
    id: 'sb-vt-1',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Qui détermine la MMA (Masse Maximale Autorisée) d’un véhicule ?', nl: 'Wie bepaalt de MTM (Maximaal Toegelaten Massa) van een voertuig?' },
    options: [
      { id: 'a', text: { fr: 'Le fabricant', nl: 'De fabrikant' }, correct: true },
      { id: 'b', text: { fr: 'Le conducteur, selon ce qu’il transporte', nl: 'De bestuurder, naargelang de lading' }, correct: false },
    ],
    explanation: { fr: 'La MMA est fixée par le fabricant du véhicule ; avec un permis B, elle ne peut excéder 3,5 tonnes.', nl: 'De MTM wordt vastgelegd door de fabrikant van het voertuig; met een rijbewijs B mag ze niet meer dan 3,5 ton bedragen.' },
    factIds: ['sb-mma-def'],
    difficulty: 'facile',
  },
  {
    id: 'sb-vt-2',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Que représente la MEC (Masse En Charge) ?', nl: 'Wat is de MTM in werkelijkheid — de "Massa in beladen toestand"?' },
    options: [
      { id: 'a', text: { fr: 'Le poids réel du véhicule à un instant donné (essence, conducteur, passagers, charge inclus)', nl: 'Het werkelijke gewicht van het voertuig op een bepaald moment (brandstof, bestuurder, passagiers, lading inbegrepen)' }, correct: true },
      { id: 'b', text: { fr: 'Le poids du véhicule vide, sans essence', nl: 'Het gewicht van het lege voertuig, zonder brandstof' }, correct: false },
    ],
    explanation: { fr: 'La MEC est le poids réel du véhicule à un instant T, en additionnant voiture, essence, conducteur, passagers et charge.', nl: 'De massa in beladen toestand is het werkelijke gewicht van het voertuig op een gegeven moment: auto, brandstof, bestuurder, passagiers en lading samen.' },
    factIds: ['sb-mec-def'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-vt-3',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Peut-on tracter une remorque avec un permis de conduire B provisoire ?', nl: 'Mag u een aanhangwagen trekken met een voorlopig rijbewijs B?' },
    options: [
      { id: 'a', text: { fr: 'Oui', nl: 'Ja' }, correct: false },
      { id: 'b', text: { fr: 'Non, c’est interdit', nl: 'Nee, dat is verboden' }, correct: true },
    ],
    explanation: { fr: 'La remorque est interdite avec un permis B provisoire ; avec un permis B définitif, elle est limitée à 750 kg.', nl: 'Een aanhangwagen is verboden met een voorlopig rijbewijs B; met een definitief rijbewijs B is dit beperkt tot 750 kg.' },
    factIds: ['sb-remorque'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-vt-4',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Entre quelles dates les pneus cloutés sont-ils autorisés en Belgique ?', nl: 'Tussen welke data zijn spijkerbanden toegelaten in België?' },
    options: [
      { id: 'a', text: { fr: 'Du 1er novembre au 31 mars', nl: 'Van 1 november tot 31 maart' }, correct: true },
      { id: 'b', text: { fr: 'Toute l’année', nl: 'Het hele jaar door' }, correct: false },
    ],
    explanation: { fr: 'Les pneus cloutés sont autorisés du 1er novembre au 31 mars (véhicule ≤ 3,5 t), avec une vitesse limitée à 90 km/h sur autoroute et 60 km/h ailleurs.', nl: 'Spijkerbanden zijn toegelaten van 1 november tot 31 maart (voertuig ≤ 3,5 ton), met een snelheidsbeperking van 90 km/u op de snelweg en 60 km/u elders.' },
    factIds: ['sb-pneus-cloutes'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-vt-5',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Des pneus sous-gonflés augmentent-ils la consommation de carburant ?', nl: 'Verhogen onderspannen banden het brandstofverbruik?' },
    options: [
      { id: 'a', text: { fr: 'Oui', nl: 'Ja' }, correct: true },
      { id: 'b', text: { fr: 'Non, aucun effet', nl: 'Nee, geen effect' }, correct: false },
    ],
    explanation: { fr: 'Des pneus sous-gonflés augmentent le risque de crevaison, réduisent la tenue de route, s’usent plus vite et augmentent la consommation.', nl: 'Onderspannen banden verhogen het risico op een lekke band, verminderen de wegligging, verslijten sneller en verhogen het verbruik.' },
    factIds: ['sb-pneus-sous-gonfles'],
    difficulty: 'facile',
  },
  {
    id: 'sb-vt-6',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Que fait l’ABS lors d’un freinage d’urgence ?', nl: 'Wat doet het ABS bij een noodstop?' },
    options: [
      { id: 'a', text: { fr: 'Il empêche les roues de se bloquer, évitant le dérapage', nl: 'Het voorkomt dat de wielen blokkeren, en dus slippen' }, correct: true },
      { id: 'b', text: { fr: 'Il augmente la puissance de freinage', nl: 'Het verhoogt de remkracht' }, correct: false },
    ],
    explanation: { fr: 'L’ABS empêche les roues de se bloquer lors du freinage et évite ainsi que la voiture ne dérape.', nl: 'Het ABS voorkomt dat de wielen blokkeren tijdens het remmen, waardoor de auto niet slipt.' },
    factIds: ['sb-abs-esp'],
    difficulty: 'facile',
  },
  {
    id: 'sb-vt-7',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Quels documents le conducteur doit-il avoir sur lui ?', nl: 'Welke documenten moet de bestuurder bij zich hebben?' },
    options: [
      { id: 'a', text: { fr: 'La carte d’identité et le permis de conduire', nl: 'De identiteitskaart en het rijbewijs' }, correct: true },
      { id: 'b', text: { fr: 'Seulement le permis de conduire', nl: 'Enkel het rijbewijs' }, correct: false },
    ],
    explanation: { fr: 'Le conducteur doit avoir sa carte d’identité et son permis de conduire ; la voiture doit avoir son certificat d’immatriculation, son attestation d’assurance et son certificat de conformité.', nl: 'De bestuurder moet zijn identiteitskaart en rijbewijs bij zich hebben; de auto moet haar inschrijvingsbewijs, verzekeringsattest en gelijkvormigheidsattest hebben.' },
    factIds: ['sb-documents'],
    difficulty: 'facile',
  },
  {
    id: 'sb-vt-8',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Quels accessoires sont obligatoires dans la voiture ?', nl: 'Welke accessoires zijn verplicht in de auto?' },
    options: [
      { id: 'a', text: { fr: 'Triangle de danger, trousse de secours, extincteur, gilet de sécurité', nl: 'Gevarendriehoek, EHBO-kit, brandblusser, veiligheidsvest' }, correct: true },
      { id: 'b', text: { fr: 'Uniquement le triangle de danger', nl: 'Enkel de gevarendriehoek' }, correct: false },
    ],
    explanation: { fr: 'Quatre accessoires sont obligatoires : triangle de danger, trousse de secours, extincteur et gilet de sécurité.', nl: 'Vier accessoires zijn verplicht: gevarendriehoek, EHBO-kit, brandblusser en veiligheidsvest.' },
    factIds: ['sb-accessoires'],
    difficulty: 'moyen',
  },

  // --- circulation-vitesse ---
  {
    id: 'sb-cv-1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Quand devez-vous utiliser vos feux de croisement de jour ?', nl: 'Wanneer moet u overdag uw dimlichten gebruiken?' },
    options: [
      { id: 'a', text: { fr: 'Quand la visibilité est inférieure à 200 mètres', nl: 'Wanneer het zicht minder dan 200 meter bedraagt' }, correct: true },
      { id: 'b', text: { fr: 'Jamais de jour', nl: 'Nooit overdag' }, correct: false },
    ],
    explanation: { fr: 'Les feux de croisement s’utilisent de la tombée au lever du jour, et de jour si la visibilité descend sous 200 m (pluie, neige, brouillard).', nl: 'Dimlichten worden gebruikt van zonsondergang tot zonsopgang, en overdag als het zicht minder dan 200 m bedraagt (regen, sneeuw, mist).' },
    factIds: ['sb-feux-croisement'],
    difficulty: 'facile',
  },
  {
    id: 'sb-cv-2',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'À quelle distance faut-il éteindre ses feux de route en suivant un véhicule ?', nl: 'Op welke afstand moet u uw grootlichten doven wanneer u een voertuig volgt?' },
    options: [
      { id: 'a', text: { fr: 'À moins de 50 mètres', nl: 'Op minder dan 50 meter' }, correct: true },
      { id: 'b', text: { fr: 'À moins de 10 mètres seulement', nl: 'Enkel op minder dan 10 meter' }, correct: false },
    ],
    explanation: { fr: 'Les feux de route sont interdits si vous croisez un usager en face, si vous suivez un véhicule à moins de 50 m, ou si un éclairage suffisant permet déjà de voir à 100 m.', nl: 'Grootlichten zijn verboden wanneer u een tegenligger kruist, een voertuig volgt op minder dan 50 m, of wanneer voldoende verlichting al zicht op 100 m geeft.' },
    factIds: ['sb-feux-route-interdit'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-cv-3',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Peut-on utiliser son klaxon de jour lors d’un dépassement ?', nl: 'Mag u overdag toeteren tijdens een inhaalmanoeuvre?' },
    options: [
      { id: 'a', text: { fr: 'Oui', nl: 'Ja' }, correct: true },
      { id: 'b', text: { fr: 'Non, jamais', nl: 'Nee, nooit' }, correct: false },
    ],
    explanation: { fr: 'De jour, le klaxon peut être utilisé en cas de danger imminent, mais aussi lors d’un dépassement ; de nuit, uniquement en cas de danger imminent.', nl: 'Overdag mag u toeteren bij dreigend gevaar, maar ook tijdens een inhaalmanoeuvre; ’s nachts enkel bij dreigend gevaar.' },
    factIds: ['sb-klaxon'],
    difficulty: 'facile',
  },
  {
    id: 'sb-cv-4',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Quelle est la vitesse minimale autorisée sur autoroute en Belgique ?', nl: 'Wat is de minimale toegelaten snelheid op de Belgische snelweg?' },
    options: [
      { id: 'a', text: { fr: '70 km/h', nl: '70 km/u' }, correct: true },
      { id: 'b', text: { fr: '50 km/h', nl: '50 km/u' }, correct: false },
    ],
    explanation: { fr: 'Sur autoroute en Belgique, la vitesse maximale est de 120 km/h et la vitesse minimale de 70 km/h.', nl: 'Op de Belgische snelweg is de maximumsnelheid 120 km/u en de minimumsnelheid 70 km/u.' },
    factIds: ['sb-vitesse-autoroute'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-cv-5',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: {
      fr: 'Hors agglomération, sur une route pour automobiles à 2 voies séparées par un simple marquage : quelle région autorise 90 km/h ?',
      nl: 'Buiten de bebouwde kom, op een autoweg met 2 rijstroken gescheiden door markering: welk gewest laat 90 km/u toe?',
    },
    options: [
      { id: 'a', text: { fr: 'La Wallonie', nl: 'Wallonië' }, correct: true },
      { id: 'b', text: { fr: 'La Flandre', nl: 'Vlaanderen' }, correct: false },
      { id: 'c', text: { fr: 'Bruxelles', nl: 'Brussel' }, correct: false },
    ],
    explanation: { fr: 'Dans ce cas précis : 90 km/h en Wallonie, contre 70 km/h en Flandre et à Bruxelles.', nl: 'In dit specifieke geval: 90 km/u in Wallonië, tegenover 70 km/u in Vlaanderen en Brussel.' },
    factIds: ['sb-vitesse-route-auto-marquage'],
    difficulty: 'difficile',
  },
  {
    id: 'sb-cv-6',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Quelle est la vitesse maximale dans une zone de rencontre ?', nl: 'Wat is de maximumsnelheid in een ontmoetingszone?' },
    options: [
      { id: 'a', text: { fr: '20 km/h', nl: '20 km/u' }, correct: true },
      { id: 'b', text: { fr: '30 km/h', nl: '30 km/u' }, correct: false },
    ],
    explanation: { fr: 'La zone de rencontre est limitée à 20 km/h en Belgique ; un chemin réservé ou une zone cyclable est limité à 30 km/h, et un dispositif surélevé à 25 km/h.', nl: 'De ontmoetingszone is beperkt tot 20 km/u in België; een voorbehouden weg of fietszone tot 30 km/u, en een verkeersdrempel tot 25 km/u.' },
    factIds: ['sb-vitesse-zones'],
    difficulty: 'moyen',
  },

  // --- signalisation-priorites ---
  {
    id: 'sb-sp-1',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Un agent qualifié lève un bras verticalement : que devez-vous faire ?', nl: 'Een bevoegd persoon steekt één arm verticaal omhoog: wat moet u doen?' },
    options: [
      { id: 'a', text: { fr: 'Vous arrêter', nl: 'Stoppen' }, correct: true },
      { id: 'b', text: { fr: 'Continuer normalement', nl: 'Gewoon doorrijden' }, correct: false },
    ],
    explanation: { fr: 'Bras levé verticalement : tout le monde doit s’arrêter (ceux déjà dans l’intersection doivent la quitter).', nl: 'Arm verticaal omhoog: iedereen moet stoppen (wie al op het kruispunt is, moet het verlaten).' },
    factIds: ['sb-agents-qualifies'],
    difficulty: 'facile',
  },
  {
    id: 'sb-sp-2',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Peut-on s’engager dans un carrefour au feu jaune-orange clignotant ?', nl: 'Mag u een kruispunt oprijden bij een knipperend geel-oranje licht?' },
    options: [
      { id: 'a', text: { fr: 'Oui, en respectant les priorités et avec prudence', nl: 'Ja, met inachtneming van de voorrang en met voorzichtigheid' }, correct: true },
      { id: 'b', text: { fr: 'Non, jamais', nl: 'Nee, nooit' }, correct: false },
    ],
    explanation: { fr: 'Un feu jaune-orange clignotant remplace parfois le vert : vous pouvez vous engager en respectant les règles de priorité et en redoublant de prudence.', nl: 'Een knipperend geel-oranje licht vervangt soms het groen: u mag oprijden mits u de voorrangsregels volgt en extra voorzichtig bent.' },
    factIds: ['sb-feu-jaune-clignotant'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-sp-3',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'La priorité de droite s’applique-t-elle dans un rond-point ?', nl: 'Geldt voorrang van rechts in een rotonde?' },
    options: [
      { id: 'a', text: { fr: 'Oui', nl: 'Ja' }, correct: false },
      { id: 'b', text: { fr: 'Non', nl: 'Nee' }, correct: true },
    ],
    explanation: { fr: 'La priorité de droite ne s’applique pas dans un rond-point, ni si le conducteur venant de droite débouche d’un sens interdit.', nl: 'Voorrang van rechts geldt niet in een rotonde, en ook niet als de bestuurder van rechts uit een verboden rijrichting komt.' },
    factIds: ['sb-priorite-droite-exceptions'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-sp-4',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: {
      fr: 'Vous venez de droite à un carrefour sans signalisation, mais il y a un passage pour piétons sur votre voie. Que faites-vous ?',
      nl: 'U komt van rechts op een kruispunt zonder signalisatie, maar er is een voetgangersoversteekplaats op uw rijstrook. Wat doet u?',
    },
    options: [
      { id: 'a', text: { fr: 'Vous avez priorité sur tout le monde, y compris les piétons', nl: 'U hebt voorrang op iedereen, ook op voetgangers' }, correct: false },
      { id: 'b', text: { fr: 'Vous devez laisser passer les piétons qui traversent ou s’apprêtent à traverser', nl: 'U moet voetgangers laten oversteken of die op het punt staan om over te steken' }, correct: true },
    ],
    explanation: { fr: 'Exception à la priorité de droite : en présence d’un trottoir ininterrompu ou d’un passage pour piétons, le conducteur venant de droite doit laisser passer les piétons.', nl: 'Uitzondering op voorrang van rechts: bij een ononderbroken voetpad of een oversteekplaats moet de bestuurder van rechts de voetgangers laten voorgaan.' },
    factIds: ['sb-priorite-droite-exceptions'],
    difficulty: 'difficile',
  },
  {
    id: 'sb-sp-5',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Un tram doit-il respecter la priorité de droite ?', nl: 'Moet een tram voorrang van rechts respecteren?' },
    options: [
      { id: 'a', text: { fr: 'Oui, comme tout véhicule', nl: 'Ja, zoals elk voertuig' }, correct: false },
      { id: 'b', text: { fr: 'Non, les véhicules sur rails en sont dispensés', nl: 'Nee, voertuigen op rails zijn daarvan vrijgesteld' }, correct: true },
    ],
    explanation: { fr: 'Les véhicules sur rails (trams) ne sont pas tenus de respecter la priorité de droite.', nl: 'Voertuigen op rails (trams) hoeven de voorrang van rechts niet te respecteren.' },
    factIds: ['sb-rails-priorite'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-sp-6',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Un panneau triangulaire pointe en bas (« cédez le passage ») concerne-t-il aussi les piétons ?', nl: 'Geldt een omgekeerd driehoekig bord ("voorrang verlenen") ook voor voetgangers?' },
    options: [
      { id: 'a', text: { fr: 'Oui', nl: 'Ja' }, correct: false },
      { id: 'b', text: { fr: 'Non, uniquement les conducteurs de la voie que vous croisez', nl: 'Nee, enkel bestuurders op de weg die u kruist' }, correct: true },
    ],
    explanation: { fr: 'Ce panneau impose de céder le passage aux conducteurs (pas aux piétons) de la voie que vous allez emprunter, et de vous arrêter si nécessaire.', nl: 'Dit bord verplicht voorrang te verlenen aan bestuurders (niet aan voetgangers) op de weg die u gaat oprijden, en indien nodig te stoppen.' },
    factIds: ['sb-triangle-pointe-bas'],
    difficulty: 'difficile',
  },

  // --- stationnement ---
  {
    id: 'sb-st-1',
    themeSlug: 'stationnement',
    region: 'BE',
    prompt: { fr: 'Qu’est-ce qui distingue un arrêt d’un stationnement ?', nl: 'Wat is het verschil tussen stilstaan en parkeren?' },
    options: [
      { id: 'a', text: { fr: 'Le temps d’immobilisation : l’arrêt est limité au temps nécessaire à l’embarquement/débarquement', nl: 'De duur van de stilstand: stilstaan is beperkt tot de tijd nodig om in/uit te stappen of te laden/lossen' }, correct: true },
      { id: 'b', text: { fr: 'Rien, ce sont les mêmes règles', nl: 'Niets, het zijn dezelfde regels' }, correct: false },
    ],
    explanation: { fr: 'Un arrêt est limité au temps nécessaire à l’embarquement/débarquement ; au-delà, on parle de stationnement.', nl: 'Stilstaan is beperkt tot de tijd nodig om in/uit te stappen of te laden/lossen; daarna spreekt men van parkeren.' },
    factIds: ['sb-arret-stationnement-def'],
    difficulty: 'facile',
  },
  {
    id: 'sb-st-2',
    themeSlug: 'stationnement',
    region: 'BE',
    prompt: { fr: 'À combien de mètres avant un passage pour piétons le stationnement est-il interdit ?', nl: 'Op hoeveel meter voor een voetgangersoversteekplaats is parkeren verboden?' },
    options: [
      { id: 'a', text: { fr: '5 mètres', nl: '5 meter' }, correct: true },
      { id: 'b', text: { fr: '1 mètre', nl: '1 meter' }, correct: false },
    ],
    explanation: { fr: 'Le stationnement est interdit à moins de 5 m avant un passage pour piétons ou cyclistes, pour garder une bonne visibilité.', nl: 'Parkeren is verboden op minder dan 5 m voor een voetgangers- of fietsoversteekplaats, om voldoende zicht te behouden.' },
    factIds: ['sb-stationnement-interdit-proximite'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-st-3',
    themeSlug: 'stationnement',
    region: 'BE',
    prompt: { fr: 'L’arrêt bref reste-t-il autorisé devant l’accès carrossable d’une propriété ?', nl: 'Mag u kort stilstaan voor de inrit van een eigendom?' },
    options: [
      { id: 'a', text: { fr: 'Oui, si votre plaque d’immatriculation y est reproduite lisiblement', nl: 'Ja, als uw nummerplaat er leesbaar is aangebracht' }, correct: true },
      { id: 'b', text: { fr: 'Non, jamais', nl: 'Nee, nooit' }, correct: false },
    ],
    explanation: { fr: 'Devant un accès carrossable, l’arrêt/stationnement est interdit sauf pour le véhicule dont la plaque est reproduite lisiblement à cet accès.', nl: 'Voor een oprit is stilstaan/parkeren verboden, behalve voor het voertuig waarvan de nummerplaat leesbaar op de oprit is aangebracht.' },
    factIds: ['sb-arret-autorise'],
    difficulty: 'difficile',
  },
  {
    id: 'sb-st-4',
    themeSlug: 'stationnement',
    region: 'BE',
    prompt: { fr: 'Quelle est la durée maximale de stationnement avec un disque, sauf indication contraire ?', nl: 'Wat is de maximale parkeerduur met een parkeerschijf, tenzij anders aangegeven?' },
    options: [
      { id: 'a', text: { fr: '2 heures', nl: '2 uur' }, correct: true },
      { id: 'b', text: { fr: '4 heures', nl: '4 uur' }, correct: false },
    ],
    explanation: { fr: 'Le disque de stationnement, réglé sur l’heure d’arrivée, autorise 2 heures de stationnement maximum sauf indication contraire du panneau.', nl: 'De parkeerschijf, ingesteld op het aankomstuur, laat maximaal 2 uur parkeren toe, tenzij het bord anders aangeeft.' },
    factIds: ['sb-disque-stationnement'],
    difficulty: 'facile',
  },
  {
    id: 'sb-st-5',
    themeSlug: 'stationnement',
    region: 'BE',
    prompt: { fr: 'Combien de temps un véhicule en panne peut-il rester sur la voie publique ?', nl: 'Hoe lang mag een defect voertuig op de openbare weg blijven staan?' },
    options: [
      { id: 'a', text: { fr: '24 heures maximum', nl: 'Maximaal 24 uur' }, correct: true },
      { id: 'b', text: { fr: 'Sans limite', nl: 'Zonder beperking' }, correct: false },
    ],
    explanation: { fr: 'Un véhicule en panne peut rester 24 heures maximum sur la voie publique (3 heures pour un véhicule publicitaire) ; il est aussi interdit d’y mettre un véhicule en vente.', nl: 'Een defect voertuig mag maximaal 24 uur op de openbare weg blijven (3 uur voor een reclamevoertuig); het is ook verboden er een voertuig te koop aan te bieden.' },
    factIds: ['sb-interdictions-diverses'],
    difficulty: 'moyen',
  },

  // --- securite-comportement ---
  {
    id: 'sb-sc-1',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Avec un permis provisoire, à partir de quelle heure ne peut-on plus conduire un vendredi soir ?', nl: 'Met een voorlopig rijbewijs: vanaf welk uur mag u vrijdagavond niet meer rijden?' },
    options: [
      { id: 'a', text: { fr: '22h00', nl: '22u00' }, correct: true },
      { id: 'b', text: { fr: 'Minuit', nl: 'Middernacht' }, correct: false },
    ],
    explanation: { fr: 'Le permis provisoire interdit de conduire de 22h00 à 6h00 les nuits de vendredi, samedi et dimanche, ainsi que la veille et le soir d’un jour férié.', nl: 'Het voorlopig rijbewijs verbiedt rijden van 22u00 tot 6u00 op vrijdag-, zaterdag- en zondagavond, en ook de avond voor en de avond van een feestdag.' },
    factIds: ['sb-permis-provisoire-horaires'],
    difficulty: 'facile',
  },
  {
    id: 'sb-sc-2',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Un chauffeur de taxi qui transporte des clients doit-il porter la ceinture de sécurité ?', nl: 'Moet een taxichauffeur die klanten vervoert de veiligheidsgordel dragen?' },
    options: [
      { id: 'a', text: { fr: 'Oui, sans exception', nl: 'Ja, zonder uitzondering' }, correct: false },
      { id: 'b', text: { fr: 'Non, il est exempté dans ce cas', nl: 'Nee, hij is in dat geval vrijgesteld' }, correct: true },
    ],
    explanation: { fr: 'Un chauffeur de taxi transportant des clients, un facteur en tournée, un conducteur en marche arrière et les agents/secours en mission sont exemptés de la ceinture.', nl: 'Een taxichauffeur die klanten vervoert, een postbode in ronde, een bestuurder die achteruitrijdt, en agenten/hulpdiensten in opdracht zijn vrijgesteld van de gordelplicht.' },
    factIds: ['sb-ceintures'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-sc-3',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Jusqu’à quel âge ET quelle taille un enfant doit-il utiliser un dispositif de retenue ?', nl: 'Tot welke leeftijd EN lengte moet een kind een kinderbeveiligingssysteem gebruiken?' },
    options: [
      { id: 'a', text: { fr: 'Moins de 18 ans ET moins de 1m35', nl: 'Jonger dan 18 jaar EN kleiner dan 1m35' }, correct: true },
      { id: 'b', text: { fr: 'Moins de 12 ans, peu importe la taille', nl: 'Jonger dan 12 jaar, ongeacht de lengte' }, correct: false },
    ],
    explanation: { fr: 'Les deux conditions sont cumulatives : moins de 18 ans ET une taille inférieure à 1m35 imposent un dispositif de retenue pour enfants.', nl: 'Beide voorwaarden gelden samen: jonger dan 18 jaar EN kleiner dan 1m35 verplicht een kinderbeveiligingssysteem.' },
    factIds: ['sb-enfants-retenue'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-sc-4',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'À quelle distance placer le triangle de danger sur autoroute ?', nl: 'Op welke afstand plaatst u de gevarendriehoek op de snelweg?' },
    options: [
      { id: 'a', text: { fr: 'Environ 100 mètres', nl: 'Ongeveer 100 meter' }, correct: true },
      { id: 'b', text: { fr: 'Environ 30 mètres, comme sur route ordinaire', nl: 'Ongeveer 30 meter, zoals op een gewone weg' }, correct: false },
    ],
    explanation: { fr: 'Sur autoroute, le triangle se place à environ 100 m derrière le véhicule (contre 30 m sur route ordinaire), pour laisser le temps aux autres conducteurs de réagir.', nl: 'Op de snelweg plaatst u de driehoek op ongeveer 100 m achter het voertuig (tegenover 30 m op een gewone weg), zodat andere bestuurders tijdig kunnen reageren.' },
    factIds: ['sb-triangle-accident'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-sc-5',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'La police ne se déplace pas après un accident avec blessés : que faites-vous ?', nl: 'De politie komt niet na een ongeval met gewonden: wat doet u?' },
    options: [
      { id: 'a', text: { fr: 'Vous faites une déclaration au bureau de police dans les 24 heures', nl: 'U doet aangifte op het politiebureau binnen de 24 uur' }, correct: true },
      { id: 'b', text: { fr: 'Ce n’est pas grave, vous n’avez rien à faire', nl: 'Geen probleem, u hoeft niets te doen' }, correct: false },
    ],
    explanation: { fr: 'En cas d’accident avec blessés, la police doit en principe se déplacer ; si elle ne vient pas, une déclaration doit être faite au bureau de police dans les 24 heures.', nl: 'Bij een ongeval met gewonden moet de politie in principe komen; komt ze niet, dan moet u binnen de 24 uur aangifte doen op het politiebureau.' },
    factIds: ['sb-accident-blesses'],
    difficulty: 'moyen',
  },
  {
    id: 'sb-sc-6',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Combien de temps devez-vous attendre avant de reprendre le volant après un résultat « ALARME » au test d’haleine (0,22 à 0,35 mg/l) ?', nl: 'Hoe lang moet u wachten om weer te rijden na een "ALARM"-resultaat bij de ademtest (0,22 tot 0,35 mg/l)?' },
    options: [
      { id: 'a', text: { fr: '12 heures', nl: '12 uur' }, correct: true },
      { id: 'b', text: { fr: '15 jours, comme pour un résultat positif', nl: '15 dagen, zoals bij een positief resultaat' }, correct: false },
    ],
    explanation: { fr: 'Un résultat « ALARME » (0,22 à 0,35 mg/l) impose 12 heures d’attente ; un résultat « POSITIF » (0,35 mg/l ou plus) impose 15 jours sans conduire. Refuser de souffler entraîne aussi 12 heures d’attente.', nl: 'Een "ALARM"-resultaat (0,22 tot 0,35 mg/l) legt 12 uur wachttijd op; een "POSITIEF"-resultaat (0,35 mg/l of meer) legt 15 dagen rijverbod op. Weigeren te blazen geeft ook 12 uur wachttijd.' },
    factIds: ['sb-alcool-table'],
    difficulty: 'difficile',
  },
]
