import type { Question } from '@/domain/quiz'

export const CIRCULATION_VITESSE_QUESTIONS: Question[] = [
  {
    id: 'cv4-q1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Sur autoroute, un cyclomoteur peut-il circuler ?', nl: 'Mag een bromfiets op de snelweg rijden?' },
    options: [
      { id: 'a', text: { fr: 'Oui', nl: 'Ja' }, correct: false },
      { id: 'b', text: { fr: 'Non, il en est exclu', nl: 'Nee, hij is ervan uitgesloten' }, correct: true },
    ],
    explanation: { fr: "Les cyclomoteurs, véhicules agricoles, quadricycles sans habitacle et trains forains sont exclus de l'autoroute.", nl: 'Bromfietsen, landbouwvoertuigen, open vierwielers en kermistreinen zijn uitgesloten van de snelweg.' },
    factIds: ['cv4-def-acces'],
    difficulty: 'facile',
  },
  {
    id: 'cv4-q2',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Vous tombez en panne sur la bande d’arrêt d’urgence. Où placez-vous le triangle de danger ?', nl: 'U heeft pech op de pechstrook. Waar plaatst u de gevarendriehoek?' },
    options: [
      { id: 'a', text: { fr: 'À 30 mètres', nl: 'Op 30 meter' }, correct: false },
      { id: 'b', text: { fr: 'À 100 mètres', nl: 'Op 100 meter' }, correct: true },
    ],
    explanation: { fr: "Sur autoroute, le triangle se place à au moins 100 mètres (30 mètres sur une route ordinaire).", nl: 'Op de snelweg plaats je de driehoek op minstens 100 meter (30 meter op een gewone weg).' },
    factIds: ['cv4-bande-arret-urgence'],
    difficulty: 'moyen',
  },
  {
    id: 'cv5-q1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Contrairement à l’autoroute, une route pour automobiles peut comporter…', nl: 'In tegenstelling tot de snelweg kan een autoweg…' },
    options: [
      { id: 'a', text: { fr: 'Des carrefours et des feux de signalisation', nl: 'Kruispunten en verkeerslichten hebben' }, correct: true },
      { id: 'b', text: { fr: 'Des cyclomoteurs', nl: 'Bromfietsen toelaten' }, correct: false },
    ],
    explanation: { fr: "Une route pour automobiles peut comporter des carrefours et des feux — l'autoroute non.", nl: 'Een autoweg kan kruispunten en lichten hebben — de snelweg niet.' },
    factIds: ['cv5-def'],
    difficulty: 'facile',
  },
  {
    id: 'cv5-q2',
    themeSlug: 'circulation-vitesse',
    region: 'WALLONIE',
    prompt: { fr: 'En Wallonie, hors agglomération, sur une route pour automobiles séparée seulement par un marquage, la vitesse max est de…', nl: 'In Wallonië, buiten de bebouwde kom, op een autoweg enkel gescheiden door markering, is de max. snelheid…' },
    options: [
      { id: 'a', text: { fr: '70 km/h', nl: '70 km/u' }, correct: false },
      { id: 'b', text: { fr: '90 km/h', nl: '90 km/u' }, correct: true },
    ],
    explanation: { fr: "90 km/h en Wallonie, contre 70 km/h en Flandre et à Bruxelles dans les mêmes conditions.", nl: '90 km/u in Wallonië, tegenover 70 km/u in Vlaanderen en Brussel in dezelfde omstandigheden.' },
    factIds: ['cv5-vitesse-marquage-wallonie'],
    difficulty: 'moyen',
  },
  {
    id: 'cv12-q1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Freiner brusquement sans raison est-il sanctionnable ?', nl: 'Is plots remmen zonder reden strafbaar?' },
    options: [
      { id: 'a', text: { fr: 'Non, ce n’est pas un excès de vitesse', nl: 'Nee, dat is geen snelheidsovertreding' }, correct: false },
      { id: 'b', text: { fr: 'Oui, c’est une infraction, comme rouler trop lentement', nl: 'Ja, dat is een overtreding, net als te traag rijden' }, correct: true },
    ],
    explanation: { fr: "Rouler trop lentement sans raison ou freiner sans nécessité sont tous deux des infractions.", nl: 'Zonder reden te traag rijden of onnodig remmen zijn allebei overtredingen.' },
    factIds: ['cv12-trop-lentement-courses'],
    difficulty: 'moyen',
  },
  {
    id: 'cv12-q2',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Qui décide d’un retrait immédiat du permis pour excès de vitesse ?', nl: 'Wie beslist over een onmiddellijke intrekking van het rijbewijs wegens snelheidsovertreding?' },
    options: [
      { id: 'a', text: { fr: 'Un juge, au tribunal', nl: 'Een rechter, voor de rechtbank' }, correct: false },
      { id: 'b', text: { fr: 'Le Procureur du Roi, exécuté par la police', nl: 'De Procureur des Konings, uitgevoerd door de politie' }, correct: true },
    ],
    explanation: { fr: "Le retrait immédiat est une décision du Procureur du Roi (ou d'un officier de police judiciaire), exécutée sur place par la police — la déchéance, elle, vient d'un juge.", nl: 'De onmiddellijke intrekking is een beslissing van de Procureur des Konings (of een officier van gerechtelijke politie), ter plaatse uitgevoerd door de politie — de vervallenverklaring komt van een rechter.' },
    factIds: ['cv12-retrait-immediat'],
    difficulty: 'difficile',
  },
  {
    id: 'cv13-q1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'À 100 km/h sur sol sec, quelle distance de sécurité approximative faut-il garder ?', nl: 'Bij 100 km/u op droog wegdek, welke veiligheidsafstand houd je ongeveer aan?' },
    options: [
      { id: 'a', text: { fr: '30 mètres', nl: '30 meter' }, correct: false },
      { id: 'b', text: { fr: '50 mètres', nl: '50 meter' }, correct: true },
    ],
    explanation: { fr: "La règle : vitesse divisée par deux, en mètres, sur sol sec — 100/2 = 50 m.", nl: 'De regel: snelheid gedeeld door twee, in meter, op droog wegdek — 100/2 = 50 m.' },
    factIds: ['cv13-distance-securite'],
    difficulty: 'facile',
  },
  {
    id: 'cv13-q2',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Après avoir consommé de l’alcool, le temps de réaction…', nl: 'Na het drinken van alcohol, de reactietijd…' },
    options: [
      { id: 'a', text: { fr: 'Reste inchangé', nl: 'Blijft onveranderd' }, correct: false },
      { id: 'b', text: { fr: 'Augmente à 2-3 secondes', nl: 'Stijgt naar 2-3 seconden' }, correct: true },
    ],
    explanation: { fr: "Le temps de réaction, environ 1 seconde à jeun, grimpe à 2-3 secondes sous alcool, et 5-8 secondes sous stupéfiants.", nl: 'De reactietijd, ongeveer 1 seconde nuchter, stijgt naar 2-3 seconden onder alcohol, en 5-8 seconden onder drugs.' },
    factIds: ['cv13-distance-reaction'],
    difficulty: 'moyen',
  },
  {
    id: 'cv13-q3',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Rouler avec l’ABS garantit-il une distance de freinage plus courte ?', nl: 'Garandeert rijden met ABS een kortere remafstand?' },
    options: [
      { id: 'a', text: { fr: 'Oui, toujours', nl: 'Ja, altijd' }, correct: false },
      { id: 'b', text: { fr: 'Non, il évite surtout la perte de contrôle', nl: 'Nee, het voorkomt vooral controleverlies' }, correct: true },
    ],
    explanation: { fr: "L'ABS empêche le blocage des roues et garde le véhicule dirigeable, mais ne garantit pas une distance de freinage plus courte.", nl: 'ABS voorkomt het blokkeren van de wielen en houdt het voertuig stuurbaar, maar garandeert geen kortere remafstand.' },
    factIds: ['cv13-abs-pneus'],
    difficulty: 'moyen',
  },
  {
    id: 'cv14-q1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Pour croiser un autre véhicule, pouvez-vous utiliser la piste cyclable ?', nl: 'Mag u het fietspad gebruiken om een ander voertuig te kruisen?' },
    options: [
      { id: 'a', text: { fr: 'Oui, si elle est libre', nl: 'Ja, als het vrij is' }, correct: false },
      { id: 'b', text: { fr: 'Non, jamais', nl: 'Nee, nooit' }, correct: true },
    ],
    explanation: { fr: "Il est interdit d'utiliser une piste cyclable — ou l'espace au-delà du bord fictif de la chaussée — pour se croiser.", nl: 'Het is verboden een fietspad — of de ruimte voorbij de fictieve rand van de rijbaan — te gebruiken om te kruisen.' },
    factIds: ['cv14-croisement-droite'],
    difficulty: 'facile',
  },
  {
    id: 'cv14-q2',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Un rétrécissement de chaussée sans aucun signal : qui cède le passage ?', nl: 'Een versmalling van de rijbaan zonder enig bord: wie verleent voorrang?' },
    options: [
      { id: 'a', text: { fr: 'Celui qui a l’obstacle de son côté', nl: 'Wie het obstakel aan zijn kant heeft' }, correct: true },
      { id: 'b', text: { fr: 'Celui qui vient de droite', nl: 'Wie van rechts komt' }, correct: false },
    ],
    explanation: { fr: "Sans signal, le conducteur qui rencontre l'obstacle de son côté doit céder le passage.", nl: 'Zonder bord moet de bestuurder die het obstakel aan zijn kant heeft, voorrang verlenen.' },
    factIds: ['cv14-retrecissement'],
    difficulty: 'moyen',
  },
  {
    id: 'cv15-q1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Doubler une voiture à l’arrêt sur le bord de la route, est-ce un dépassement au sens légal ?', nl: 'Een stilstaande auto langs de weg voorbijrijden, is dat wettelijk een inhaalmanoeuvre?' },
    options: [
      { id: 'a', text: { fr: 'Oui', nl: 'Ja' }, correct: false },
      { id: 'b', text: { fr: 'Non, c’est un contournement', nl: 'Nee, dat is een omzeiling' }, correct: true },
    ],
    explanation: { fr: "Un dépassement ne concerne qu'un véhicule en mouvement ; doubler un véhicule à l'arrêt, c'est le contourner.", nl: 'Een inhaalmanoeuvre betreft enkel een rijdend voertuig; een stilstaand voertuig voorbijrijden is het omzeilen ervan.' },
    factIds: ['cv15-def-depassement'],
    difficulty: 'facile',
  },
  {
    id: 'cv15-q2',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Dans quels cas pouvez-vous dépasser par la droite ?', nl: 'In welke gevallen mag u rechts inhalen?' },
    options: [
      { id: 'a', text: { fr: 'Jamais, c’est toujours interdit', nl: 'Nooit, altijd verboden' }, correct: false },
      { id: 'b', text: { fr: 'Un véhicule qui tourne à gauche, ou un tram', nl: 'Een voertuig dat links afslaat, of een tram' }, correct: true },
    ],
    explanation: { fr: "Le dépassement par la droite est permis dans deux cas seulement : un véhicule déjà déporté à gauche pour tourner, ou un tram.", nl: 'Rechts inhalen mag enkel in twee gevallen: een voertuig dat al naar links is uitgeweken om te draaien, of een tram.' },
    factIds: ['cv15-2-cas-droite'],
    difficulty: 'moyen',
  },
  {
    id: 'cv16-q1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Un signal d’interdiction de dépasser porte un panneau additionnel « 200 m ». Que signifie-t-il ?', nl: 'Een inhaalverbodsbord heeft een onderbord "200 m". Wat betekent dit?' },
    options: [
      { id: 'a', text: { fr: 'L’interdiction dure 200 m puis s’arrête', nl: 'Het verbod duurt 200 m en stopt dan' }, correct: false },
      { id: 'b', text: { fr: 'L’interdiction commence seulement 200 m plus loin', nl: 'Het verbod begint pas 200 m verder' }, correct: true },
    ],
    explanation: { fr: "Le panneau additionnel avec une distance retarde le début de l'interdiction, il n'en fixe pas la fin.", nl: 'Het onderbord met een afstand vertraagt het begin van het verbod, het bepaalt niet het einde ervan.' },
    factIds: ['cv16-signaux-interdiction'],
    difficulty: 'moyen',
  },
  {
    id: 'cv16-q2',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Pouvez-vous dépasser au sommet d’une côte sans visibilité, même sans signal ?', nl: 'Mag u inhalen op de top van een helling zonder zicht, zelfs zonder bord?' },
    options: [
      { id: 'a', text: { fr: 'Oui, en l’absence de signal c’est autorisé', nl: 'Ja, zonder bord is het toegelaten' }, correct: false },
      { id: 'b', text: { fr: 'Non, c’est interdit même sans signal', nl: 'Nee, dat is verboden zelfs zonder bord' }, correct: true },
    ],
    explanation: { fr: "Dépasser est interdit au sommet d'une côte sans visibilité suffisante, même en l'absence de tout signal.", nl: 'Inhalen is verboden op de top van een helling zonder voldoende zicht, zelfs zonder enig bord.' },
    factIds: ['cv16-lieux-interdits'],
    difficulty: 'moyen',
  },
  {
    id: 'cv21-q1',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Vous voulez tourner à gauche à un carrefour. Que devez-vous faire ?', nl: 'U wilt links afslaan aan een kruispunt. Wat moet u doen?' },
    options: [
      { id: 'a', text: { fr: 'Céder le passage aux véhicules venant en face', nl: 'Voorrang verlenen aan tegemoetkomende voertuigen' }, correct: true },
      { id: 'b', text: { fr: 'Passer en premier si j’arrive avant', nl: 'Eerst gaan als ik er eerder ben' }, correct: false },
    ],
    explanation: { fr: "Tourner à gauche impose toujours de céder le passage aux véhicules venant en sens inverse.", nl: 'Links afslaan verplicht altijd voorrang te verlenen aan tegemoetkomende voertuigen.' },
    factIds: ['cv21-priorite-tourner'],
    difficulty: 'facile',
  },
  {
    id: 'cv21-q2',
    themeSlug: 'circulation-vitesse',
    region: 'BE',
    prompt: { fr: 'Reculer sur la chaussée est-il considéré comme une manœuvre ?', nl: 'Wordt achteruitrijden op de rijbaan als een manoeuvre beschouwd?' },
    options: [
      { id: 'a', text: { fr: 'Oui, et il faut céder le passage à tous les usagers', nl: 'Ja, en je moet voorrang verlenen aan alle weggebruikers' }, correct: true },
      { id: 'b', text: { fr: 'Non, ce n’est pas une manœuvre', nl: 'Nee, dat is geen manoeuvre' }, correct: false },
    ],
    explanation: { fr: "Reculer est une manœuvre : elle exige de céder le passage à absolument tous les usagers.", nl: 'Achteruitrijden is een manoeuvre: het vereist voorrang te verlenen aan werkelijk alle weggebruikers.' },
    factIds: ['cv21-manoeuvre-def'],
    difficulty: 'facile',
  },
]
