const fr = {
  eyebrow: 'Entraînement vidéo · PermisHub', title: 'Test de perception des risques',
  subtitle: 'Entraîne-toi à détecter les dangers comme lors du test de perception des risques.',
  instructions: 'Des séquences de conduite vont être diffusées. Dès que tu identifies une situation présentant un risque, clique directement dessus.',
  start: 'Commencer l’entraînement', demo: 'DÉMO TECHNIQUE',
  demoNotice: 'Vidéo de conduite locale, zones de risque fictives. Cette démo vérifie le moteur interactif ; elle ne constitue pas un véritable examen ni une évaluation de ton niveau.',
  demoShort: 'Démo : zones fictives, sans valeur d’évaluation.',
  step1: 'Observe la scène', step1Body: 'La vidéo se lance sans son. Reste attentif à ce qui se passe autour de toi.',
  step2: 'Touche le danger', step2Body: 'Clique ou touche directement la zone. Un cercle confirme uniquement ton geste.',
  step3: 'Comprends ensuite', step3Body: 'À la fin, retrouve ton score sur 10 et la correction des séquences.',
  local: 'Tes résultats restent dans ce navigateur. Aucun résultat n’est envoyé au serveur.',
  previous: 'Revoir mon dernier résultat', next: 'Séquence suivante', loading: 'Chargement de la vidéo…',
  resume: 'Lancer / reprendre la vidéo', videoError: 'La vidéo ne peut pas être lue. Vérifie le fichier ou ta connexion locale.',
  retry: 'Réessayer la lecture', unsupported: 'Ton navigateur ne prend pas en charge cette vidéo.',
  tap: 'Touche directement une situation à risque.', noFeedback: 'La correction sera disponible à la fin.',
  leave: 'Quitter l’entraînement', leaveTitle: 'Quitter cette tentative ?', leaveBody: 'Les clics de cette tentative seront abandonnés.',
  stay: 'Continuer l’entraînement', quit: 'Quitter', result: 'Ton résultat', detected: 'risques détectés',
  missed: 'risques manqués', falseClicks: 'clics hors des zones actives', duplicates: 'clics répétés sur une zone déjà détectée',
  noPenalty: 'Aucune pénalité pour les faux clics. Chaque risque vaut au maximum un point.',
  correction: 'Voir la correction', restart: 'Recommencer', reviewTitle: 'Comprendre tes clics',
  reviewLead: 'Revois les zones au moment où elles étaient actives. Le lecteur de correction permet de revenir dans la vidéo.',
  found: 'Risque détecté', missedOne: 'Risque manqué', replay: 'Revoir ce risque',
  backResult: 'Retour au résultat', clickHistory: 'Journal des clics', noClicks: 'Aucun clic enregistré pour cette séquence.',
  correctClick: 'Détection', duplicateClick: 'Clic répété', falseClick: 'Hors zone / hors fenêtre',
  replayClick: 'Revoir le clic', soundless: 'Lecture sans son', reviewVideo: 'Vidéo de correction',
  testVideo: 'Vidéo interactive : touche une zone à risque', cursor: 'Clavier : flèches pour viser, Entrée ou Espace pour cliquer.',
  storageUnavailable: 'La sauvegarde locale est indisponible. Ton résultat reste consultable tant que cette page est ouverte.',
  saved: 'Résultat enregistré dans ce navigateur.', progress: (n:number,total:number) => `Séquence ${n} / ${total}`,
  reviewSequence: (n:number) => `Séquence ${n}`, total: 'Score de démonstration', select: 'Choisir une démonstration',
}
const nl: typeof fr = {
  eyebrow: 'Videotraining · PermisHub', title: 'Gevaarherkenningstest',
  subtitle: 'Oefen het herkennen van gevaren zoals bij de gevaarherkenningstest.',
  instructions: 'Je bekijkt verschillende rijvideo’s. Zodra je een risicovolle situatie herkent, klik je er rechtstreeks op.',
  start: 'Start de training', demo: 'TECHNISCHE DEMO',
  demoNotice: 'Lokale rijvideo met fictieve risicozones. Deze demo test de interactieve speler; het is geen echt examen of beoordeling van je niveau.',
  demoShort: 'Demo: fictieve zones, geen beoordeling van je niveau.',
  step1: 'Observeer de situatie', step1Body: 'De video start zonder geluid. Let goed op de omgeving.',
  step2: 'Tik op het gevaar', step2Body: 'Klik of tik rechtstreeks op de zone. Een cirkel bevestigt alleen je aanraking.',
  step3: 'Bekijk de uitleg', step3Body: 'Na afloop zie je je score op 10 en de correctie van de fragmenten.',
  local: 'Je resultaten blijven in deze browser. Er wordt geen resultaat naar de server verzonden.',
  previous: 'Bekijk mijn laatste resultaat', next: 'Volgend fragment', loading: 'Video laden…',
  resume: 'Video starten / hervatten', videoError: 'De video kan niet worden afgespeeld. Controleer het bestand of je lokale verbinding.',
  retry: 'Opnieuw proberen', unsupported: 'Je browser ondersteunt deze video niet.',
  tap: 'Tik rechtstreeks op een risicovolle situatie.', noFeedback: 'De correctie volgt na afloop.',
  leave: 'Training verlaten', leaveTitle: 'Deze poging verlaten?', leaveBody: 'De klikken van deze poging gaan verloren.',
  stay: 'Doorgaan met de training', quit: 'Verlaten', result: 'Je resultaat', detected: 'risico’s herkend',
  missed: 'risico’s gemist', falseClicks: 'klikken buiten actieve zones', duplicates: 'herhaalde klikken op een al herkende zone',
  noPenalty: 'Geen strafpunten voor foutieve klikken. Elk risico levert maximaal één punt op.',
  correction: 'Bekijk de correctie', restart: 'Opnieuw beginnen', reviewTitle: 'Begrijp je klikken',
  reviewLead: 'Bekijk de zones op het moment waarop ze actief waren. In de correctie kun je terugspoelen.',
  found: 'Risico herkend', missedOne: 'Risico gemist', replay: 'Bekijk dit risico',
  backResult: 'Terug naar resultaat', clickHistory: 'Klikgeschiedenis', noClicks: 'Geen klikken geregistreerd voor dit fragment.',
  correctClick: 'Herkenning', duplicateClick: 'Herhaalde klik', falseClick: 'Buiten zone / tijdvenster',
  replayClick: 'Bekijk de klik', soundless: 'Zonder geluid', reviewVideo: 'Correctievideo',
  testVideo: 'Interactieve video: tik op een risicozone', cursor: 'Toetsenbord: pijlen om te richten, Enter of Spatie om te klikken.',
  storageUnavailable: 'Lokale opslag is niet beschikbaar. Je resultaat blijft zichtbaar zolang deze pagina openstaat.',
  saved: 'Resultaat opgeslagen in deze browser.', progress: (n:number,total:number) => `Fragment ${n} / ${total}`,
  reviewSequence: (n:number) => `Fragment ${n}`, total: 'Demoscore', select: 'Kies een demo',
}
export function riskCopy(locale: string) { return locale === 'nl' ? nl : fr }
