export type ChallengeQuestion={question:string;options:string[];correct:number;explanation:string;topic:string;topicLabel:string;lesson:string;visual:string}

export const FINAL_CHALLENGE:ChallengeQuestion[]=[
{question:'Feu vert + agent face ou dos. Que faire ?',options:['Continuer grâce au feu vert','M’arrêter','Continuer si personne n’arrive'],correct:1,explanation:"L'agent qualifié est prioritaire sur le feu.",topic:'hierarchy',topicLabel:'Hiérarchie',lesson:'Leçon 1',visual:'agent et feu'},
{question:'Feu rouge + ligne d’arrêt blanche. Où t’arrêter ?',options:['Avant la ligne','Sur la ligne','Après la ligne'],correct:0,explanation:'Arrête-toi devant la ligne blanche.',topic:'lights',topicLabel:'Feux',lesson:'Leçons 2 & 8',visual:'feu rouge et ligne d’arrêt'},
{question:'Que signifie ce panneau ?',options:['Une chaussée glissante','Une interdiction de dépasser','Une direction obligatoire'],correct:0,explanation:'Il annonce un risque à anticiper.',topic:'danger',topicLabel:'Danger',lesson:'Leçon 5',visual:'panneau de danger'},
{question:'Quelle consigne donne ce panneau ?',options:['Tourner à droite','Ne pas tourner à droite','Choisir librement'],correct:0,explanation:'Une obligation impose la direction.',topic:'mandatory',topicLabel:'Obligation',lesson:'Leçon 6',visual:'panneau d’obligation'},
{question:'Peux-tu franchir ce marquage ?',options:['Oui','Non'],correct:0,explanation:'La ligne discontinue peut être franchie.',topic:'markings',topicLabel:'Marquages',lesson:'Leçon 8',visual:'ligne discontinue'},
{question:'Orange fixe, voiture assez loin pour s’arrêter. Que faire ?',options:['Accélérer','S’arrêter','Continuer systématiquement'],correct:1,explanation:'Orange fixe : arrêt si possible en sécurité.',topic:'lights',topicLabel:'Feux',lesson:'Leçon 2',visual:'feu orange'},
{question:'Lequel interdit de franchir le signal dans ce sens ?',options:['Sens interdit','Accès interdit dans les deux sens'],correct:0,explanation:'Le sens interdit concerne ce sens.',topic:'prohibition',topicLabel:'Interdiction',lesson:'Leçon 6',visual:'panneaux d’interdiction'},
{question:'Que précise le panneau additionnel ?',options:['Danger environ 200 m plus loin','Danger durant 200 m','Vitesse 200 km/h'],correct:0,explanation:'Le panneau indique la distance approximative.',topic:'danger',topicLabel:'Danger',lesson:'Leçon 5',visual:'panneau additionnel'},
{question:'Lignes juxtaposées : discontinue de ton côté. Laquelle prendre ?',options:['Toujours la continue','La ligne de mon côté','Aucune'],correct:1,explanation:'Ma ligne d’abord.',topic:'markings',topicLabel:'Marquages',lesson:'Leçon 8',visual:'lignes juxtaposées'},
{question:'Que signifie ce panneau ?',options:['Sens interdit','Voie publique à sens unique','Accès interdit'],correct:1,explanation:'Il informe sur le sens de circulation.',topic:'information',topicLabel:'Indication',lesson:'Leçon 7',visual:'panneau d’indication'},
{question:'Ce panneau interdit-il aussi de tourner à gauche ?',options:['Oui','Non'],correct:1,explanation:'Ce sont deux actions différentes.',topic:'prohibition',topicLabel:'Interdiction',lesson:'Leçon 6',visual:'interdiction de demi-tour'},
{question:'Travaux : blanc et temporaire orange indiquent deux trajectoires. Lequel suivre ?',options:['Le blanc','Le temporaire orange'],correct:1,explanation:'Le temporaire prime dans la règle étudiée.',topic:'markings',topicLabel:'Marquages',lesson:'Leçon 8',visual:'marquage temporaire'},
{question:'Feu rouge + flèche verte + piéton. Que faire ?',options:['Tourner immédiatement','Céder le passage puis suivre la flèche','La flèche ne sert à rien'],correct:1,explanation:'La flèche ne donne pas une priorité absolue.',topic:'special',topicLabel:'Feux particuliers',lesson:'Leçon 3',visual:'flèche verte'},
{question:'Pas engagé, feu rouge, flèche d’évacuation visible. Peux-tu entrer ?',options:['Oui','Non'],correct:1,explanation:'Elle concerne les véhicules déjà engagés.',topic:'special',topicLabel:'Feux particuliers',lesson:'Leçon 3',visual:'flèche d’évacuation'},
{question:'Agent, feu vert, panneau et marquage. Qui décide en premier ?',options:['Le panneau','Le feu vert','L’agent qualifié'],correct:2,explanation:'L’agent est au sommet de la hiérarchie.',topic:'hierarchy',topicLabel:'Hiérarchie',lesson:'Leçon 1',visual:'hiérarchie de la route'}]
