import type { LearningLesson } from './types'

export const LESSON_4: LearningLesson = {
  id: 'comprendre-les-panneaux', moduleId: 'signalisation', title: 'Comprendre les panneaux', description: 'Reconnaître rapidement les grandes familles de panneaux et comprendre ce qu’elles demandent.', xp: 20,
  steps: [
    { type: 'compare', title: 'Tu n’as pas besoin de réciter des centaines de panneaux', body: 'À l’examen, le plus important est de comprendre la logique d’un panneau et la famille à laquelle il appartient.', items: [{ label: '⚠️ DANGER', result: 'J’anticipe' }, { label: '⛔ INTERDICTION', result: 'Je ne peux pas' }, { label: '🔵 OBLIGATION', result: 'Je dois' }, { label: 'ℹ️ INDICATION', result: 'Je suis informé' }] },
    { type: 'text', title: '⚠️ Cette route veut t’avertir', body: 'Un panneau de danger annonce un danger possible. Il ne signifie pas automatiquement « tu dois t’arrêter » : il te demande d’anticiper et d’adapter ta conduite. Exemples : virage dangereux, chaussée glissante, passage pour piétons, enfants.', callout: '🧠 DANGER = ANTICIPER' },
    { type: 'scenario', title: '⛔ Cette fois, quelque chose t’est interdit', body: 'Un signal d’interdiction impose une restriction. Il peut indiquer un sens interdit, un accès interdit ou une catégorie de véhicules interdite.', question: 'Tu rencontres un sens interdit. Que t’indique le panneau ?', options: ['Un danger arrive', 'Je ne peux pas entrer dans ce sens', 'Je dois obligatoirement tourner'], correct: 1, explanation: 'Interdiction = une restriction s’applique : tu ne peux pas entrer dans ce sens.' },
    { type: 'scenario', title: '🔵 Interdit de faire ≠ obligé de faire', body: 'Un panneau d’obligation impose un comportement. Une flèche bleue vers la droite signifie que tu dois suivre la direction indiquée.', question: 'Que dois-tu faire ?', options: ['Tourner à droite', 'Ne pas tourner à droite', 'C’est seulement un conseil'], correct: 0, explanation: 'Une direction obligatoire impose de suivre la direction indiquée.' },
    { type: 'text', title: 'ℹ️ Parfois, le panneau t’informe', body: 'Certains panneaux donnent une information utile sur la route ou son organisation : sens unique, voie sans issue, autoroute ou organisation des voies.', callout: '🧠 INDICATION = « Voici une information sur la route. »' },
    { type: 'hierarchy', title: 'Le réflexe PermisHub', body: 'Avant de chercher la signification exacte, raisonne en trois étapes.', items: ['1️⃣ OBSERVE — Quelle est la famille ?', '2️⃣ COMPRENDS — Danger, interdiction, obligation ou information ?', '3️⃣ APPLIQUE — Qu’est-ce que cela change dans ta conduite ?'], memory: 'Ne récite pas. Raisonne.' },
    { type: 'text', title: 'Regarde aussi sous le panneau', body: 'Un panneau additionnel apporte une information supplémentaire au signal principal. Un danger accompagné de « 200 m » signifie que le danger annoncé se trouve à cette distance.', callout: '⚠️ Piège d’examen : lis toujours le panneau principal et l’information placée sous celui-ci.' },
    { type: 'scenario', title: 'Jeu de reconnaissance', body: '⚠️ Virage dangereux. ⛔ Sens interdit. 🔵 Direction obligatoire. ℹ️ Sens unique. Classe chaque panneau dans sa famille avant de répondre.', question: 'Un panneau triangulaire annonçant un virage dangereux appartient à quelle famille ?', options: ['DANGER', 'INTERDICTION', 'OBLIGATION', 'INDICATION'], correct: 0, explanation: 'Le triangle de danger annonce un risque : DANGER.' },
    { type: 'scenario', title: 'Question piège', body: 'Tu vois un panneau triangulaire annonçant un endroit fréquenté par des enfants.', question: 'Ce panneau impose-t-il à lui seul une limitation de vitesse précise ?', options: ['Oui', 'Non'], correct: 1, explanation: 'Il annonce un danger et demande d’adapter sa conduite, mais ne fixe pas à lui seul une limitation précise.' },
    { type: 'summary', title: 'À retenir', items: ['⚠️ DANGER → J’anticipe', '⛔ INTERDICTION → Je ne peux pas', '🔵 OBLIGATION → Je dois', 'ℹ️ INDICATION → Je suis informé', 'Panneau additionnel → Je lis aussi l’information sous le panneau'] },
  ],
  quiz: [
    { question: 'Un panneau de danger sert principalement à…', options: ['Annoncer un danger possible', 'Interdire systématiquement le passage', 'Imposer systématiquement l’arrêt'], correct: 0, explanation: 'Danger = anticiper et adapter sa conduite.' },
    { question: 'Un panneau d’obligation signifie principalement…', options: ['Attention', 'Je dois…', 'Je ne peux jamais…'], correct: 1, explanation: 'Une obligation impose un comportement.' },
    { question: 'Un panneau d’interdiction signifie principalement…', options: ['Une restriction s’applique', 'Une simple information', 'Une recommandation sans conséquence'], correct: 0, explanation: 'Interdiction = je ne peux pas faire quelque chose.' },
    { question: 'Un panneau d’indication sert notamment à…', options: ['Fournir une information sur la route ou son organisation', 'Annoncer uniquement des dangers', 'Interdire systématiquement le passage'], correct: 0, explanation: 'Indication = information utile sur la route.' },
    { question: 'Un panneau de danger possède un panneau additionnel « 200 m ». Que comprends-tu ?', options: ['Je dois rouler à 200 km/h', 'Le danger annoncé se trouve à la distance indiquée', 'Le panneau ne me concerne plus'], correct: 1, explanation: 'Le panneau additionnel précise la distance du danger.' },
    { question: 'Un panneau annonce un endroit fréquenté par des enfants. À lui seul, ce panneau…', options: ['Fixe automatiquement une limitation précise', 'Annonce un danger et demande d’adapter sa conduite', 'Oblige toujours à s’arrêter'], correct: 1, explanation: 'Danger ≠ automatiquement interdiction ou arrêt.' },
  ],
  resultMessages: { perfect: 'Excellent. Tu sais maintenant lire la logique d’un panneau.', good: 'Bien joué. Encore un petit effort pour reconnaître les familles instantanément.', low: 'Revois les 4 familles avant de continuer.' },
}
