import type { LearningLesson } from './types'

export const LESSON_13: LearningLesson = {
  id: 'les-autres-panneaux-de-priorite',
  moduleId: 'priorities-intersections',
  title: 'Les autres panneaux de priorité',
  description: 'Lire une situation routière pour déterminer qui doit céder.',
  xp: 20,
  steps: [
    { type: 'scenario', visualId: 'M2_PRIORITY_SIGN_RIGHT_01', title: 'Carrefour avec priorité de droite', body: 'Le panneau annonce le régime de priorité qui s’applique au carrefour. Une voiture arrive depuis la droite.', question: 'Une voiture arrive de ta droite. Que dois-tu faire ?', options: ['Passer en premier', 'Lui céder le passage', 'M’arrêter obligatoirement même si elle est loin'], correct: 1, explanation: 'Le signal annonce un carrefour où la priorité de droite est applicable. Tu dois tenir compte du conducteur venant de droite.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_SIGN_RIGHT_01', title: 'Ce panneau ne te donne pas la priorité', body: 'Ne transforme pas une annonce de règle en autorisation de passer.', question: 'Ce panneau signifie-t-il que tu es prioritaire ?', options: ['Oui', 'Non', 'Seulement si tu continues tout droit'], correct: 1, explanation: 'Non. Il t’indique que la priorité de droite s’applique au carrefour.' },
    { type: 'text', visualId: 'M2_PRIORITY_PASSAGE_01', title: 'Priorité de passage', body: 'Une priorité de passage doit être lue avec le panneau et la géométrie exacte de la scène. Le visuel de référence est en attente de validation pour éviter toute règle approximative.', callout: 'PANNEAU ≠ « J’AI PRIORITÉ »' },
    { type: 'scenario', visualId: 'M2_NARROW_YIELD_01', title: 'Passage étroit : tu cèdes', body: 'Le rétrécissement est trop étroit pour permettre le croisement normal. Le panneau B19 organise le passage.', question: 'Une voiture arrive en sens inverse. Qui doit passer en premier ?', options: ['Moi', 'Le véhicule venant en sens inverse', 'Celui qui arrive le premier'], correct: 1, explanation: 'Le panneau B19 t’oblige à céder le passage aux conducteurs venant en sens opposé.' },
    { type: 'scenario', visualId: 'M2_NARROW_YIELD_01', title: 'Le piège de l’arrivée en premier', body: 'La signalisation reste la règle de référence au rétrécissement.', question: 'Tu es arrivé au rétrécissement avant l’autre voiture. Cela te donne-t-il automatiquement la priorité ?', options: ['Oui', 'Non', 'Seulement en agglomération'], correct: 1, explanation: 'Non. Le simple fait d’arriver en premier ne remplace pas le panneau.' },
    { type: 'scenario', visualId: 'M2_NARROW_PRIORITY_01', title: 'Passage étroit : tu as priorité', body: 'Le panneau B21 organise le passage dans le sens opposé au B19.', question: 'Une voiture arrive en face. Que t’indique ce panneau ?', options: ['Je dois lui céder le passage', 'J’ai priorité de passage par rapport au véhicule venant en sens opposé', 'Nous devons tous les deux nous arrêter'], correct: 1, explanation: 'Le signal indique que tu as priorité de passage par rapport aux conducteurs venant en sens opposé.' },
    { type: 'compare', title: 'B19 ou B21 ?', body: 'Lis le panneau avant de te fier à l’ordre d’arrivée. Les deux situations concernent un passage étroit.', items: [{ label: 'B19', result: 'JE CÈDE au trafic en sens inverse' }, { label: 'B21', result: 'J’AI PRIORITÉ sur le trafic en sens inverse' }] },
    { type: 'scenario', visualId: 'M2_NARROW_YIELD_01', title: 'Lecture rapide', body: 'Un véhicule est en face et le rétrécissement ne permet pas le croisement.', question: 'Sans lire une longue règle, qui doit attendre dans cette situation ?', options: ['Moi, car le panneau B19 m’impose de céder', 'Le véhicule en face', 'Personne, nous pouvons nous croiser'], correct: 0, explanation: 'B19 impose de céder au trafic venant en sens inverse.' },
    { type: 'text', title: 'La méthode PermisHub', body: 'Identifie le panneau. Observe le carrefour ou le rétrécissement. Repère les autres véhicules. Détermine qui doit céder. Ne te fie jamais uniquement à « je suis arrivé avant ».', callout: 'PANNEAU + SITUATION = BONNE DÉCISION' },
    { type: 'summary', title: 'À retenir', items: ['Certains panneaux annoncent la règle applicable au carrefour.', 'Le panneau de priorité de droite ne signifie pas « je suis prioritaire ».', 'Dans un passage étroit, la signalisation peut déterminer lequel des deux sens doit céder.', 'B19 → tu cèdes au trafic venant en sens inverse.', 'B21 → tu as priorité sur le trafic venant en sens inverse.', 'Observe toujours le panneau et la situation réelle.'] },
  ],
  quiz: [
    { visualId: 'M2_PRIORITY_SIGN_RIGHT_01', question: 'Quelle règle dois-tu envisager à ce carrefour avant de t’engager ?', options: ['La priorité de droite', 'Une priorité automatique pour moi', 'Un arrêt obligatoire sans raison'], correct: 0, explanation: 'Le panneau B17 annonce un carrefour où la priorité de droite est applicable.' },
    { visualId: 'M2_PRIORITY_PASSAGE_01', question: 'Quelle information manque-t-il avant de résoudre une situation de priorité de passage ?', options: ['Le panneau exact et les trajectoires de la scène', 'La couleur des voitures', 'La météo'], correct: 0, explanation: 'La priorité de passage doit être décidée à partir d’un signal et d’une géométrie non ambigus.' },
    { visualId: 'M2_NARROW_YIELD_01', question: 'Quelle conduite impose le panneau B19 face au véhicule venant en sens inverse ?', options: ['Je cède le passage', 'Je passe toujours en premier', 'Je m’engage sans ralentir'], correct: 0, explanation: 'B19 impose de céder le passage aux conducteurs venant en sens opposé.' },
    { visualId: 'M2_NARROW_PRIORITY_01', question: 'Que signifie le panneau visible dans cette situation étroite ?', options: ['J’ai priorité de passage sur le sens inverse', 'Je dois céder au sens inverse', 'La route devient à sens unique'], correct: 0, explanation: 'B21 donne la priorité de passage par rapport aux conducteurs venant en sens opposé.' },
    { visualId: 'M2_NARROW_YIELD_01', question: 'L’ordre d’arrivée suffit-il à annuler la règle indiquée par le panneau ?', options: ['Non', 'Oui', 'Seulement la nuit'], correct: 0, explanation: 'La signalisation s’applique même si tu arrives le premier au rétrécissement.' },
  ],
  nextLessonLabel: 'Suivant : Tram & priorité →',
  resultMessages: { perfect: 'Excellent. Tu lis le panneau et la situation avant de décider.', good: 'Bien joué. Revois surtout la différence entre B19 et B21.', low: 'Reprends la méthode : panneau, situation, usagers, puis décision.' },
}
