import type { LearningLesson } from './types'

export const LESSON_26: LearningLesson = {
  id: 'panneaux-lies-au-depassement', moduleId: 'manoeuvres-overtaking', title: 'Les panneaux liés au dépassement', description: 'Lis les signaux de dépassement en tenant compte du conducteur et de l’usager dépassé.', xp: 25,
  steps: [
    { type: 'text', visualId: 'M4_OVERTAKE_SIGNS_OVERVIEW_01', title: 'Regarde le panneau… mais aussi le véhicule', body: 'Un panneau d’interdiction de dépassement ne signifie pas forcément qu’il est interdit de dépasser tous les usagers. Identifie le panneau, le conducteur concerné et le véhicule qu’il veut dépasser.', callout: 'PANNEAU + CONDUCTEUR + VÉHICULE DÉPASSÉ' },
    { type: 'text', visualId: 'M4_OVERTAKE_SIGN_GENERAL_01', title: 'Signal général d’interdiction de dépasser', body: 'Ce signal interdit aux conducteurs de dépasser par la gauche un véhicule attelé ou un véhicule à plus de deux roues. Il ne signifie pas « interdiction de dépasser absolument tout usager ».', callout: 'COMPTE LES ROUES.' },
    { type: 'scenario', visualId: 'M4_SIGN_CAR_01', title: 'Une voiture devant', body: 'Le signal général est actif. La ligne est discontinue et la visibilité est excellente.', question: 'La voiture rouge peut-elle dépasser la voiture bleue par la gauche ?', options: ['Oui, car la ligne centrale est discontinue', 'Non, car le signal vise ici ce véhicule à plus de deux roues', 'Oui, puisqu’aucun véhicule n’arrive en sens inverse'], correct: 1, explanation: 'La ligne discontinue et la bonne visibilité ne neutralisent pas le signal. La voiture bleue possède plus de deux roues : elle est concernée par l’interdiction.' },
    { type: 'scenario', visualId: 'M4_SIGN_MOTORCYCLE_01', title: 'Même panneau, moto solo', body: 'Le signal général est actif. Devant la voiture rouge se trouve une motocyclette solo.', question: 'Si les autres conditions permettent le dépassement, le signal l’interdit-il à lui seul ?', options: ['Non, il interdit tous les véhicules motorisés', 'Oui, car une motocyclette solo ne possède que deux roues', 'Non, parce qu’il concerne tous les véhicules rapides'], correct: 1, explanation: 'Ce signal ne vise pas tous les véhicules. Une motocyclette solo possède deux roues et n’entre pas dans la catégorie des véhicules à plus de deux roues visée par le signal. Les autres règles restent applicables.' },
    { type: 'scenario', visualId: 'M4_SIGN_BICYCLE_01', title: 'Même panneau, vélo', body: 'Le signal général est actif. Un cycliste circule devant la voiture rouge.', question: 'Le panneau interdit-il à lui seul de dépasser le cycliste ?', options: ['Oui, il interdit tout dépassement', 'Non, le cycliste n’entre pas dans la catégorie visée par ce signal', 'Oui, parce qu’un vélo est un véhicule'], correct: 1, explanation: 'Le vélo possède deux roues et n’entre pas dans la catégorie des véhicules à plus de deux roues visée ici. Les autres conditions du dépassement restent évidemment applicables.' },
    { type: 'scenario', visualId: 'M4_SIGN_SIDECAR_COMPARE_01', title: 'Le piège du side-car', body: 'Le même panneau est présent. Compare une moto solo et une moto avec side-car.', question: 'Pourquoi la réponse change-t-elle entre ces deux situations ?', options: ['La moto avec side-car possède plus de deux roues', 'La moto avec side-car est une voiture particulière', 'Le panneau ne s’applique qu’aux motos avec passager'], correct: 0, explanation: 'Le side-car fait passer la motocyclette de deux à trois roues. Elle entre donc dans la catégorie des véhicules à plus de deux roues visée par le signal.' },
    { type: 'scenario', visualId: 'M4_SIGN_SIDECAR_SCENE_01', title: 'Raisonnement complet', body: 'La ligne est discontinue, la visibilité excellente et aucun véhicule n’arrive en sens inverse. Une moto avec side-car est devant.', question: 'Quel élément détermine ici l’interdiction de dépasser ?', options: ['Le side-car fait entrer le véhicule dans la catégorie visée par le signal', 'La ligne discontinue interdit le dépassement d’une motocyclette', 'Une motocyclette ne peut jamais être dépassée après ce signal'], correct: 0, explanation: 'Le piège n’est ni la visibilité ni le marquage. Avec son side-car, la motocyclette possède trois roues et est concernée par l’interdiction.' },
    { type: 'scenario', visualId: 'M4_OVERTAKE_SIGN_END_01', title: 'Fin de l’interdiction', body: 'Le signal noir et blanc correspondant met fin à l’interdiction de dépassement signalée précédemment.', question: 'Que change ce signal ?', options: ['L’interdiction signalée précédemment prend fin', 'Toute limitation de vitesse prend aussi fin', 'La voiture rouge obtient la priorité pour dépasser'], correct: 0, explanation: 'Le signal met fin à l’interdiction correspondante. Il ne donne aucune priorité et n’autorise pas automatiquement un dépassement dangereux.' },
    { type: 'text', visualId: 'M4_OVERTAKE_SIGN_TRUCK_01', title: 'Le signal pour certains transports de choses', body: 'Ce signal concerne les conducteurs de véhicules ou trains de véhicules affectés au transport de choses dont la MMA dépasse 3 500 kg.', callout: 'TRANSPORT DE CHOSES + MMA > 3 500 KG' },
    { type: 'scenario', visualId: 'M4_TRUCK_SIGN_CAR_DRIVER_01', title: 'Qui conduit ?', body: 'Le signal spécifique est présent. Une voiture particulière rouge suit une voiture bleue ; les autres conditions sont correctes.', question: 'Ce signal interdit-il à lui seul à la voiture rouge de dépasser ?', options: ['Oui, il interdit tout dépassement d’une voiture', 'Non, il vise une catégorie particulière de véhicules affectés au transport de choses', 'Oui, parce que la voiture bleue possède quatre roues'], correct: 1, explanation: 'Il faut d’abord regarder qui conduit. Ce signal spécifique ne vise pas une voiture particulière ordinaire.' },
    { type: 'scenario', visualId: 'M4_TRUCK_SIGN_WEIGHT_COMPARE_01', title: 'Le piège numérique', body: 'Deux véhicules sont affectés au transport de choses : l’un a une MMA de 3 500 kg, l’autre de 3 501 kg.', question: 'Lequel entre dans la catégorie visée par cette règle de MMA ?', options: ['Les deux', 'Seulement le véhicule de 3 501 kg', 'Seulement le véhicule de 3 500 kg'], correct: 1, explanation: 'La règle vise une MMA qui dépasse 3 500 kg. 3 500 kg exactement ne dépasse pas cette valeur ; 3 501 kg la dépasse.' },
    { type: 'scenario', visualId: 'M4_TRUCK_SIGN_MOTORCYCLE_01', title: 'Double analyse', body: 'Un véhicule de transport de choses de 4 000 kg est concerné par le signal. Une moto solo se trouve devant lui.', question: 'Le signal interdit-il à lui seul de dépasser cette moto solo ?', options: ['Oui, puisqu’il dépasse 3 500 kg', 'Non, il faut aussi regarder la catégorie du véhicule dépassé', 'Oui, tout véhicule motorisé est visé'], correct: 1, explanation: 'Le conducteur entre bien dans la catégorie visée par le signal, mais il faut aussi identifier ce qu’il veut dépasser. Une moto solo n’a que deux roues.' },
    { type: 'scenario', visualId: 'M4_SIGN_CUMULATIVE_01', title: 'Le panneau ne suffit pas', body: 'Le signal général ne vise pas à lui seul le cycliste devant. Mais la route est en virage et la visibilité vers l’avant est insuffisante.', question: 'La voiture rouge peut-elle commencer son dépassement ?', options: ['Oui, puisque le cycliste n’est pas visé par le signal', 'Non, car la visibilité vers l’avant reste insuffisante', 'Oui, si elle met son clignotant gauche'], correct: 1, explanation: 'Ne pas être interdit par un panneau ne signifie pas que le dépassement est permis dans toutes les circonstances. La visibilité insuffisante empêche ici de commencer la manœuvre.' },
    { type: 'summary', title: 'Face à un panneau de dépassement', items: ['Identifie le panneau.', 'Qui est-ce que je conduis ?', 'Qui est-ce que je veux dépasser ?', 'Combien de roues ?', 'L’interdiction est-elle encore active ?', 'Les autres conditions permettent-elles le dépassement ?'] }
  ],
  quiz: [
    { visualId: 'M4_SIGN_CAR_01', question: 'Le signal général est actif devant une voiture bleue. Quelle réponse est correcte ?', options: ['Le dépassement est interdit par ce signal', 'La ligne discontinue suffit à autoriser', 'La visibilité suffit à autoriser'], correct: 0, explanation: 'La voiture bleue possède plus de deux roues et est concernée.' },
    { visualId: 'M4_SIGN_MOTORCYCLE_01', question: 'Le signal général interdit-il à lui seul de dépasser une moto solo ?', options: ['Oui, toutes les motos sont visées', 'Non, une moto solo possède deux roues', 'Oui, tout véhicule motorisé est visé'], correct: 1, explanation: 'La moto solo n’entre pas dans la catégorie des véhicules à plus de deux roues visée ici.' },
    { visualId: 'M4_SIGN_BICYCLE_01', question: 'Quel élément compte pour le cycliste ?', options: ['Il n’est pas visé par ce signal seul', 'Il est toujours visé car il est lent', 'Il est visé car il circule à droite'], correct: 0, explanation: 'Le signal ne vise pas à lui seul le vélo à deux roues.' },
    { visualId: 'M4_SIGN_SIDECAR_SCENE_01', question: 'Pourquoi la moto avec side-car est-elle concernée ?', options: ['Elle possède trois roues', 'Elle roule plus vite', 'Elle est motorisée'], correct: 0, explanation: 'Le side-car fait passer la motocyclette à plus de deux roues.' },
    { visualId: 'M4_OVERTAKE_SIGN_END_01', question: 'Que signifie le signal de fin ?', options: ['La fin de l’interdiction signalée', 'Une priorité de dépassement', 'La fin de toute limitation'], correct: 0, explanation: 'La fin d’interdiction ne rend pas un dépassement automatiquement sûr.' },
    { visualId: 'M4_TRUCK_SIGN_CAR_DRIVER_01', question: 'Une voiture particulière est-elle visée par le signal spécifique aux transports de choses ?', options: ['Oui, toujours', 'Non, pas à elle seule', 'Oui, si la voiture devant a quatre roues'], correct: 1, explanation: 'Le signal vise une catégorie particulière de véhicules affectés au transport de choses.' },
    { visualId: 'M4_TRUCK_SIGN_WEIGHT_COMPARE_01', question: 'Quelle MMA dépasse 3 500 kg ?', options: ['3 500 kg', '3 501 kg', 'Les deux'], correct: 1, explanation: 'La règle emploie le mot « dépasse ».' },
    { visualId: 'M4_SIGN_FINAL_ANALYSIS_01', question: 'Un véhicule de transport de choses de 4 200 kg suit une moto avec side-car. Le panneau C39 est actif. Peut-il dépasser ?', options: ['Oui, une moto a toujours deux roues', 'Non, le conducteur et le véhicule dépassé sont tous deux concernés', 'Oui, car la ligne est discontinue'], correct: 1, explanation: 'Le véhicule de transport dépasse 3 500 kg et le side-car fait entrer la moto dans la catégorie de plus de deux roues.' }
  ],
  nextLessonLabel: 'Suivant : Dépasser les cyclistes et autres usagers →',
  resultMessages: { perfect: 'Excellent. Tu lis le panneau et toute la situation.', good: 'Bon travail. Revois qui conduit et qui est dépassé.', low: 'Reprends la méthode : panneau, conducteur, véhicule dépassé, roues, durée et sécurité.' }
}
