import type { LearningLesson } from './types'
export const LESSON_18: LearningLesson={id:'adapter-sa-vitesse-a-la-situation',moduleId:'speed-road-position',title:'Adapter sa vitesse à la situation',description:'Voir le danger, l’anticiper et réduire son allure si nécessaire.',xp:20,steps:[
{type:'scenario',visualId:'M3_ADAPT_SPEED_50_01',title:'50 ne signifie pas toujours 50',body:'La vitesse maximale autorisée est de 50 km/h, mais un danger est visible plus loin.',question:'Dois-tu forcément continuer à 50 km/h ?',options:['Oui','Non','Oui si je suis prioritaire'],correct:1,explanation:'Une limitation indique une vitesse maximale. Si la situation présente un danger, tu dois adapter ton allure.'},
{type:'scenario',visualId:'M3_ADAPT_CHILDREN_01',title:'Enfants',body:'Le panneau et les enfants près de la chaussée demandent une attention accrue.',question:'Que dois-tu faire ?',options:['Adapter mon allure à la situation','Continuer sans changer mon comportement','Accélérer pour quitter rapidement la zone'],correct:0,explanation:'En présence d’enfants, adapte ton allure et sois particulièrement attentif.'},
{type:'scenario',visualId:'M3_ADAPT_CHILDREN_01',title:'Le piège du panneau enfants',body:'Le panneau indique un danger.',question:'Ce panneau impose-t-il, à lui seul, une nouvelle limitation chiffrée ?',options:['Oui, automatiquement 30 km/h','Non','Oui, automatiquement 20 km/h'],correct:1,explanation:'Ce panneau ne crée pas, à lui seul, une limitation chiffrée. Tu dois cependant adapter ton allure.'},
{type:'scenario',visualId:'M3_ADAPT_SLIPPERY_01',title:'Chaussée glissante',body:'Les conditions de la route rendent le danger compréhensible.',question:'Quel comportement est le plus adapté ?',options:['Adapter mon allure aux conditions','Rouler exactement à la vitesse maximale indiquée','Accélérer pour traverser rapidement la zone'],correct:0,explanation:'Une chaussée glissante constitue un danger. Adapte ton allure aux conditions rencontrées.'},
{type:'scenario',visualId:'M3_ADAPT_CURVE_01',title:'Virage et visibilité',body:'La configuration du virage réduit la visibilité.',question:'Quelle attitude est correcte ?',options:['Adapter mon allure avant d’aborder le virage','Accélérer avant le virage','Garder obligatoirement la vitesse maximale autorisée'],correct:0,explanation:'Une visibilité limitée augmente le risque. Adapte ton allure avant d’aborder la situation dangereuse.'},
{type:'scenario',visualId:'M3_ADAPT_PEDESTRIAN_01',title:'Passage pour piétons',body:'Un piéton s’engage sur le passage.',question:'Quelle réaction est correcte ?',options:['Adapter immédiatement mon allure et respecter son passage','Maintenir ma vitesse parce que je suis déjà sur la chaussée','Accélérer avant qu’il traverse'],correct:0,explanation:'Tu dois tenir compte du piéton et lui permettre de traverser conformément à la situation.'},
{type:'scenario',visualId:'M3_ADAPT_CYCLIST_01',title:'Cycliste',body:'Un usager vulnérable est proche de ta trajectoire.',question:'Que dois-tu faire en premier ?',options:['Adapter mon allure et observer la situation','Accélérer immédiatement pour le dépasser','Klaxonner jusqu’à ce qu’il quitte la chaussée'],correct:0,explanation:'Adapte ton allure avant de décider d’une éventuelle manœuvre.'},
{type:'scenario',visualId:'M3_ADAPT_SCHOOL_BUS_01',title:'Transport scolaire',body:'Tu approches d’un véhicule de transport scolaire.',question:'Quel comportement dois-tu adopter ?',options:['Ralentir fortement','Maintenir systématiquement la même vitesse','Accélérer pour le dépasser'],correct:0,explanation:'À l’approche d’un véhicule de transport scolaire, tu dois ralentir fortement.'},
{type:'scenario',visualId:'M3_ADAPT_BUS_01',title:'Bus',body:'Le bus est à l’arrêt et des passagers sont visibles.',question:'Tu longes ce bus. Quelle attitude est correcte ?',options:['Modérer ma vitesse','Accélérer systématiquement','Maintenir ma vitesse sans observer les alentours'],correct:0,explanation:'Lorsque tu longes un bus, tu dois modérer ta vitesse.'},
{type:'scenario',visualId:'M3_ADAPT_BUS_01',title:'Passagers du bus',body:'Des passagers descendent du côté où tu circules.',question:'Que dois-tu faire ?',options:['M’arrêter pour les laisser passer','Accélérer avant qu’ils traversent','Continuer parce qu’ils doivent attendre'],correct:0,explanation:'Lorsque tu longes un transport en commun du côté de l’embarquement ou du débarquement, tu dois permettre aux passagers de passer.'},
{type:'scenario',visualId:'M3_ADAPT_NARROWING_01',title:'Rétrécissement',body:'La chaussée se rétrécit devant toi.',question:'Quelle est la première bonne réaction ?',options:['Adapter mon allure et observer les autres usagers','Accélérer pour passer avant les autres','Rouler au milieu de la chaussée sans ralentir'],correct:0,explanation:'Le rétrécissement demande davantage d’anticipation. Adapte ton allure et observe la circulation.'},
{type:'text',title:'Méthode PermisHub',body:'Vitesse autorisée : danger ? visibilité ? usagers vulnérables ? conditions de la route ? J’adapte mon allure.',callout:'LA LIMITATION EST UN MAXIMUM, PAS UNE VITESSE À ATTEINDRE À TOUT PRIX.'},
{type:'summary',title:'À retenir',items:['Une limitation est une vitesse maximale.','En présence d’un danger, adapte ton allure.','Enfants, chaussée glissante et visibilité réduite demandent une allure adaptée.','Transport scolaire : ralentir fortement.','En longeant un bus : modérer sa vitesse.']}
],quiz:[
{visualId:'M3_ADAPT_CHILDREN_01',question:'La limitation actuelle permet une vitesse supérieure. Des enfants sont présents près de la chaussée. Que dois-tu faire ?',options:['Adapter mon allure','Maintenir obligatoirement la vitesse maximale','Accélérer'],correct:0,explanation:'Les enfants près de la chaussée demandent une allure adaptée.'},
{visualId:'M3_ADAPT_CHILDREN_01',question:'Le panneau visible impose-t-il automatiquement 30 km/h ?',options:['Oui','Non','Seulement hors agglomération'],correct:1,explanation:'Le panneau enfants signale un danger ; il ne crée pas seul une limitation chiffrée.'},
{visualId:'M3_ADAPT_SLIPPERY_01',question:'La chaussée est glissante. Quelle attitude est correcte ?',options:['Adapter mon allure','Rouler systématiquement à la limitation maximale','Accélérer'],correct:0,explanation:'La chaussée glissante demande une allure adaptée.'},
{visualId:'M3_ADAPT_SCHOOL_BUS_01',question:'Tu approches de ce transport scolaire. Que dois-tu faire ?',options:['Ralentir fortement','Accélérer','Ne rien changer'],correct:0,explanation:'À l’approche d’un transport scolaire, tu dois ralentir fortement.'},
{visualId:'M3_ADAPT_BUS_01',question:'Tu longes ce bus. Que dois-tu faire ?',options:['Modérer ma vitesse','Accélérer','Maintenir ma vitesse quoi qu’il arrive'],correct:0,explanation:'Modère ta vitesse lorsque tu longes le bus.'},
{visualId:'M3_ADAPT_CURVE_01',question:'La visibilité est limitée dans ce virage. Quelle attitude est correcte ?',options:['Adapter mon allure avant le virage','Accélérer dans le virage','Rouler obligatoirement à la vitesse maximale autorisée'],correct:0,explanation:'Adapte ton allure avant d’aborder un virage à visibilité limitée.'}
],nextLessonLabel:'Suivant : Position sur la chaussée →',resultMessages:{perfect:'Excellent. Tu sais distinguer vitesse maximale et vitesse adaptée.',good:'Bon travail. Revois les dangers qui demandent une allure adaptée.',low:'Reprends la méthode : observe le danger, anticipe puis adapte ton allure.'}}
