import type { LearningLesson } from './types'

export const LESSON_23: LearningLesson = {
  id: 'comprendre-le-depassement', moduleId: 'manoeuvres-overtaking', title: 'Comprendre le dépassement', description: 'Dépasser, ce n’est pas seulement aller plus vite. Il faut aussi savoir où passer et comment réagir.', xp: 20,
  steps: [
    { type: 'text', visualId: 'M4_OVERTAKE_OVERVIEW_01', title: 'Comprendre le dépassement', body: 'Deux véhicules roulent dans le même sens. La voiture rouge commence à passer devant la voiture bleue.', callout: 'DÉPASSER, CE N’EST PAS SEULEMENT ALLER PLUS VITE.' },
    { type: 'text', visualId: 'M4_OVERTAKE_VS_CROSSING_01', title: 'Croisement ou dépassement ?', body: 'Croisement : les usagers viennent en sens opposés. Dépassement : un usager passe devant un autre qui circule dans le même sens.', callout: 'DÉPASSEMENT : PAR LA GAUCHE. CROISEMENT : PAR LA DROITE.' },
    { type: 'text', title: 'Les fondamentaux', body: 'Pendant le dépassement, conserve une distance latérale suffisante. Si tu es dépassé, garde la même allure et serre à droite autant que possible.', callout: 'UNE RÈGLE RESPECTÉE ≠ MANŒUVRE ENTIÈREMENT CORRECTE.' },
    { type: 'scenario', visualId: 'M4_OVERTAKE_ANALYSIS_01', title: 'Identifier l’erreur', body: 'La voiture rouge dépasse par la gauche avec un espace latéral suffisant. La voiture bleue accélère pendant la manœuvre.', question: 'Quel conducteur adopte ici un comportement incorrect ?', options: ['Le conducteur rouge, parce qu’il dépasse par la gauche', 'Le conducteur bleu, parce qu’il accélère pendant qu’il est dépassé', 'Aucun des deux, si la limitation de vitesse est respectée'], correct: 1, explanation: 'Le véhicule dépassé doit garder la même allure et serrer à droite autant que possible. Il ne doit pas accélérer pendant le dépassement.' },
    { type: 'scenario', visualId: 'M4_OVERTAKE_ANALYSIS_02', title: 'Plusieurs règles', body: 'La voiture rouge dépasse par la gauche, mais l’espace latéral est manifestement insuffisant.', question: 'Le conducteur rouge dépasse par le bon côté. Son dépassement est-il pour autant correctement effectué ?', options: ['Oui, puisqu’il passe par la gauche', 'Non, l’espace latéral est insuffisant', 'Oui, si sa vitesse reste sous la limitation'], correct: 1, explanation: 'Passer par la gauche ne suffit pas. Une distance latérale suffisante doit également être conservée pendant le dépassement.' },
    { type: 'scenario', visualId: 'M4_OVERTAKE_ANALYSIS_03', title: 'Comportement du véhicule dépassé', body: 'La voiture rouge commence un dépassement. La voiture bleue se déporte légèrement vers la gauche.', question: 'Quelle réaction de la voiture bleue serait correcte ?', options: ['Se rapprocher de la gauche pour empêcher le dépassement', 'Garder la même allure et serrer à droite autant que possible', 'Accélérer jusqu’à ce que la voiture rouge abandonne'], correct: 1, explanation: 'Le véhicule dépassé garde la même allure et serre à droite autant que possible pour faciliter le dépassement.' },
    { type: 'scenario', visualId: 'M4_OVERTAKE_ANALYSIS_04', title: 'Ne pas se fier à un seul détail', body: 'La voiture rouge dépasse par la gauche et la bleue reste à droite, mais les deux voitures sont beaucoup trop proches latéralement.', question: 'Quelle affirmation décrit le mieux cette situation ?', options: ['Le dépassement est correct puisque la voiture rouge passe à gauche', 'Le dépassement est incorrect car la distance latérale est insuffisante', 'Le dépassement est correct puisque la voiture bleue reste à droite'], correct: 1, explanation: 'Le bon côté de dépassement ne suffit pas. Il faut également conserver une distance latérale suffisante.' },
    { type: 'scenario', visualId: 'M4_OVERTAKE_ANALYSIS_05', title: 'Trouver les deux comportements corrects', body: 'La voiture rouge dépasse par la gauche avec un espace suffisant. La voiture bleue reste à droite et garde son allure.', question: 'Pourquoi cette situation est-elle correcte ?', options: ['Parce que le conducteur rouge passe à gauche et le conducteur bleu facilite le dépassement', 'Uniquement parce que la voiture rouge roule plus vite', 'Parce que le véhicule dépassé doit accélérer lorsque l’autre véhicule arrive à sa hauteur'], correct: 0, explanation: 'Le dépassement s’effectue par la gauche avec un espace suffisant. Le véhicule dépassé garde son allure et serre à droite autant que possible.' },
    { type: 'summary', title: 'À retenir', items: ['Croisement = sens opposés.', 'Dépassement = même sens.', 'Le dépassement se fait normalement par la gauche.', 'Garde une distance latérale suffisante.', 'Si tu es dépassé : garde la même allure et serre à droite autant que possible.'] },
  ],
  quiz: [
    { visualId: 'M4_OVERTAKE_ANALYSIS_01', question: 'Quel comportement complique le dépassement dans cette situation ?', options: ['La voiture rouge passe par la gauche', 'La voiture bleue accélère pendant le dépassement', 'Les voitures circulent dans le même sens'], correct: 1, explanation: 'Le véhicule dépassé doit garder la même allure.' },
    { visualId: 'M4_OVERTAKE_ANALYSIS_02', question: 'Quelle règle reste à respecter malgré le bon côté de dépassement ?', options: ['Conserver une distance latérale suffisante', 'Accélérer dès que la voiture bleue apparaît', 'Rouler près de la voiture bleue'], correct: 0, explanation: 'Le bon côté ne dispense pas de conserver une distance latérale suffisante.' },
    { visualId: 'M4_OVERTAKE_ANALYSIS_03', question: 'Quelle action de la voiture bleue rendrait la manœuvre plus prévisible ?', options: ['Se déporter vers la gauche', 'Garder son allure et serrer à droite autant que possible', 'Accélérer au moment où la rouge arrive'], correct: 1, explanation: 'Le véhicule dépassé facilite le dépassement en gardant son allure et en serrant à droite autant que possible.' },
    { visualId: 'M4_OVERTAKE_ANALYSIS_04', question: 'Pourquoi le dépassement reste-t-il incorrect malgré la bonne position de la voiture bleue ?', options: ['La voiture rouge passe à gauche', 'La distance latérale est insuffisante', 'Les deux véhicules roulent dans le même sens'], correct: 1, explanation: 'Une distance latérale suffisante doit être conservée.' },
    { visualId: 'M4_OVERTAKE_ANALYSIS_05', question: 'Quelle combinaison rend la manœuvre correcte ?', options: ['Rouge à gauche, espace suffisant, bleu prévisible à droite', 'Rouge à gauche, bleu qui accélère', 'Rouge à droite, bleu qui se déporte à gauche'], correct: 0, explanation: 'Le dépassement respecte ici le bon côté, l’espace latéral et le comportement prévisible du véhicule dépassé.' },
  ],
  nextLessonLabel: 'Suivant : Dépasser en toute sécurité →', resultMessages: { perfect: 'Excellent. Tu sais analyser une manœuvre au-delà d’une seule règle.', good: 'Bon travail. Revois les détails qui rendent un dépassement incomplet ou imprévisible.', low: 'Reprends la combinaison des règles : gauche, espace latéral et comportement du véhicule dépassé.' },
}
