import type { LearningLesson } from './types'

export const LESSON_10: LearningLesson = {
  id: 'les-pieges-et-exceptions-a-la-priorite-de-droite',
  moduleId: 'priorities-intersections',
  title: 'Les pièges et exceptions à la priorité de droite',
  description: 'Identifier l’origine d’un usager avant de décider si la priorité de droite s’applique.',
  xp: 20,
  steps: [
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_PARKING_01', title: 'Une sortie de parking', body: 'La voiture arrive physiquement de ta droite, mais observe d’où elle débouche.', question: 'Cette voiture arrive de ta droite, mais elle sort d’un parking. Dois-tu lui céder le passage uniquement parce qu’elle vient de droite ?', options: ['Oui', 'Non', 'Seulement si elle tourne à droite'], correct: 1, explanation: 'Non. Un conducteur qui débouche d’un parking ne bénéficie pas de la priorité de droite dans cette situation.' },
    { type: 'text', visualId: 'M2_PRIORITY_EXCEPTION_PARKING_01', title: 'Le piège', body: 'Regarder uniquement la position du véhicule est une erreur. Pose-toi aussi la question : d’où vient-il ?', callout: 'DROITE ≠ TOUJOURS PRIORITAIRE' },
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_PROPERTY_01', title: 'Une propriété riveraine', body: 'La voiture sort d’une entrée carrossable à droite. Son origine est différente d’une voie publique normale.', question: 'Une voiture sort de cette propriété et arrive de ta droite. Qui doit céder ?', options: ['Je dois lui céder le passage', 'Le conducteur qui sort de la propriété doit céder', 'Celui qui accélère le plus passe'], correct: 1, explanation: 'Le conducteur qui sort d’une propriété ne bénéficie pas simplement de la priorité de droite.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_DIRTROAD_01', title: 'Le chemin de terre', body: 'La route sur laquelle tu circules est revêtue. À droite, la voiture débouche d’un chemin clairement non revêtu.', question: 'La voiture arrive de ta droite mais débouche d’un chemin de terre. Est-elle prioritaire grâce à la priorité de droite ?', options: ['Oui', 'Non', 'Seulement hors agglomération'], correct: 1, explanation: 'Non. Le conducteur qui débouche d’un chemin de terre ne bénéficie pas ici de la priorité de droite.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_DIRTROAD_02', title: 'Quelques mètres goudronnés', body: 'Ne te fie pas seulement aux derniers mètres visibles près du carrefour : observe l’origine complète de la voie.', question: 'Les derniers mètres du chemin sont goudronnés. La priorité de droite s’applique-t-elle automatiquement ?', options: ['Oui', 'Non', 'Seulement en agglomération'], correct: 1, explanation: 'Non. Le fait que la fin du chemin soit revêtue ne change pas automatiquement son origine : il débouche d’un chemin de terre.' },
    { type: 'text', visualId: 'M2_PRIORITY_EXCEPTION_CYCLEPATH_01', title: 'Infrastructure cyclable : à distinguer', body: 'Une piste cyclable séparée et une bande cyclable suggérée ne se confondent pas. La scène exacte et sa signalisation doivent être vérifiées avant d’en tirer une règle de priorité.', callout: 'OBSERVE L’INFRASTRUCTURE ET LA SIGNALISATION' },
    { type: 'text', visualId: 'M2_PRIORITY_EXCEPTION_ONEWAY_01', title: 'Sens interdit : lire toute la signalisation', body: 'Un sens interdit peut avoir des exceptions indiquées par des panneaux additionnels. Analyse toujours le panneau et la voie avant de conclure.', callout: 'UN PANNEAU ADDITIONNEL PEUT CHANGER LA SITUATION' },
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_TRAM_01', title: 'Le tram', body: 'Un tram arrive de gauche. Ne le traite pas comme une voiture ordinaire dans ton raisonnement de priorité.', question: 'Le tram arrive de ta gauche. Peux-tu simplement appliquer la priorité de droite et passer ?', options: ['Oui', 'Non', 'Seulement si le tram ralentit'], correct: 1, explanation: 'Non. La priorité du tram sera approfondie dans une leçon dédiée ; ici, retiens que « personne à droite = je passe » ne suffit pas.' },
    { type: 'text', title: 'La méthode PermisHub', body: 'À chaque carrefour, observe la signalisation, regarde d’où viennent les autres usagers, identifie le type de voie ou de sortie, puis vérifie les usagers particuliers. Ensuite seulement, décide si la priorité de droite s’applique.', callout: '« DROITE » NE SUFFIT PAS. IL FAUT COMPRENDRE LA SITUATION.' },
    { type: 'summary', title: 'Tu as compris le piège principal', items: ['Venir de droite ne signifie pas toujours être prioritaire.', 'Observe l’origine du véhicule.', 'Parking et propriété peuvent modifier ton raisonnement.', 'Un chemin de terre est un piège classique.', 'Observe attentivement les infrastructures cyclables.', 'Le tram demande un raisonnement particulier.'] },
  ],
  quiz: [
    { visualId: 'M2_PRIORITY_EXCEPTION_PARKING_01', question: 'Quel détail doit te faire vérifier la règle avant de céder à cette voiture située à droite ?', options: ['Elle vient d’une sortie de parking', 'Sa couleur', 'La taille du parking'], correct: 0, explanation: 'Son origine compte : elle débouche d’un parking.' },
    { visualId: 'M2_PRIORITY_EXCEPTION_PROPERTY_01', question: 'Dans cette scène, quel élément distingue la voiture de droite d’un usager arrivant par une rue ?', options: ['Elle sort d’une propriété', 'Elle est proche du trottoir', 'Elle roule lentement'], correct: 0, explanation: 'L’entrée carrossable indique qu’elle sort d’une propriété.' },
    { visualId: 'M2_PRIORITY_EXCEPTION_DIRTROAD_01', question: 'Quel type de voie est à l’origine de la voiture située à droite ?', options: ['Un chemin de terre', 'Une route principale', 'Une zone de stationnement'], correct: 0, explanation: 'Elle débouche d’un chemin de terre : ne lui attribue pas automatiquement la priorité de droite.' },
    { visualId: 'M2_PRIORITY_EXCEPTION_DIRTROAD_02', question: 'Pourquoi faut-il regarder plus loin que la fin goudronnée de cette voie ?', options: ['Parce que son origine est un chemin de terre', 'Parce que la voiture est blanche', 'Parce que la route est étroite'], correct: 0, explanation: 'Les derniers mètres revêtus ne changent pas automatiquement l’origine de cette voie.' },
    { visualId: 'M2_PRIORITY_EXCEPTION_TRAM_01', question: 'Quelle attitude adoptes-tu face au tram visible sur cette scène ?', options: ['Je l’analyse avec les règles propres au tram', 'Je l’ignore puisqu’il arrive de gauche', 'Je passe avant lui si je suis déjà proche'], correct: 0, explanation: 'Un tram demande un raisonnement particulier : ne réduis pas la situation à la seule priorité de droite.' },
  ],
  nextLessonLabel: 'Suivant : STOP & Cédez le passage →',
  resultMessages: { perfect: 'Très bien. Tu observes l’origine des usagers avant de décider.', good: 'Bon réflexe. Revois les origines de voie qui changent ton raisonnement.', low: 'Reprends la méthode : signalisation, origine de la voie, usagers particuliers, puis priorité de droite si elle s’applique.' },
}
