import type { LearningLesson } from './types'
export const LESSON_19:LearningLesson={id:'position-sur-la-chaussee',moduleId:'speed-road-position',title:'Bien se positionner sur la chaussée',description:'Savoir où rouler est aussi important que savoir à quelle vitesse rouler.',xp:20,steps:[
{type:'scenario',visualId:'M3_POSITION_RIGHT_01',title:'Où dois-tu rouler ?',body:'La route est à double sens, avec une bande par sens.',question:'Où dois-tu normalement te positionner ?',options:['Du côté droit de la chaussée','Au milieu de la chaussée','Du côté gauche de la chaussée'],correct:0,explanation:'En règle générale, tu dois tenir ta droite. Ne roule pas inutilement au milieu de la chaussée.'},
{type:'scenario',visualId:'M3_POSITION_RIGHT_01',title:'Le piège du milieu',body:'La route est complètement libre.',question:'Peux-tu rouler continuellement près du milieu simplement parce qu’aucun véhicule n’arrive ?',options:['Oui','Non','Oui uniquement le jour'],correct:1,explanation:'L’absence de circulation ne justifie pas de rouler inutilement au milieu. Garde une position correcte.'},
{type:'scenario',visualId:'M3_POSITION_DIVIDED_01',title:'Chaussées séparées',body:'Deux bandes vont dans ton sens, les chaussées opposées sont séparées par une berme centrale.',question:'Quelle position dois-tu normalement privilégier lorsque tu ne dépasses pas ?',options:['La bande de droite','La bande de gauche','N’importe quelle bande'],correct:0,explanation:'En règle générale, tiens ta droite. La bande de gauche ne doit pas être choisie simplement parce qu’elle paraît plus libre.'},
{type:'scenario',visualId:'M3_POSITION_DIVIDED_01',title:'Bande de gauche sans raison',body:'La bande de droite est libre et tu ne dépasses personne.',question:'Peux-tu rester inutilement sur la bande de gauche ?',options:['Oui','Non','Oui si je roule à la vitesse maximale autorisée'],correct:1,explanation:'Lorsque rien ne justifie ton maintien à gauche, reprends une position correcte à droite.'},
{type:'scenario',visualId:'M3_POSITION_OBSTACLE_01',title:'Obstacle sur la chaussée',body:'Un obstacle bloque une partie de ton côté de la chaussée.',question:'Que dois-tu faire ?',options:['Adapter ma trajectoire pour le contourner prudemment','Monter systématiquement sur le trottoir','Continuer tout droit dans l’obstacle'],correct:0,explanation:'Un obstacle peut t’obliger à modifier temporairement ta position. Observe la circulation et contourne-le prudemment lorsque la situation le permet.'},
{type:'scenario',visualId:'M3_POSITION_OBSTACLE_01',title:'Après l’obstacle',body:'La situation redevient normale après le contournement.',question:'Que dois-tu faire ?',options:['Reprendre une position correcte à droite','Continuer au milieu de la chaussée','Rester du côté gauche'],correct:0,explanation:'La modification de trajectoire est temporaire. Après l’obstacle, reprends ta position normale lorsque tu peux le faire en sécurité.'},
{type:'scenario',visualId:'M3_POSITION_NARROW_01',title:'Route étroite',body:'Un véhicule arrive en sens inverse.',question:'Quel comportement est correct ?',options:['Tenir suffisamment ma droite tout en restant en sécurité','Rouler volontairement au milieu','Me déporter vers la gauche'],correct:0,explanation:'Lors d’un croisement, un positionnement correct aide à conserver une distance latérale suffisante.'},
{type:'scenario',visualId:'M3_POSITION_SHOULDER_01',title:'Accotement',body:'L’accotement est clairement visible à droite.',question:'Est-il simplement une bande supplémentaire que tu peux emprunter pour circuler normalement ?',options:['Oui','Non','Oui si la chaussée est encombrée'],correct:1,explanation:'Ne considère pas l’accotement comme une bande de circulation ordinaire.'},
{type:'scenario',visualId:'M3_POSITION_ONEWAY_01',title:'Sens unique',body:'La signalisation et les véhicules indiquent le sens de circulation.',question:'Quel élément essentiel différencie cette rue de la route à double sens ?',options:['Les véhicules motorisés y circulent dans un seul sens','La priorité de droite n’existe jamais','Toutes les bandes sont toujours utilisables librement'],correct:0,explanation:'Une chaussée à sens unique n’organise pas la circulation comme une chaussée à double sens. Observe toujours la signalisation.'},
{type:'text',title:'Méthode PermisHub',body:'Double sens ou sens unique ? Combien de bandes ? Y a-t-il un obstacle ? Y a-t-il un marquage particulier ? Je garde une position correcte.',callout:'PAR DÉFAUT : PENSE À TENIR TA DROITE. ADAPTE TA POSITION UNIQUEMENT SI LA SITUATION LE JUSTIFIE.'},
{type:'summary',title:'À retenir',items:['En règle générale, tiens ta droite.','Route vide ≠ autorisation de rouler au milieu.','Bande gauche libre ≠ raison d’y rester.','Un obstacle modifie temporairement ta trajectoire.','Après l’obstacle, reprends une position correcte.','Accotement ≠ bande de circulation ordinaire.']}
],quiz:[
{visualId:'M3_POSITION_RIGHT_01',question:'Sur cette route à double sens, où dois-tu normalement rouler ?',options:['À droite','Au milieu','À gauche'],correct:0,explanation:'La règle générale est de tenir sa droite.'},
{visualId:'M3_POSITION_DIVIDED_01',question:'Tu ne dépasses aucun véhicule. Quelle bande dois-tu normalement privilégier ?',options:['Celle de droite','Celle de gauche','Toujours celle qui est la plus vide'],correct:0,explanation:'En règle générale, privilégie la bande de droite.'},
{visualId:'M3_POSITION_DIVIDED_01',question:'Tu roules à la vitesse maximale autorisée. Cela te permet-il de rester inutilement à gauche ?',options:['Oui','Non','Seulement la nuit'],correct:1,explanation:'Rouler à la vitesse maximale ne donne pas automatiquement le droit de rester à gauche.'},
{visualId:'M3_POSITION_OBSTACLE_01',question:'L’obstacle t’oblige à modifier ta trajectoire. Que fais-tu après l’avoir franchi ?',options:['Je reprends une position correcte','Je reste au milieu','Je continue à gauche'],correct:0,explanation:'Après l’obstacle, reprends ta position normale lorsque la situation le permet.'},
{visualId:'M3_POSITION_SHOULDER_01',question:'Peux-tu considérer cet accotement comme une bande normale de circulation ?',options:['Oui','Non','Oui dès que la route est chargée'],correct:1,explanation:'L’accotement n’est pas une bande de circulation ordinaire.'},
{visualId:'M3_POSITION_ONEWAY_01',question:'Quelle caractéristique de cette rue dois-tu identifier avant de choisir ta position ?',options:['Elle est à sens unique','Elle est forcément prioritaire','Elle est forcément limitée à 30 km/h'],correct:0,explanation:'La signalisation indique ici une rue à sens unique.'}
],nextLessonLabel:'Suivant : Bandes de circulation & choix de bande →',resultMessages:{perfect:'Excellent. Tu sais conserver une position correcte sur la chaussée.',good:'Bon travail. Revois les situations qui justifient une modification temporaire de position.',low:'Reprends la règle de base : tiens ta droite, puis adapte ta position seulement si la situation le justifie.'}}
