import type { LearningLesson } from './types'

export const LESSON_15: LearningLesson = {
  id: 'carrefours-complexes',
  moduleId: 'priorities-intersections',
  title: 'Carrefours complexes',
  description: 'Identifier la règle qui organise le carrefour avant de décider qui passe.',
  xp: 25,
  steps: [
    { type: 'text', title: 'Face à un carrefour, dans quel ordre réfléchir ?', body: 'Commence par identifier ce qui organise le carrefour : agent, feux, signalisation de priorité, situation particulière, puis priorité de droite si elle s’applique. Ensuite seulement, détermine qui peut passer.', callout: 'IDENTIFIE LA RÈGLE AVANT DE CHERCHER QUI PASSE.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_RIGHT_03', title: 'Trois véhicules, aucune signalisation', body: 'Ce carrefour ne comporte ni agent, ni feu, ni signalisation de priorité. Plusieurs véhicules doivent être pris en compte.', question: 'Quelle règle faut-il appliquer en premier dans cette situation ?', options: ['La priorité de droite', 'Le véhicule arrivé en premier passe', 'Le véhicule qui continue tout droit passe'], correct: 0, explanation: 'Sans règle supérieure qui organise le carrefour, la priorité de droite est la règle à analyser.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_RIGHT_03', title: 'Même scène, autre question', body: 'Une scène peut servir à plusieurs raisonnements. Cherche d’abord le véhicule pertinent pour la règle identifiée.', question: 'Quel véhicule dois-tu prendre en compte avant de t’engager ?', options: ['Le véhicule venant de droite', 'Seulement le véhicule le plus proche', 'Seulement celui qui va tout droit'], correct: 0, explanation: 'Lorsque la priorité de droite s’applique, tu dois d’abord prendre en compte le véhicule venant de droite.' },
    { type: 'scenario', visualId: 'M2_STOP_TRAFFIC_01', title: 'STOP et autres véhicules', body: 'Le STOP organise d’abord ton approche du carrefour, avant la recherche de l’ordre complet de passage.', question: 'Quelle est ta première obligation avant de déterminer si tu peux t’engager ?', options: ['Marquer l’arrêt', 'Regarder uniquement à droite', 'Passer si personne ne klaxonne'], correct: 0, explanation: 'Le STOP impose d’abord de marquer l’arrêt. Ensuite seulement, observe les autres usagers.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_ROUTE_LEFT_01', title: 'Voie prioritaire qui tourne', body: 'Avant de regarder quelle voiture vient de droite, analyse le panneau additionnel et son tracé.', question: 'Quel élément dois-tu analyser en premier ?', options: ['Le tracé de la voie prioritaire', 'La couleur des véhicules', 'Le véhicule le plus proche'], correct: 0, explanation: 'Le tracé indiqué par la ligne épaisse organise la situation avant la priorité de droite.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_PARKING_01', title: 'Exception cachée', body: 'Une voiture arrive de ta droite, mais son origine doit aussi être observée.', question: 'Est-ce suffisant pour conclure qu’elle est prioritaire ?', options: ['Oui', 'Non', 'Seulement si elle roule plus vite'], correct: 1, explanation: 'Non. Avant d’appliquer la priorité de droite, observe d’où vient réellement le véhicule.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_TRAM_01', title: 'Tram et autres usagers', body: 'Les rails et le tram sont des éléments particuliers de la situation.', question: 'Quel élément doit t’empêcher d’appliquer automatiquement le raisonnement classique de priorité de droite ?', options: ['La présence du tram', 'La couleur de la voiture', 'La largeur de la route'], correct: 0, explanation: 'Un tram demande une analyse spécifique de la situation et des signaux applicables.' },
    { type: 'text', visualId: 'M2_COMPLEX_PRIORITY_ROUTE_01', title: 'Carrefour complexe : voie prioritaire', body: 'Pour une future question d’examen, cette scène doit montrer sans ambiguïté le panneau additionnel, son tracé et les véhicules concernés. Elle reste en attente de validation.', callout: 'PAS D’ORDRE DE PASSAGE SANS GÉOMÉTRIE VALIDÉE' },
    { type: 'text', visualId: 'M2_COMPLEX_STOP_YIELD_01', title: 'Carrefour complexe : STOP et cédez', body: 'Avant de calculer un ordre de passage, lis la signalisation applicable à chaque approche. La scène de référence reste en attente de validation.', callout: 'POUR CHAQUE VÉHICULE : IDENTIFIE SA SIGNALISATION' },
    { type: 'text', title: 'Exercice : trouve la règle avant la réponse', body: 'Pour chaque scène, applique toujours deux temps : identifie d’abord la règle à analyser — priorité de droite, STOP, voie prioritaire, tram ou cédez le passage — puis décide seulement qui doit céder.', callout: 'CARREFOUR = A.F.S.S.D. : Agent · Feux · Signalisation · Situation particulière · Droite' },
    { type: 'summary', title: 'À retenir', items: ['N’applique jamais automatiquement la priorité de droite.', 'Cherche d’abord ce qui organise le carrefour.', 'STOP = arrêt obligatoire avant de poursuivre ton raisonnement.', 'Une voie prioritaire peut changer de direction.', 'Observe l’origine des autres véhicules.', 'Un tram nécessite une attention particulière.', 'Dans un carrefour complexe, identifie d’abord la règle, puis détermine qui passe.'] },
  ],
  quiz: [
    { visualId: 'M2_PRIORITY_RIGHT_03', question: 'En l’absence de feux, agent et panneaux, quelle règle recherches-tu ?', options: ['La priorité de droite', 'L’ordre d’arrivée', 'La direction tout droit'], correct: 0, explanation: 'Sans règle supérieure, la priorité de droite est la règle à analyser.' },
    { visualId: 'M2_PRIORITY_EXCEPTION_DIRTROAD_01', question: 'Quel contrôle évite une erreur face à la voiture située à droite ?', options: ['Observer l’origine de sa voie', 'Observer sa couleur', 'Observer sa vitesse seulement'], correct: 0, explanation: 'Un véhicule qui débouche d’un chemin de terre ne se traite pas comme un véhicule arrivant par une voie ordinaire.' },
    { visualId: 'M2_STOP_TRAFFIC_01', question: 'Quel geste doit précéder l’analyse de la circulation ?', options: ['L’arrêt imposé par le STOP', 'Un appel de phares', 'Un demi-tour'], correct: 0, explanation: 'Le STOP impose un arrêt avant toute décision d’engagement.' },
    { visualId: 'M2_PRIORITY_ROAD_01', question: 'Quelle information organise la priorité dans cette scène ?', options: ['Le panneau de voie prioritaire', 'La présence d’une voiture à droite', 'La largeur de la route'], correct: 0, explanation: 'La signalisation de voie prioritaire organise le carrefour.' },
    { visualId: 'M2_PRIORITY_ROUTE_LEFT_01', question: 'Pourquoi la direction tout droit ne suffit-elle pas ici ?', options: ['La voie prioritaire peut tourner selon le panneau additionnel', 'Les voitures sont trop proches', 'La priorité de droite disparaît toujours'], correct: 0, explanation: 'Le panneau additionnel montre le tracé réel de la voie prioritaire.' },
    { visualId: 'M2_PRIORITY_EXCEPTION_TRAM_01', question: 'Quelle situation particulière dois-tu identifier immédiatement ?', options: ['Le tram et ses rails', 'Le trottoir', 'La météo'], correct: 0, explanation: 'Un tram impose d’analyser sa trajectoire et les signaux applicables.' },
    { visualId: 'M2_COMPLEX_STOP_YIELD_01', question: 'Quelle méthode reste correcte dans un carrefour complexe ?', options: ['Identifier la signalisation de chaque approche avant de décider', 'Se fier au véhicule le plus rapide', 'Chercher seulement la voiture à droite'], correct: 0, explanation: 'La signalisation et les situations particulières doivent être analysées avant l’ordre de passage.' },
  ],
  nextLessonLabel: 'Défi final — Priorités & carrefours →',
  resultMessages: { perfect: 'Excellent. Tu identifies la règle qui organise le carrefour avant de raisonner sur le passage.', good: 'Bon raisonnement. Revois les situations particulières avant de conclure.', low: 'Reprends la méthode : agent, feux, signalisation, situation particulière, puis priorité de droite.' },
}
