import type { LearningLesson } from './types'

export const LESSON_17: LearningLesson = {
  id: 'zones-particulieres-et-vitesse', moduleId: 'speed-road-position', title: 'Zones particulières et vitesse', description: 'Certaines zones imposent une allure particulière et des règles supplémentaires. Apprends à les reconnaître avant d’y entrer.', xp: 20,
  steps: [
    { type:'text', visualId:'M3_ZONE_OVERVIEW_01', title:'Les zones changent ta conduite', body:'Tous les endroits ne fonctionnent pas comme une route ordinaire. Dans certaines zones, tu dois réduire ton allure et adapter ton comportement aux autres usagers.', callout:'PANNEAU → ZONE → ALLURE → USAGERS À PROTÉGER' },
    { type:'scenario', visualId:'M3_ZONE_PEDESTRIAN_01', title:'Zone piétonne', body:'Tu es autorisé à circuler dans cette zone.', question:'À quelle allure dois-tu rouler ?', options:['À l’allure du pas','Maximum 30 km/h','Maximum 50 km/h'], correct:0, explanation:'Dans une zone piétonne, les véhicules autorisés doivent circuler à l’allure du pas. Les piétons y sont prioritaires.' },
    { type:'scenario', visualId:'M3_ZONE_PEDESTRIAN_01', title:'Qui peut entrer ?', body:'Une zone piétonne ne signifie pas que n’importe quelle voiture peut y entrer. L’accès dépend des catégories autorisées et de la signalisation locale.', question:'Le fait de rouler à l’allure du pas signifie-t-il que toutes les voitures peuvent entrer dans une zone piétonne ?', options:['Oui','Non','Oui uniquement le week-end'], correct:1, explanation:'Non. L’accès à une zone piétonne est réglementé. Rouler à l’allure du pas ne donne pas automatiquement le droit d’y entrer.' },
    { type:'scenario', visualId:'M3_ZONE_PLAY_STREET_01', title:'Rue réservée au jeu', body:'Des personnes sont présentes dans la rue.', question:'Tu es autorisé à circuler dans cette rue. Quelle allure dois-tu adopter ?', options:['L’allure du pas','30 km/h','50 km/h'], correct:0, explanation:'Dans une rue réservée au jeu, tu dois circuler à l’allure du pas et redoubler de prudence envers les personnes présentes.' },
    { type:'scenario', visualId:'M3_ZONE_SCHOOL_STREET_01', title:'Rue scolaire', body:'L’accès des véhicules à moteur y est réglementé.', question:'Peux-tu entrer librement dans cette rue simplement parce que tu roules lentement ?', options:['Oui','Non','Oui si aucun enfant ne traverse'], correct:1, explanation:'Non. Réduire ta vitesse ne t’autorise pas, à lui seul, à entrer dans une rue scolaire.' },
    { type:'scenario', visualId:'M3_ZONE_RESIDENTIAL_01', title:'Zone résidentielle ou de rencontre', body:'La rue est un espace partagé.', question:'Quel comportement est essentiel dans cette zone ?', options:['Redoubler de prudence envers les piétons','Klaxonner pour faire partir les piétons','Considérer que les voitures sont toujours prioritaires'], correct:0, explanation:'Les piétons peuvent utiliser la chaussée et ne doivent pas être gênés. Redouble de prudence.' },
    { type:'scenario', visualId:'M3_ZONE_RESIDENTIAL_01', title:'Stationnement', body:'Observe la zone résidentielle.', question:'Peux-tu stationner n’importe où dans cette zone ?', options:['Oui','Non, seulement aux endroits prévus par les marquages ou la signalisation','Oui si je laisse mes feux de détresse'], correct:1, explanation:'Non. Le stationnement est autorisé aux emplacements prévus par les marquages ou la signalisation.' },
    { type:'scenario', visualId:'M3_ZONE_CYCLING_01', title:'Zone cyclable', body:'Un cycliste roule devant ta voiture.', question:'Quelle est la vitesse maximale autorisée dans cette zone ?', options:['20 km/h','30 km/h','50 km/h'], correct:1, explanation:'Dans une zone cyclable, la vitesse maximale est de 30 km/h.' },
    { type:'scenario', visualId:'M3_ZONE_CYCLING_01', title:'Dépasser le cycliste ?', body:'Le cycliste devant toi roule à 20 km/h.', question:'Peux-tu le dépasser avec ta voiture ?', options:['Oui, si je ne dépasse pas 30 km/h','Non','Oui, si je laisse 1 mètre'], correct:1, explanation:'Non. Dans une zone cyclable, les véhicules à moteur ne peuvent pas dépasser les cyclistes ni les speed-pédélecs.' },
    { type:'scenario', visualId:'M3_ZONE_CYCLING_01', title:'Place du cycliste', body:'La zone cyclable organise aussi la place des usagers.', question:'Le cycliste doit-il obligatoirement serrer complètement à droite pour te laisser passer ?', options:['Oui','Non','Oui uniquement en journée'], correct:1, explanation:'Non. Dans une zone cyclable, le cycliste peut utiliser toute la largeur de la chaussée dans les conditions prévues.' },
    { type:'scenario', visualId:'M3_ZONE_SPECIAL_PATH_01', title:'Chemin particulier', body:'Le signal indique les usagers admis sur ce chemin.', question:'Tous les conducteurs peuvent-ils emprunter librement ce chemin ?', options:['Oui','Non','Oui si leur vitesse ne dépasse pas 30 km/h'], correct:1, explanation:'Non. L’accès est réservé aux usagers autorisés par le signal et aux catégories prévues par les règles applicables.' },
    { type:'scenario', visualId:'M3_ZONE_RAISED_DEVICE_01', title:'Dispositif surélevé', body:'Le dispositif est visible sur la chaussée.', question:'Laquelle de ces actions est interdite sur le dispositif surélevé ?', options:['Le franchir','Y stationner','Continuer sa route'], correct:1, explanation:'Le stationnement y est interdit. Les données pédagogiques indiquent aussi l’interdiction de s’y arrêter et, en principe, d’y dépasser sauf exception prévue pour le cycliste.' },
    { type:'compare', title:'Comparer les zones', body:'Une zone ne change pas seulement ta vitesse : elle peut changer ton accès, ton stationnement et ton comportement envers les autres usagers.', items:[{label:'ZONE PIÉTONNE / RUE DE JEU',result:'Allure du pas'},{label:'ZONE CYCLABLE',result:'30 km/h · pas de dépassement'}] },
    { type:'text', title:'Tu vois un panneau de zone ?', body:'Identifie la zone. Vérifie si tu peux y entrer. Adapte ta vitesse ou ton allure. Identifie les usagers prioritaires ou à protéger. Respecte les règles propres à la zone.', callout:'NE REGARDE JAMAIS UNIQUEMENT LA VITESSE. COMMENCE PAR IDENTIFIER LA ZONE.' },
    { type:'summary', title:'À retenir', items:['Zone piétonne → allure du pas.','Rue réservée au jeu → allure du pas.','Zone cyclable → maximum 30 km/h et pas de dépassement des cyclistes ou speed-pédélecs.','Zone résidentielle ou de rencontre → prudence particulière envers les piétons et stationnement aux endroits prévus.','Certaines zones limitent aussi l’accès.'] },
  ],
  quiz:[
    {visualId:'M3_ZONE_PEDESTRIAN_01',question:'Tu es autorisé à entrer ici. À quelle allure dois-tu circuler ?',options:['Allure du pas','30 km/h','50 km/h'],correct:0,explanation:'Dans une zone piétonne, les véhicules autorisés circulent à l’allure du pas.'},
    {visualId:'M3_ZONE_PLAY_STREET_01',question:'Quelle allure dois-tu adopter dans cette rue ?',options:['Allure du pas','30 km/h','50 km/h'],correct:0,explanation:'Une rue réservée au jeu impose l’allure du pas.'},
    {visualId:'M3_ZONE_RESIDENTIAL_01',question:'Où peux-tu stationner dans cette zone ?',options:['Partout le long de la chaussée','Aux endroits prévus par les marquages ou la signalisation','Sur le trottoir si je laisse assez de place'],correct:1,explanation:'Le stationnement est autorisé seulement aux endroits prévus.'},
    {visualId:'M3_ZONE_CYCLING_01',question:'Quelle vitesse maximale est autorisée ici ?',options:['20 km/h','30 km/h','50 km/h'],correct:1,explanation:'La zone cyclable est limitée à 30 km/h.'},
    {visualId:'M3_ZONE_CYCLING_01',question:'Le cycliste roule lentement. Peux-tu le dépasser ?',options:['Oui','Non','Oui si je reste sous 30 km/h'],correct:1,explanation:'Les véhicules à moteur ne peuvent pas dépasser les cyclistes dans une zone cyclable.'},
    {visualId:'M3_ZONE_SPECIAL_PATH_01',question:'Le fait de rouler lentement suffit-il pour avoir le droit d’emprunter ce chemin ?',options:['Oui','Non','Seulement hors agglomération'],correct:1,explanation:'L’accès dépend des usagers autorisés par le signal, pas seulement de la vitesse.'},
  ], nextLessonLabel:'Suivant : Adapter sa vitesse à la situation →', resultMessages:{perfect:'Excellent. Tu reconnais les zones et les règles qui les accompagnent.',good:'Bon travail. Revois les règles propres à chaque zone.',low:'Reprends la méthode : identifie la zone avant de décider de ta vitesse, de ton accès ou de ton stationnement.'}
}
