import type { LearningLesson } from './types'

export const LESSON_16: LearningLesson = {
  id: 'comprendre-les-limitations-de-vitesse',
  moduleId: 'speed-road-position',
  title: 'Comprendre les limitations de vitesse',
  description: 'Apprends à déterminer la vitesse maximale autorisée en observant la route, la signalisation et l’endroit où tu circules.',
  xp: 20,
  steps: [
    { type: 'text', visualId: 'M3_SPEED_OVERVIEW_01', title: 'À combien peux-tu rouler ici ?', body: 'Pour répondre correctement, ne regarde pas seulement la largeur de la route. Observe d’abord la signalisation, puis identifie le type d’endroit et de chaussée où tu circules.', callout: 'UNE LIMITATION INDIQUÉE PAR UN PANNEAU DOIT ÊTRE RESPECTÉE, MÊME SI LA ROUTE SEMBLE PERMETTRE DE ROULER PLUS VITE.' },
    { type: 'scenario', visualId: 'M3_SPEED_SIGN_50_01', title: 'Panneau de limitation', body: 'Le panneau C43 est visible à droite de la route.', question: 'Quelle est la vitesse maximale autorisée après ce panneau ?', options: ['30 km/h', '50 km/h', '70 km/h'], correct: 1, explanation: 'Le panneau impose une vitesse maximale de 50 km/h. La limitation indiquée s’applique à partir du signal.' },
    { type: 'text', visualId: 'M3_SPEED_SIGN_50_01', title: 'Avant ou après le panneau ?', body: 'La limitation prend effet à partir du signal : ce qui se trouve avant le panneau n’est pas encore soumis à cette nouvelle limitation.', callout: 'EN DEÇÀ = AVANT LE PANNEAU · AU-DELÀ = APRÈS LE PANNEAU' },
    { type: 'scenario', visualId: 'M3_SPEED_SIGN_50_01', title: 'Ne pas suivre les autres', body: 'Les autres voitures roulent à 70 km/h dans cette situation.', question: 'Quelle vitesse maximale dois-tu respecter ?', options: ['50 km/h', '70 km/h', 'La même vitesse que les autres voitures'], correct: 0, explanation: 'Le comportement des autres conducteurs ne modifie pas la limitation. Le panneau indique 50 km/h maximum.' },
    { type: 'scenario', visualId: 'M3_SPEED_AGGLO_ENTRY_01', title: 'Agglomération', body: 'Le signal F1a apparaît à l’entrée d’une localité belge.', question: 'Que t’indique ce panneau ?', options: ['Le commencement d’une agglomération', 'Le commencement d’une autoroute', 'Une zone de stationnement'], correct: 0, explanation: 'Ce signal indique le commencement d’une agglomération.' },
    { type: 'scenario', visualId: 'M3_SPEED_AGGLO_EXIT_01', title: 'Sortie d’agglomération', body: 'La route quitte la zone bâtie et le signal de fin est visible.', question: 'Que t’indique ce signal ?', options: ['Je quitte l’agglomération', 'J’entre dans une zone 30', 'J’entre sur une autoroute'], correct: 0, explanation: 'Ce signal indique la fin de l’agglomération. Détermine ensuite la limitation applicable à la route sur laquelle tu circules.' },
    { type: 'text', visualId: 'M3_SPEED_ROAD_TYPES_01', title: 'Comprendre le type de route', body: 'Les trois illustrations montrent successivement une route ordinaire, une route dont les sens sont séparés par une ligne blanche, puis des chaussées séparées par une berme centrale. Ne regarde pas seulement le nombre de bandes.', callout: 'LA MANIÈRE DONT LES DEUX SENS SONT SÉPARÉS PEUT ÊTRE IMPORTANTE.' },
    { type: 'scenario', visualId: 'M3_SPEED_ROAD_TYPES_01', title: 'Ligne blanche ou berme centrale ?', body: 'Observe l’ordre des trois illustrations présentées dans la scène.', question: 'Sur quelle illustration les deux sens de circulation sont-ils séparés par une berme centrale ?', options: ['Illustration 1', 'Illustration 2', 'Illustration 3'], correct: 2, explanation: 'L’illustration 3 montre une berme centrale qui sépare physiquement les deux chaussées. Ne la confonds pas avec une simple ligne blanche.' },
    { type: 'text', visualId: 'M3_SPEED_REGIONS_01', title: 'Les régions', body: 'Les règles générales de vitesse ne sont pas toujours identiques partout en Belgique. Hors agglomération, sur route ordinaire : Wallonie 90 km/h ; Bruxelles et Flandre 70 km/h. En agglomération : Wallonie et Flandre 50 km/h ; Bruxelles 30 km/h.', callout: 'SACHE DANS QUELLE RÉGION TU CIRCULES.' },
    { type: 'scenario', visualId: 'M3_SPEED_MOTORWAY_01', title: 'Autoroute', body: 'Le signal F5 et les chaussées séparées indiquent un type de route précis.', question: 'Quel type de route commences-tu à emprunter ?', options: ['Une route ordinaire', 'Une autoroute', 'Une zone résidentielle'], correct: 1, explanation: 'Le signal F5 indique le commencement d’une autoroute.' },
    { type: 'scenario', visualId: 'M3_SPEED_MOTORWAY_01', title: '120 km/h', body: 'Aucune limitation inférieure n’est indiquée dans cette scène.', question: 'En l’absence d’une limitation inférieure, quelle vitesse maximale la synthèse associe-t-elle à l’autoroute pour une voiture ?', options: ['90 km/h', '100 km/h', '120 km/h'], correct: 2, explanation: 'Pour une voiture, la vitesse maximale indiquée dans la synthèse sur autoroute est de 120 km/h, sauf limitation plus basse applicable.' },
    { type: 'scenario', visualId: 'M3_SPEED_MOTORWAY_90_01', title: 'Autoroute limitée', body: 'Un panneau de limitation est visible sur l’autoroute.', question: 'Tu circules sur autoroute mais ce panneau est présent. Quelle vitesse maximale dois-tu respecter ?', options: ['90 km/h', '120 km/h', '130 km/h'], correct: 0, explanation: 'Le panneau impose ici 90 km/h maximum. Le fait d’être sur autoroute ne permet pas d’ignorer une limitation plus basse signalée.' },
    { type: 'text', title: 'Méthode à retenir', body: 'Y a-t-il un panneau de limitation ? Suis-je en agglomération ou hors agglomération ? Quel est le type de route ? Dans quelle Région suis-je ? Existe-t-il une limitation particulière ?', callout: 'NE CHOISIS JAMAIS UNE VITESSE UNIQUEMENT PARCE QUE LA ROUTE PARAÎT LARGE OU DÉGAGÉE.' },
    { type: 'summary', title: 'À retenir', items: ['Cherche d’abord la signalisation.', 'Identifie si tu entres ou quittes une agglomération.', 'Identifie le type de route.', 'Tiens compte des règles applicables à la Région.', 'Une vitesse maximale autorisée n’est pas forcément une vitesse adaptée aux circonstances.'] },
  ],
  quiz: [
    { visualId: 'M3_SPEED_SIGN_50_01', question: 'Tu viens de dépasser ce panneau. À combien peux-tu rouler au maximum ?', options: ['30 km/h', '50 km/h', '70 km/h'], correct: 1, explanation: 'Le panneau visible fixe la vitesse maximale à 50 km/h.' },
    { visualId: 'M3_SPEED_AGGLO_ENTRY_01', question: 'Quel changement indique la signalisation visible ?', options: ['Entrée dans une agglomération', 'Sortie d’agglomération', 'Entrée sur autoroute'], correct: 0, explanation: 'Le signal F1a indique le commencement d’une agglomération.' },
    { visualId: 'M3_SPEED_AGGLO_EXIT_01', question: 'Quelle information dois-tu comprendre avant de poursuivre ta route ?', options: ['Je quitte l’agglomération', 'Je dois obligatoirement rouler à 120 km/h', 'Je suis dans une zone résidentielle'], correct: 0, explanation: 'Le signal annonce la fin de l’agglomération ; analyse ensuite la route et la signalisation.' },
    { visualId: 'M3_SPEED_ROAD_TYPES_01', question: 'Quelle illustration montre une séparation physique des deux sens de circulation ?', options: ['Illustration 1', 'Illustration 2', 'Illustration 3'], correct: 2, explanation: 'La troisième illustration montre une berme centrale, à la différence d’une simple ligne blanche.' },
    { visualId: 'M3_SPEED_MOTORWAY_90_01', question: 'Tu es sur autoroute. Le panneau visible indique 90 km/h. Quelle est ta vitesse maximale ici ?', options: ['90 km/h', '120 km/h', '130 km/h'], correct: 0, explanation: 'La limitation explicitement signalée à 90 km/h doit être respectée.' },
  ],
  nextLessonLabel: 'Suivant : Zones particulières et vitesse →',
  resultMessages: { perfect: 'Excellent. Tu identifies les éléments qui organisent la vitesse maximale.', good: 'Bon travail. Revois l’ordre : panneau, agglomération, route, Région.', low: 'Reprends la méthode : la signalisation et le type de route doivent être observés avant de choisir une vitesse.' },
}
