import type { LearningLesson } from './types'

export const LESSON_14: LearningLesson = {
  id: 'tram-et-priorite',
  moduleId: 'priorities-intersections',
  title: 'Tram & priorité',
  description: 'Analyser les rails, les signaux et la trajectoire du tram avant de décider.',
  xp: 20,
  steps: [
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_TRAM_01', title: 'Le tram arrive de gauche', body: 'Des rails et un tram sont présents au carrefour. Ne réduis pas la situation à la seule priorité de droite.', question: 'Le tram arrive de ta gauche. Peux-tu passer simplement parce qu’aucun véhicule n’arrive de ta droite ?', options: ['Oui', 'Non', 'Oui, si je continue tout droit'], correct: 1, explanation: 'Non. Le tram ne doit pas être traité comme une voiture ordinaire dans ton raisonnement de priorité.' },
    { type: 'text', visualId: 'M2_PRIORITY_EXCEPTION_TRAM_01', title: 'Le piège', body: 'Tu vérifies ce qui vient de droite pour une voiture. Mais lorsqu’un véhicule sur rails intervient, vérifie spécifiquement sa situation et les règles qui organisent le carrefour.', callout: 'TRAM À GAUCHE ≠ « JE PASSE »' },
    { type: 'scenario', visualId: 'M2_TRAM_RIGHT_01', title: 'Le tram vient de droite', body: 'La présence des rails doit déclencher ton analyse, quelle que soit la direction d’arrivée du tram.', question: 'Le tram vient maintenant de ta droite. Quel élément dois-tu immédiatement prendre en compte ?', options: ['C’est un véhicule sur rails', 'Sa couleur', 'La largeur de ta voiture'], correct: 0, explanation: 'Repère immédiatement le véhicule sur rails et sa trajectoire.' },
    { type: 'text', visualId: 'M2_TRAM_PRIORITY_SIGN_01', title: 'Panneau de priorité et tram', body: 'Un panneau de priorité pour ta route ne suffit pas à résoudre automatiquement une situation avec un tram. Le visuel précis doit être validé avant de l’utiliser pour une décision d’examen.', callout: 'AVEC UN TRAM, ANALYSE LES RÈGLES ET SIGNAUX SPÉCIFIQUES' },
    { type: 'scenario', visualId: 'M2_TRAM_SIGNAL_01', title: 'Tram et feux', body: 'Le carrefour est réglé par des signaux lumineux. La présence du tram ne permet pas de les ignorer.', question: 'Un tram est présent, mais la circulation est réglée par des signaux. Que dois-tu observer avant de décider de passer ?', options: ['Les signaux qui règlent la circulation', 'Seulement la position du tram', 'Seulement la priorité de droite'], correct: 0, explanation: 'Observe d’abord les signaux applicables à la situation.' },
    { type: 'scenario', visualId: 'M2_TRAM_BLOCKING_01', title: 'Ne pas bloquer les rails', body: 'La circulation devant toi est arrêtée et l’espace après le carrefour ne permet pas de dégager les rails.', question: 'Peux-tu t’engager et rester immobilisé sur les rails ?', options: ['Oui', 'Non', 'Oui si le feu est vert'], correct: 1, explanation: 'Ne t’engage pas si tu risques de rester immobilisé sur la voie du tram.' },
    { type: 'compare', title: 'Le bon raisonnement', body: 'La présence d’un tram ne remplace pas l’analyse de la signalisation. La situation complète décide.', items: [{ label: 'SANS SIGNAL RÉGLANT LE PASSAGE', result: 'Analyse les rails et la trajectoire du tram' }, { label: 'AVEC SIGNAUX LUMINEUX', result: 'Observe d’abord les signaux applicables' }] },
    { type: 'text', title: 'La méthode PermisHub', body: 'Identifie les rails. Repère le tram et sa trajectoire. Cherche un agent ou des signaux lumineux. Observe la signalisation. N’applique pas automatiquement le raisonnement d’une voiture ordinaire. Engage-toi seulement lorsque la situation le permet.', callout: 'RAILS → TRAM → SIGNAUX → DÉCISION' },
    { type: 'summary', title: 'À retenir', items: ['Un tram est un véhicule sur rails.', 'Ne lui applique pas automatiquement le raisonnement classique de priorité de droite.', 'Un tram venant de gauche peut remettre en cause « personne à droite = je passe ».', 'Ne conclus pas automatiquement qu’un panneau de priorité te permet de passer devant un tram.', 'Observe les agents, signaux et la configuration réelle avant de décider.'] },
  ],
  quiz: [
    { visualId: 'M2_PRIORITY_EXCEPTION_TRAM_01', question: 'Quelle erreur dois-tu éviter devant le tram arrivant de gauche ?', options: ['Conclure que je passe uniquement parce que ma droite est libre', 'Regarder les rails', 'Observer le carrefour'], correct: 0, explanation: 'Le tram demande un raisonnement spécifique : ta droite libre ne suffit pas à conclure.' },
    { visualId: 'M2_TRAM_RIGHT_01', question: 'Quel élément transforme immédiatement ton analyse de ce carrefour ?', options: ['Le tram sur rails', 'La couleur du tram', 'La largeur du trottoir'], correct: 0, explanation: 'La présence du véhicule sur rails doit être identifiée immédiatement.' },
    { visualId: 'M2_TRAM_PRIORITY_SIGN_01', question: 'Pourquoi faut-il valider précisément une scène avec panneau de priorité et tram ?', options: ['Les signaux et trajectoires doivent être non ambigus', 'Le tram est toujours bleu', 'Les rails ne comptent pas'], correct: 0, explanation: 'Un cas de tram doit être résolu avec les signaux et trajectoires exacts.' },
    { visualId: 'M2_TRAM_SIGNAL_01', question: 'Quel contrôle prime lorsque des signaux lumineux organisent le carrefour ?', options: ['Les signaux applicables', 'Uniquement la priorité de droite', 'Uniquement le tram'], correct: 0, explanation: 'Les signaux règlent la circulation et doivent être observés avant de décider.' },
    { visualId: 'M2_TRAM_BLOCKING_01', question: 'Quel risque dois-tu éviter avant de t’engager sur ce carrefour encombré ?', options: ['Rester immobilisé sur les rails', 'Ralentir', 'Regarder le tram'], correct: 0, explanation: 'N’entre pas si tu ne peux pas dégager les rails.' },
  ],
  nextLessonLabel: 'Suivant : Carrefours complexes →',
  resultMessages: { perfect: 'Excellent. Tu analyses la situation complète avant de décider face à un tram.', good: 'Bien joué. Revois les signaux et la trajectoire du tram.', low: 'Reprends la méthode : rails, tram, signaux, puis décision.' },
}
