import type { LearningLesson } from './types'

export const LESSON_20: LearningLesson = {
  id: 'bandes-de-circulation-et-choix-de-bande',
  moduleId: 'speed-road-position',
  title: 'Bandes de circulation : où dois-tu rouler ?',
  description: 'Plusieurs bandes devant toi ? Apprends à choisir la bonne avant de poursuivre ta route.',
  xp: 20,
  steps: [
    { type: 'scenario', visualId: 'M3_LANES_BASIC_01', title: 'Reconnaître les bandes', body: 'Observe les marquages au sol et la chaussée séparée.', question: 'Combien de bandes de circulation sont disponibles dans ton sens ?', options: ['Une', 'Deux', 'Trois'], correct: 1, explanation: 'Les marquages au sol permettent ici de distinguer deux bandes de circulation dans ton sens.' },
    { type: 'scenario', visualId: 'M3_LANES_BASIC_01', title: 'Quelle bande en situation normale ?', body: 'Tu continues normalement ta route et aucune situation particulière ne justifie un autre placement.', question: 'Quelle bande dois-tu privilégier ?', options: ['La bande de droite', 'La bande de gauche', 'Celle où il y a le moins de voitures'], correct: 0, explanation: 'En règle générale, tiens ta droite. Une bande de gauche libre ne signifie pas que tu dois y rester sans raison.' },
    { type: 'scenario', visualId: 'M3_LANES_BASIC_01', title: 'Le piège de la bande vide', body: 'La bande de gauche est complètement libre.', question: 'Est-ce une raison suffisante pour y rester ?', options: ['Oui', 'Non', 'Oui si je roule à la vitesse maximale'], correct: 1, explanation: 'Le fait qu’une bande soit plus libre ne suffit pas à justifier ton maintien à gauche.' },
    { type: 'scenario', visualId: 'M3_LANES_BUS_01', title: 'Bande réservée aux bus', body: 'La bande visible à droite est réservée aux autobus.', question: 'Peux-tu l’utiliser comme une bande normale avec ta voiture ?', options: ['Oui', 'Non', 'Oui si elle est vide'], correct: 1, explanation: 'Une bande réservée aux autobus n’est pas une bande de circulation ordinaire pour ta voiture.' },
    { type: 'scenario', visualId: 'M3_LANES_BUS_01', title: 'Bande bus vide', body: 'Aucun bus n’est présent.', question: 'Peux-tu utiliser la bande réservée simplement parce qu’elle est vide ?', options: ['Oui', 'Non', 'Oui uniquement pour dépasser'], correct: 1, explanation: 'Le fait qu’une bande réservée soit vide ne la transforme pas en bande ordinaire.' },
    { type: 'scenario', visualId: 'M3_LANES_SSF_01', title: 'Site spécial franchissable', body: 'Observe cet aménagement particulier destiné aux transports en commun.', question: 'Ce site doit-il être confondu avec une bande ordinaire pour voitures ?', options: ['Oui', 'Non', 'Oui lorsqu’aucun bus ou tram n’est présent'], correct: 1, explanation: 'Un site spécial franchissable est un aménagement particulier destiné aux transports en commun et aux usagers éventuellement autorisés.' },
    { type: 'scenario', visualId: 'M3_LANES_DIRECTION_ARROWS_01', title: 'Flèches de sélection', body: 'La bande gauche indique un virage à gauche ; la bande droite indique tout droit.', question: 'Tu veux continuer tout droit. Quelle bande correspond à la direction indiquée ?', options: ['La bande indiquant tout droit', 'La bande indiquant à gauche', 'Les deux, quelle que soit la flèche'], correct: 0, explanation: 'Observe les flèches associées aux bandes. Elles t’indiquent la direction correspondant à la bande concernée.' },
    { type: 'scenario', visualId: 'M3_LANES_DIRECTION_ARROWS_01', title: 'Mauvaise bande', body: 'Tu veux aller tout droit mais tu te places sur une bande dont la flèche indique uniquement une autre direction.', question: 'Ton placement est-il correct ?', options: ['Oui', 'Non', 'Oui si aucun véhicule n’est derrière moi'], correct: 1, explanation: 'Choisis ta bande en tenant compte des indications présentes sur la chaussée. Lis les flèches avant d’arriver au carrefour.' },
    { type: 'scenario', visualId: 'M3_LANES_RED_CROSS_01', title: 'Croix rouge au-dessus d’une bande', body: 'Une croix rouge est allumée au-dessus de la bande de gauche.', question: 'Peux-tu emprunter cette bande ?', options: ['Oui', 'Non', 'Oui si elle est vide'], correct: 1, explanation: 'Une croix rouge au-dessus d’une bande en interdit l’accès.' },
    { type: 'scenario', visualId: 'M3_LANES_RED_CROSS_01', title: 'Indication lumineuse autorisant l’accès', body: 'La croix rouge interdit la bande de gauche ; les flèches vertes autorisent les autres bandes.', question: 'Quelle bande est accessible d’après la signalisation lumineuse ?', options: ['Une bande sous une flèche verte', 'La bande sous la croix rouge', 'Aucune bande'], correct: 0, explanation: 'Les signaux lumineux placés au-dessus des bandes permettent de savoir quelles bandes sont accessibles.' },
    { type: 'scenario', visualId: 'M3_LANES_EVACUATION_01', title: 'Flèche d’évacuation', body: 'Une flèche lumineuse d’évacuation est affichée au-dessus de ta bande.', question: 'Que t’indique cette flèche ?', options: ['Que tu dois quitter cette bande dans la direction indiquée', 'Que tu dois accélérer', 'Que tu peux t’arrêter sur cette bande'], correct: 0, explanation: 'Une flèche d’évacuation t’indique que tu dois quitter la bande dans la direction indiquée.' },
    { type: 'text', title: 'Quelle bande ?', body: '1. Combien de bandes ?  2. Quels marquages ?  3. Quelles flèches ?  4. Bande réservée ?  5. Signal au-dessus de la bande ?  6. Je choisis ma bande.', callout: 'Ne choisis jamais une bande uniquement parce qu’elle semble plus rapide ou plus vide.' },
    { type: 'summary', title: 'À retenir', items: ['En règle générale, tiens ta droite.', 'Une bande vide n’est pas forcément une bande que tu peux emprunter.', 'Bande bus : bande réservée.', 'Observe les flèches associées aux bandes.', 'Croix rouge au-dessus d’une bande : bande interdite.', 'Flèche d’évacuation : quitte la bande dans la direction indiquée.'] },
  ],
  quiz: [
    { visualId: 'M3_LANES_BASIC_01', question: 'Tu poursuis normalement ta route. Quelle bande dois-tu privilégier ?', options: ['Droite', 'Gauche', 'Celle qui est la plus vide'], correct: 0, explanation: 'En règle générale, tiens ta droite.' },
    { visualId: 'M3_LANES_BUS_01', question: 'Cette bande réservée est vide. Peux-tu l’emprunter comme une bande normale ?', options: ['Oui', 'Non', 'Oui si je roule lentement'], correct: 1, explanation: 'Une bande réservée vide reste une bande réservée.' },
    { visualId: 'M3_LANES_DIRECTION_ARROWS_01', question: 'Tu veux continuer tout droit. Quelle bande dois-tu choisir ?', options: ['La bande de droite, marquée tout droit', 'La bande de gauche, marquée à gauche', 'Les deux indifféremment'], correct: 0, explanation: 'Les flèches au sol indiquent ici que la bande de droite permet de continuer tout droit.' },
    { visualId: 'M3_LANES_RED_CROSS_01', question: 'Peux-tu emprunter la bande située sous la croix rouge ?', options: ['Oui', 'Non', 'Seulement si elle est vide'], correct: 1, explanation: 'La croix rouge interdit l’accès à cette bande.' },
    { visualId: 'M3_LANES_EVACUATION_01', question: 'Que dois-tu faire ?', options: ['Quitter la bande dans la direction indiquée', 'T’arrêter sur place', 'Accélérer'], correct: 0, explanation: 'La flèche d’évacuation t’indique de quitter la bande dans sa direction.' },
    { visualId: 'M3_LANES_BUS_01', question: 'Il y a beaucoup de circulation sur ta bande mais la bande bus est vide. Peux-tu l’utiliser pour avancer plus vite ?', options: ['Oui', 'Non', 'Oui pendant quelques mètres'], correct: 1, explanation: 'Une bande réservée ne devient pas utilisable parce qu’elle est vide.' },
    { visualId: 'M3_LANES_DIRECTION_ARROWS_01', question: 'Quel élément dois-tu observer avant de choisir ta bande à l’approche du carrefour ?', options: ['Les flèches de direction', 'La couleur des véhicules', 'La bande la moins fréquentée'], correct: 0, explanation: 'Les flèches associées aux bandes indiquent la direction à suivre.' },
  ],
  nextLessonLabel: 'Suivant : Croisement et situations particulières →',
  resultMessages: { perfect: 'Excellent. Tu sais lire les bandes et leur signalisation.', good: 'Bon travail. Revois les indications de bandes qui t’ont fait hésiter.', low: 'Reprends la méthode : marquages, flèches, bandes réservées et signaux lumineux.' },
}

