import type { LearningLesson } from './types'

export const LESSON_11: LearningLesson = {
  id: 'stop-et-cedez-le-passage',
  moduleId: 'priorities-intersections',
  title: 'STOP & Cédez le passage',
  description: 'Reconnaître les deux signaux, savoir où s’arrêter et décider quand céder.',
  xp: 20,
  steps: [
    { type: 'scenario', visualId: 'M2_YIELD_01', title: 'Cédez le passage', body: 'Le panneau et le marquage indiquent que tu abordes une voie où tu dois céder le passage aux usagers concernés.', question: 'Tu arrives à ce carrefour. Que dois-tu faire ?', options: ['M’arrêter obligatoirement', 'Céder le passage et m’arrêter si nécessaire', 'Passer puisque je viens de droite'], correct: 1, explanation: 'Le cédez le passage n’impose pas un arrêt obligatoire. Tu cèdes et tu t’arrêtes si cela est nécessaire.' },
    { type: 'scenario', visualId: 'M2_YIELD_01', title: 'La voie est libre', body: 'Regarde la même signalisation, mais imagine qu’aucun usager n’arrive sur la voie abordée.', question: 'La voie est complètement libre. Dois-tu obligatoirement marquer un arrêt complet ?', options: ['Oui', 'Non', 'Seulement la nuit'], correct: 1, explanation: 'Contrairement au STOP, le cédez le passage n’impose pas systématiquement un arrêt complet.' },
    { type: 'scenario', visualId: 'M2_STOP_01', title: 'STOP', body: 'Le panneau STOP et la ligne d’arrêt sont visibles. La route transversale est libre.', question: 'La route est complètement libre. Que dois-tu faire ?', options: ['Ralentir puis continuer', 'Marquer l’arrêt', 'Continuer si j’ai une bonne visibilité'], correct: 1, explanation: 'STOP = arrêt obligatoire. Même sans véhicule, tu dois marquer l’arrêt avant de t’engager.' },
    { type: 'scenario', visualId: 'M2_STOP_01', title: 'Où t’arrêter ?', body: 'Repère la ligne blanche transversale avant le carrefour : elle indique la limite à respecter.', question: 'Où dois-tu t’arrêter dans cette scène ?', options: ['Avant la ligne d’arrêt', 'Après la ligne', 'Au milieu du carrefour'], correct: 0, explanation: 'L’arrêt se fait avant la ligne d’arrêt, sans empiéter sur le carrefour.' },
    { type: 'compare', title: 'STOP ou cédez ?', body: 'Les deux signaux imposent de respecter la priorité des conducteurs concernés. La différence essentielle porte sur l’arrêt.', items: [{ label: 'CÉDEZ LE PASSAGE', result: 'CÉDER · arrêt seulement si nécessaire' }, { label: 'STOP', result: 'ARRÊT obligatoire · puis céder' }] },
    { type: 'scenario', visualId: 'M2_STOP_01', title: 'Le piège sans trafic', body: 'Une bonne visibilité et l’absence de trafic ne remplacent jamais l’arrêt imposé par le STOP.', question: 'Peux-tu franchir le STOP au pas sans t’immobiliser ?', options: ['Oui', 'Non', 'Seulement si tu tournes à droite'], correct: 1, explanation: 'Non. Une excellente visibilité ne supprime pas l’obligation de marquer l’arrêt.' },
    { type: 'scenario', visualId: 'M2_YIELD_ADVANCE_01', title: 'Préavis du cédez le passage', body: 'Le signal vu ici annonce la signalisation que tu rencontreras plus loin.', question: 'Ce panneau signifie-t-il que tu dois céder immédiatement à cet endroit ?', options: ['Oui', 'Non, il annonce le cédez le passage situé plus loin', 'Il annonce un STOP'], correct: 1, explanation: 'Il s’agit d’un préavis : le cédez le passage se trouve plus loin.' },
    { type: 'scenario', visualId: 'M2_STOP_ADVANCE_01', title: 'Préavis du STOP', body: 'Le signal t’informe à l’avance de l’arrêt que tu rencontreras sur la route.', question: 'Que t’annonce ce signal ?', options: ['Un STOP à la distance indiquée', 'Un cédez le passage immédiat', 'Une voie prioritaire'], correct: 0, explanation: 'Ce panneau annonce un STOP à venir : prépare ton approche.' },
    { type: 'scenario', visualId: 'M2_STOP_TRAFFIC_01', title: 'Après l’arrêt', body: 'Tu as marqué l’arrêt. Un véhicule circule sur la voie transversale devant toi.', question: 'Après avoir marqué ton arrêt, peux-tu maintenant t’engager ?', options: ['Oui, l’arrêt suffit', 'Non, je dois encore céder au véhicule qui circule', 'Oui, car le véhicule vient de gauche'], correct: 1, explanation: 'Après le STOP, tu dois encore observer et céder le passage avant de t’engager.' },
    { type: 'text', title: 'La méthode PermisHub', body: 'STOP : repère la ligne, marque réellement l’arrêt, observe, cède puis engage-toi lorsque tu peux le faire. Cédez : ralentis, observe, détermine à qui céder, arrête-toi si nécessaire puis engage-toi.', callout: 'STOP : ARRÊT OBLIGATOIRE · CÉDEZ : ARRÊT SI NÉCESSAIRE' },
    { type: 'summary', title: 'À retenir', items: ['STOP = arrêt obligatoire.', 'Cédez = arrêt seulement si nécessaire.', 'Après le STOP, tu dois encore vérifier la priorité.', 'Un panneau peut annoncer un STOP ou un cédez situé plus loin.', 'Regarde toujours la situation avant de t’engager.'] },
  ],
  quiz: [
    { visualId: 'M2_YIELD_01', question: 'Quelle différence essentielle distingue le cédez le passage du STOP ?', options: ['Le cédez n’impose l’arrêt que si nécessaire', 'Le cédez donne toujours priorité', 'Le STOP ne concerne que les virages'], correct: 0, explanation: 'Au cédez, tu ralentis et tu t’arrêtes seulement si la situation l’exige.' },
    { visualId: 'M2_STOP_01', question: 'Quel geste reste obligatoire même si la voie transversale est vide ?', options: ['Marquer l’arrêt', 'Klaxonner', 'Attendre un autre véhicule'], correct: 0, explanation: 'Le STOP impose l’arrêt même lorsqu’aucun usager n’arrive.' },
    { visualId: 'M2_YIELD_01', question: 'Si aucune circulation ne t’oblige à céder dans cette scène, quelle action n’est pas imposée ?', options: ['Un arrêt complet systématique', 'L’observation', 'Le ralentissement'], correct: 0, explanation: 'Le cédez demande de pouvoir céder, pas de s’immobiliser systématiquement.' },
    { visualId: 'M2_STOP_ADVANCE_01', question: 'Pourquoi ce signal est-il placé avant le carrefour ?', options: ['Pour annoncer un STOP plus loin', 'Pour t’autoriser à accélérer', 'Pour indiquer une voie prioritaire'], correct: 0, explanation: 'C’est un préavis qui te prépare au STOP à venir.' },
    { visualId: 'M2_STOP_TRAFFIC_01', question: 'Après l’arrêt, quel élément décide encore de ton engagement ?', options: ['La circulation transversale à laquelle tu dois céder', 'La couleur du panneau', 'La proximité du carrefour'], correct: 0, explanation: 'Le STOP n’autorise pas à s’engager : tu dois encore céder si nécessaire.' },
  ],
  nextLessonLabel: 'Suivant : La voie prioritaire →',
  resultMessages: { perfect: 'Excellent. Tu distingues clairement arrêt obligatoire et arrêt nécessaire.', good: 'Bon travail. Revois surtout ce qui se passe après un STOP.', low: 'Reprends les deux méthodes : STOP, arrêt puis observation ; cédez, observation puis arrêt seulement si nécessaire.' },
}
