import type { LearningLesson } from './types'

export const LESSON_12: LearningLesson = {
  id: 'la-voie-prioritaire',
  moduleId: 'priorities-intersections',
  title: 'La voie prioritaire',
  description: 'Reconnaître une voie prioritaire et suivre son tracé aux carrefours.',
  xp: 20,
  steps: [
    { type: 'scenario', visualId: 'M2_PRIORITY_ROAD_01', title: 'Entrée sur une voie prioritaire', body: 'Le panneau jaune en losange indique le régime de priorité de la voie sur laquelle tu circules.', question: 'Que t’indique ce panneau ?', options: ['J’ai priorité uniquement au prochain carrefour', 'Je circule sur une voie prioritaire', 'La priorité de droite s’applique au prochain carrefour'], correct: 1, explanation: 'Tu circules sur une voie prioritaire. Ce régime continue aux carrefours suivants jusqu’à ce qu’une signalisation indique sa fin.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_ROAD_01', title: 'Au carrefour', body: 'Une voiture peut arriver de ta droite. Observe d’abord la signalisation qui organise déjà le carrefour.', question: 'Une voiture arrive de ta droite. Dois-tu automatiquement appliquer la priorité de droite ?', options: ['Oui', 'Non', 'Seulement si elle tourne à droite'], correct: 1, explanation: 'Non. Tu circules sur une voie prioritaire : la présence d’une voiture à droite ne signifie pas automatiquement que tu dois lui céder le passage.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_ROAD_END_01', title: 'Fin de voie prioritaire', body: 'Le panneau indique que le régime de voie prioritaire se termine avant la situation à venir.', question: 'Que signifie ce panneau ?', options: ['La route est interdite', 'Ma voie prioritaire prend fin', 'Je dois obligatoirement céder immédiatement'], correct: 1, explanation: 'Le panneau indique la fin de la voie prioritaire. Observe ensuite la signalisation et la configuration du prochain carrefour.' },
    { type: 'text', visualId: 'M2_PRIORITY_ROAD_END_01', title: 'Piège d’examen', body: 'Fin de voie prioritaire ne signifie pas « je dois forcément céder à tout le monde ». Le régime de voie prioritaire prend fin ; la règle applicable au carrefour reste à identifier.', callout: 'FIN DE VOIE PRIORITAIRE ≠ CÉDER À TOUT LE MONDE' },
    { type: 'text', visualId: 'M2_PRIORITY_ROUTE_LEFT_01', title: 'Lire le panneau additionnel', body: 'Lorsqu’un panneau additionnel décrit le carrefour, la ligne épaisse représente le tracé de la voie prioritaire. Vérifie toujours le panneau exact avant de décider.', callout: 'LIGNE ÉPAISSE = TRACÉ DE LA VOIE PRIORITAIRE' },
    { type: 'scenario', visualId: 'M2_PRIORITY_ROUTE_LEFT_01', title: 'La voie prioritaire tourne', body: 'La branche située tout droit ne correspond pas forcément au tracé prioritaire. La lecture du panneau additionnel décide.', question: 'Pour comprendre la priorité, que dois-tu suivre ?', options: ['Toujours la route qui continue tout droit', 'Le tracé indiqué comme voie prioritaire', 'Toujours le véhicule venant de droite'], correct: 1, explanation: 'Ne confonds pas aller tout droit et rester sur la voie prioritaire : suis le tracé indiqué.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_ROUTE_RIGHT_01', title: 'Autre tracé', body: 'Une voie prioritaire peut aussi changer de direction vers la droite. Le panneau additionnel reste la référence à lire.', question: 'Quelle branche suit la voie prioritaire ?', options: ['Celle montrée par la ligne épaisse', 'Toujours celle qui va tout droit', 'La branche la plus large'], correct: 0, explanation: 'La ligne épaisse du panneau additionnel représente le tracé de la voie prioritaire.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_ROUTE_MULTI_01', title: 'Plusieurs véhicules', body: 'Avant de déterminer un ordre de passage, commence par repérer les véhicules qui suivent le même tracé prioritaire.', question: 'Quelle information dois-tu identifier en premier ?', options: ['Les véhicules qui circulent sur la voie prioritaire', 'Le véhicule le plus proche', 'La couleur des voitures'], correct: 0, explanation: 'Le tracé de la voie prioritaire permet d’identifier les véhicules concernés avant de raisonner sur le passage.' },
    { type: 'text', title: 'La méthode PermisHub', body: 'Identifie le panneau de priorité. Cherche un éventuel panneau additionnel. Observe la ligne épaisse, suis mentalement son tracé dans le carrefour, puis identifie les véhicules qui circulent sur cette voie.', callout: 'SUIVRE LA LIGNE ÉPAISSE AVANT DE DÉCIDER' },
    { type: 'summary', title: 'À retenir', items: ['Le panneau B9 indique une voie prioritaire.', 'Cette priorité continue jusqu’à la fin du régime.', 'B11 indique la fin de la voie prioritaire.', 'Un panneau additionnel peut montrer le tracé.', 'La ligne épaisse représente ce tracé.', 'Aller tout droit ne signifie pas forcément suivre la voie prioritaire.'] },
  ],
  quiz: [
    { visualId: 'M2_PRIORITY_ROAD_01', question: 'Quel régime de circulation est annoncé par le panneau visible ?', options: ['Une voie prioritaire', 'Une interdiction de circuler', 'Un cédez le passage'], correct: 0, explanation: 'Le panneau B9 indique que tu circules sur une voie prioritaire.' },
    { visualId: 'M2_PRIORITY_ROAD_END_01', question: 'Après ce panneau, quelle erreur dois-tu éviter ?', options: ['Penser que la priorité de droite s’applique automatiquement partout', 'Observer le carrefour', 'Chercher la signalisation suivante'], correct: 0, explanation: 'La fin du régime prioritaire ne suffit pas à elle seule pour résoudre toutes les priorités du carrefour suivant.' },
    { visualId: 'M2_PRIORITY_ROUTE_LEFT_01', question: 'Sur un panneau additionnel de priorité, que représente la ligne épaisse ?', options: ['Le tracé de la voie prioritaire', 'Toutes les voies possibles', 'La voie réservée aux bus'], correct: 0, explanation: 'La ligne épaisse permet de suivre le véritable tracé de la voie prioritaire.' },
    { visualId: 'M2_PRIORITY_ROUTE_RIGHT_01', question: 'Quelle affirmation est correcte lorsqu’une voie prioritaire tourne ?', options: ['Je suis le tracé indiqué, même s’il change de direction', 'Je reste prioritaire seulement si je vais tout droit', 'Je regarde seulement à droite'], correct: 0, explanation: 'C’est le panneau additionnel qui montre le tracé à suivre.' },
    { visualId: 'M2_PRIORITY_ROUTE_MULTI_01', question: 'Quel est le premier contrôle utile dans cette situation avec plusieurs véhicules ?', options: ['Identifier la voie prioritaire et les véhicules qui la suivent', 'Démarrer rapidement', 'Appliquer la priorité de droite sans lire les panneaux'], correct: 0, explanation: 'Commence par la signalisation et le tracé prioritaire, puis seulement détermine les priorités.' },
  ],
  nextLessonLabel: 'Suivant : Les autres panneaux de priorité →',
  resultMessages: { perfect: 'Excellent. Tu lis la voie prioritaire au-delà de la direction apparente de la route.', good: 'Bien joué. Revois surtout la lecture du panneau additionnel.', low: 'Reprends la méthode : panneau, panneau additionnel, ligne épaisse, puis véhicules concernés.' },
}
