import type { LearningLesson } from './types'

export const LESSON_21: LearningLesson = {
  id: 'croisement-et-situations-particulieres',
  moduleId: 'speed-road-position',
  title: 'Croiser un autre usager en sécurité',
  description: 'Route étroite, obstacle, véhicule en face : lis la situation avant de passer.',
  xp: 20,
  steps: [
    { type: 'scenario', visualId: 'M3_CROSSING_BASIC_01', title: 'Croiser ≠ dépasser', body: 'Deux véhicules se présentent face à face sur une route à double sens.', question: 'Que se passe-t-il dans cette situation ?', options: ['Je croise un véhicule venant en sens inverse', 'Je dépasse le véhicule', 'Je stationne'], correct: 0, explanation: 'Il s’agit d’un croisement : les deux véhicules circulent en sens opposés et passent l’un à côté de l’autre.' },
    { type: 'scenario', visualId: 'M3_CROSSING_BASIC_01', title: 'Croisement par la droite', body: 'Le sens de circulation est clairement séparé par la ligne centrale.', question: 'De quel côté dois-tu normalement croiser ce véhicule venant en sens inverse ?', options: ['Par la droite', 'Par la gauche', 'Peu importe'], correct: 0, explanation: 'Le croisement s’effectue par la droite. Chaque conducteur reste correctement positionné de son côté de la chaussée.' },
    { type: 'scenario', visualId: 'M3_CROSSING_DISTANCE_01', title: 'Distance latérale', body: 'La route est relativement étroite, mais l’espace entre les véhicules reste visible.', question: 'Lorsque tu croises ce véhicule, que dois-tu préserver ?', options: ['Une distance latérale suffisante', 'Une distance minimale de 10 mètres', 'Aucun espace si tu roules lentement'], correct: 0, explanation: 'Lors du croisement, tu dois laisser une distance latérale suffisante.' },
    { type: 'scenario', visualId: 'M3_POSITION_NARROW_01', title: 'Route étroite', body: 'La chaussée est étroite et un véhicule arrive en face.', question: 'Quelle attitude est correcte ?', options: ['Réduire mon allure et préparer le croisement', 'Accélérer pour passer avant lui', 'Rouler volontairement au milieu'], correct: 0, explanation: 'Sur une chaussée étroite, anticipe le croisement. Adapte ton allure et conserve une position qui permet un passage en sécurité.' },
    { type: 'scenario', visualId: 'M3_POSITION_NARROW_01', title: 'Ne pas forcer', body: 'L’espace devient insuffisant pour vous croiser normalement.', question: 'Quelle attitude est la plus sûre ?', options: ['Ralentir et éviter de forcer le passage', 'Accélérer', 'Continuer au milieu'], correct: 0, explanation: 'Si l’espace disponible devient insuffisant, ne force pas le passage. Observe la situation et adapte ton comportement.' },
    { type: 'scenario', visualId: 'M3_CROSSING_OBSTACLE_OWN_01', title: 'Obstacle de ton côté', body: 'Des véhicules stationnés bloquent ton côté de la chaussée et un véhicule arrive en face.', question: 'Que dois-tu faire ?', options: ['Attendre si nécessaire avant de contourner l’obstacle', 'Forcer le passage', 'Obliger le véhicule en face à monter sur l’accotement'], correct: 0, explanation: 'L’obstacle t’oblige à modifier ta trajectoire. Tu ne dois pas forcer le passage si un véhicule arrive en sens inverse.' },
    { type: 'scenario', visualId: 'M3_CROSSING_OBSTACLE_OTHER_01', title: 'Obstacle du côté opposé', body: 'Observe la position des véhicules stationnés avant de décider.', question: 'Cette fois, de quel côté se trouve l’obstacle ?', options: ['Du côté du véhicule venant en face', 'De mon côté', 'Au milieu du carrefour'], correct: 0, explanation: 'L’obstacle se trouve ici du côté du véhicule venant en sens inverse. Commence toujours par identifier de quel côté se trouve l’obstacle.' },
    { type: 'text', title: 'Méthode obstacle', body: '1. Où est l’obstacle ?  2. Qui doit modifier sa trajectoire ?  3. Y a-t-il assez de place ?  4. Y a-t-il un panneau de priorité ?  5. Je passe sans forcer la situation.', callout: 'Ne mémorise pas uniquement « voiture à gauche » ou « voiture à droite ». Regarde d’abord la route.' },
    { type: 'scenario', visualId: 'M2_NARROW_YIELD_01', title: 'Passage étroit B19', body: 'Ce panneau est placé de ton côté à l’entrée du passage étroit.', question: 'Que dois-tu faire par rapport aux véhicules venant en sens inverse ?', options: ['Leur céder le passage', 'Passer toujours en premier', 'Accélérer avant eux'], correct: 0, explanation: 'Ce signal t’impose de céder le passage aux conducteurs venant en sens inverse.' },
    { type: 'scenario', visualId: 'M2_NARROW_PRIORITY_01', title: 'Passage étroit B21', body: 'Ce panneau règle le passage étroit dans ton sens.', question: 'Que t’indique ce panneau ?', options: ['Tu as la priorité sur les véhicules venant en sens inverse', 'Tu dois toujours faire demi-tour', 'Tu dois céder à tous les véhicules en face'], correct: 0, explanation: 'Ce signal indique que tu as la priorité sur les conducteurs venant en sens inverse.' },
    { type: 'scenario', visualId: 'M2_PRIORITY_EXCEPTION_TRAM_01', title: 'Véhicule sur rails', body: 'Un tram et ses rails constituent une situation particulière.', question: 'Le véhicule que tu rencontres ici doit-il être analysé exactement comme une voiture ordinaire ?', options: ['Oui', 'Non', 'Seulement s’il est vide'], correct: 1, explanation: 'Un véhicule sur rails constitue une situation particulière. Observe sa position, ses rails et la configuration de la route.' },
    { type: 'summary', title: 'À retenir', items: ['Croisement : véhicules en sens opposés.', 'Le croisement s’effectue par la droite.', 'Conserve une distance latérale suffisante.', 'Route étroite : anticipe et adapte ton allure.', 'Obstacle : identifie d’abord de quel côté il se trouve.', 'Ne force jamais un passage insuffisant.', 'B19 : tu cèdes au sens inverse.', 'B21 : priorité sur le sens inverse.', 'Véhicule sur rails : situation particulière.'] },
  ],
  quiz: [
    { visualId: 'M3_CROSSING_BASIC_01', question: 'Que fais-tu avec le véhicule qui arrive en sens inverse ?', options: ['Je le croise', 'Je le dépasse', 'Je le suis'], correct: 0, explanation: 'Des véhicules en sens opposés se croisent.' },
    { visualId: 'M3_CROSSING_DISTANCE_01', question: 'Lors du croisement, que dois-tu conserver ?', options: ['Une distance latérale suffisante', 'Exactement 50 cm', 'Aucun espace particulier'], correct: 0, explanation: 'Il faut conserver une distance latérale suffisante.' },
    { visualId: 'M3_CROSSING_OBSTACLE_OWN_01', question: 'De quel côté se trouve l’obstacle ?', options: ['De mon côté', 'Du côté opposé', 'Au milieu de la chaussée'], correct: 0, explanation: 'Les véhicules stationnés bloquent le côté du candidat.' },
    { visualId: 'M3_CROSSING_OBSTACLE_OWN_01', question: 'Un véhicule arrive en face. Quelle attitude est correcte ?', options: ['Attendre si nécessaire avant de contourner l’obstacle', 'Forcer le passage', 'Accélérer vers l’obstacle'], correct: 0, explanation: 'N’avance pas si le contournement t’oblige à forcer le véhicule venant en face.' },
    { visualId: 'M2_NARROW_YIELD_01', question: 'Que t’impose ce panneau ?', options: ['Céder au véhicule venant en sens inverse', 'Passer obligatoirement en premier', 'Faire demi-tour'], correct: 0, explanation: 'B19 impose de céder au sens inverse.' },
    { visualId: 'M2_NARROW_PRIORITY_01', question: 'Quelle règle s’applique ici ?', options: ['J’ai la priorité sur le véhicule venant en sens inverse', 'Je dois toujours céder', 'Le passage est interdit'], correct: 0, explanation: 'B21 indique la priorité sur le sens inverse.' },
    { visualId: 'M3_POSITION_NARROW_01', question: 'La route est étroite et un véhicule arrive en sens inverse. Quelle est la meilleure première réaction ?', options: ['Observer, réduire mon allure et préparer le croisement', 'Accélérer', 'Me placer au milieu'], correct: 0, explanation: 'Sur une route étroite, anticipe et adapte ton allure.' },
  ],
  nextLessonLabel: 'Suivant : Situations complexes — vitesse + position →',
  resultMessages: { perfect: 'Excellent. Tu analyses l’espace, les obstacles et la signalisation avant de croiser.', good: 'Bon travail. Revois les situations étroites et les panneaux B19/B21.', low: 'Reprends la méthode : espace disponible, obstacle, signalisation, puis passage sans forcer.' },
}
