import type { LearningLesson } from './types'
export const LESSON_27: LearningLesson = { id:'depasser-cyclistes-et-autres-usagers',moduleId:'manoeuvres-overtaking',title:'Dépasser les cyclistes et autres usagers',description:'Adapter son dépassement aux usagers vulnérables, à l’espace et au lieu.',xp:25,steps:[
{type:'text',visualId:'M4_VULNERABLE_OVERVIEW_01',title:'Plus vulnérable = plus d’espace',body:'Dépasser un cycliste, un cyclomotoriste ou un piéton demande une distance latérale minimale. Elle dépend notamment de l’endroit où tu circules.',callout:'OBSERVE L’USAGER, LE LIEU ET L’ESPACE.'},
{type:'text',visualId:'M4_LATERAL_DISTANCE_COMPARE_01',title:'Les deux distances',body:'En agglomération, laisse au moins 1 m. Hors agglomération, laisse au moins 1,5 m. Cette règle concerne ici cycliste, cyclomotoriste et piéton.',callout:'AGGLOMÉRATION : 1 M · HORS AGGLOMÉRATION : 1,5 M'},
{type:'scenario',visualId:'M4_CYCLIST_URBAN_01',title:'En agglomération',body:'La scène est clairement située en agglomération. La distance affichée avec le cycliste est de 1 m.',question:'La distance minimale est-elle respectée ?',options:['Oui, puisqu’elle circule en agglomération','Non, il faut toujours 1,5 m','Non, dépasser un cycliste y est interdit'],correct:0,explanation:'En agglomération, la distance latérale minimale avec un cycliste est de 1 m.'},
{type:'scenario',visualId:'M4_CYCLIST_OUTSIDE_01',title:'Même distance, autre lieu',body:'La voiture est hors agglomération et la distance affichée avec le cycliste est de 1 m.',question:'Quel est le problème ?',options:['Aucun : 1 m suffit partout','Hors agglomération, le minimum est de 1,5 m','Hors agglomération, le dépassement est toujours interdit'],correct:1,explanation:'Hors agglomération, il faut laisser au moins 1,5 m de distance latérale.'},
{type:'scenario',visualId:'M4_CYCLIST_NARROW_ROAD_01',title:'Pas assez de place',body:'La route est étroite, un véhicule arrive en face et le dépassement ne peut pas respecter la distance sans danger.',question:'La voiture rouge peut-elle dépasser immédiatement ?',options:['Oui, un cycliste peut être dépassé même avec peu d’espace','Non, elle attend une situation où la distance est possible sans danger','Oui, si elle ralentit fortement'],correct:1,explanation:'Si la distance minimale ne peut pas être respectée sans mettre les autres en danger, le conducteur attend.'},
{type:'scenario',visualId:'M4_CYCLIST_CYCLEPATH_01',title:'Cycliste sur piste cyclable',body:'La scène est hors agglomération. Le cycliste circule sur une piste cyclable parallèle et la distance affichée est de 1 m.',question:'La voiture peut-elle passer à seulement 1 m ?',options:['Oui, car le cycliste n’est pas sur la chaussée','Non, hors agglomération la distance reste de 1,5 m','Oui, s’il reste entièrement sur sa piste'],correct:1,explanation:'La distance latérale s’applique aussi lorsqu’un cycliste circule sur une piste cyclable. Hors agglomération, elle est d’au moins 1,5 m.'},
{type:'scenario',visualId:'M4_PEDESTRIAN_OVERTAKE_01',title:'Piéton sur la chaussée',body:'Un piéton circule sur la chaussée hors agglomération.',question:'Le conducteur doit-il aussi prévoir une distance latérale minimale ?',options:['Oui, au moins 1,5 m ici','Non, cette règle concerne seulement les cyclistes','Non, il suffit de ralentir'],correct:0,explanation:'Les distances de 1 m en agglomération et 1,5 m hors agglomération concernent aussi un piéton circulant sur la chaussée.'},
{type:'scenario',visualId:'M4_MOPED_OVERTAKE_01',title:'Cyclomotoriste',body:'En agglomération, la distance affichée avec le cyclomotoriste est de 0,7 m.',question:'Quel élément rend ce dépassement incorrect ?',options:['Le cyclomotoriste doit laisser passer la voiture','La distance latérale est inférieure au minimum requis','Une voiture ne peut jamais dépasser un cyclomoteur'],correct:1,explanation:'En agglomération, il faut laisser au moins 1 m avec le cyclomotoriste. 0,7 m est insuffisant.'},
{type:'scenario',visualId:'M4_CYCLING_ZONE_01',title:'Zone cyclable',body:'Le panneau F111 indique une zone cyclable. La voiture a assez d’espace pour laisser 1 m.',question:'Peut-elle dépasser le cycliste ?',options:['Oui, puisque 1 m est disponible','Non, le dépassement du cycliste y est interdit','Oui, si elle reste sous 30 km/h'],correct:1,explanation:'Dans une zone cyclable, un véhicule à moteur ne peut pas dépasser les cyclistes ou speed-pédélecs. La distance ne suffit donc pas.'},
{type:'scenario',visualId:'M4_RAISED_DEVICE_CYCLIST_01',title:'Dispositif surélevé',body:'Un cycliste se trouve devant la voiture sur le dispositif surélevé.',question:'Le dispositif interdit-il ici, à lui seul, de dépasser le cycliste ?',options:['Oui, aucun usager ne peut y être dépassé','Non, l’exception concernant le cycliste doit être prise en compte','Oui, même avec la distance nécessaire'],correct:1,explanation:'L’interdiction sur un dispositif surélevé ne s’applique pas de la même manière au dépassement d’un cycliste. Les autres règles de sécurité restent applicables.'},
{type:'scenario',visualId:'M4_CYCLEPATH_VS_CYCLINGZONE_01',title:'Piste cyclable ou zone cyclable ?',body:'Une piste cyclable et une zone cyclable sont deux notions différentes.',question:'Dans quelle situation le conducteur ne peut-il pas dépasser le cycliste même avec la distance ?',options:['Uniquement sur la piste cyclable','Dans la zone cyclable','Dans les deux situations, toujours'],correct:1,explanation:'Dans une zone cyclable, les véhicules à moteur ne peuvent pas dépasser les cyclistes ou speed-pédélecs.'},
{type:'scenario',visualId:'M4_CYCLIST_COMPLEX_01',title:'Une règle respectée ne suffit pas',body:'La voiture peut laisser 1,5 m avec le cycliste, mais un véhicule arrive en sens inverse.',question:'Peut-elle commencer son dépassement ?',options:['Oui, car la distance réglementaire est respectée','Non, elle doit aussi tenir compte du véhicule venant en sens inverse','Oui, le véhicule opposé doit ralentir'],correct:1,explanation:'Respecter la distance n’est qu’une condition. Le dépassement ne peut pas mettre en danger un véhicule venant en sens inverse.'},
{type:'summary',title:'Méthode PermisHub',items:['Qui est devant moi ?','Suis-je en ou hors agglomération ?','1 m ou 1,5 m ?','Ai-je réellement cet espace ?','Suis-je dans une zone particulière ?','Est-ce sûr pour les autres usagers ?']}
],quiz:[
{visualId:'M4_CYCLIST_URBAN_01',question:'1 m est affiché en agglomération. Quelle décision ?',options:['Distance minimale respectée','Il faut toujours 1,5 m','Dépassement interdit'],correct:0,explanation:'En agglomération, le minimum est de 1 m.'},
{visualId:'M4_CYCLIST_OUTSIDE_01',question:'1 m est affiché hors agglomération. Quelle affirmation est correcte ?',options:['La distance est suffisante','Le minimum est de 1,5 m','Le cycliste doit quitter la chaussée'],correct:1,explanation:'Hors agglomération, le minimum est de 1,5 m.'},
{visualId:'M4_CYCLIST_NARROW_ROAD_01',question:'Pourquoi attendre ici ?',options:['La distance ne peut pas être respectée sans danger','Le cycliste roule trop lentement','Il faut toujours attendre derrière un cycliste'],correct:0,explanation:'La distance et la sécurité de la circulation opposée doivent être respectées.'},
{visualId:'M4_CYCLIST_CYCLEPATH_01',question:'Que change la piste cyclable hors agglomération ?',options:['La distance de 1,5 m reste applicable','Toute distance devient possible','Le dépassement est toujours interdit'],correct:0,explanation:'La distance reste applicable sur une piste cyclable parallèle.'},
{visualId:'M4_PEDESTRIAN_OVERTAKE_01',question:'Quelle distance faut-il prévoir avec le piéton hors agglomération ?',options:['Au moins 1,5 m','Aucune distance particulière','0,7 m'],correct:0,explanation:'Le piéton sur la chaussée est aussi concerné.'},
{visualId:'M4_CYCLING_ZONE_01',question:'La distance est suffisante dans une zone cyclable. Peut-on dépasser ?',options:['Oui','Non, le dépassement du cycliste y est interdit','Oui, sous 30 km/h'],correct:1,explanation:'La règle de zone cyclable s’ajoute à la règle de distance.'},
{visualId:'M4_CYCLEPATH_VS_CYCLINGZONE_01',question:'Quelle notion interdit le dépassement du cycliste ?',options:['La piste cyclable seule','La zone cyclable','Les deux toujours'],correct:1,explanation:'Piste cyclable et zone cyclable ne sont pas la même chose.'},
{visualId:'M4_CYCLIST_FINAL_ANALYSIS_01',question:'Les 1,5 m sont disponibles, mais un véhicule opposé est proche. Quelle affirmation est correcte ?',options:['Le dépassement est autorisé','Le conducteur doit attendre','Le cycliste doit s’écarter'],correct:1,explanation:'La distance avec le cycliste ne permet jamais de mettre en danger la circulation opposée.'}
],nextLessonLabel:'Suivant : Tram et véhicules sur rails →',resultMessages:{perfect:'Excellent. Tu combines distance, lieu, usager et sécurité.',good:'Bon travail. Revois les situations où une distance correcte ne suffit pas.',low:'Reprends la méthode : lieu, usager, distance, espace et autres dangers.'}}
