import type { LearningLesson } from './types'
export const LESSON_24: LearningLesson = { id:'depasser-en-toute-securite',moduleId:'manoeuvres-overtaking',title:'Dépasser en toute sécurité',description:'Avant de dépasser, analyse la circulation, l’espace et la manœuvre complète.',xp:20,steps:[
{type:'text',visualId:'M4_SAFE_OVERTAKE_OVERVIEW_01',title:'Avant de dépasser, analyse toute la situation',body:'Un véhicule lent devant toi ne signifie pas que tu peux immédiatement le dépasser. Vérifie la circulation devant, derrière et l’espace disponible pour terminer en sécurité.',callout:'ANALYSE D’ABORD. DÉPASSE ENSUITE.'},
{type:'scenario',visualId:'M4_OVERTAKE_ONCOMING_01',title:'Regarder devant',body:'La voiture bleue roule lentement, mais un véhicule arrive en sens inverse.',question:'Quel élément empêche surtout la voiture rouge de commencer son dépassement ?',options:['La présence du véhicule venant en sens inverse','Le fait que la voiture bleue roule sous la vitesse maximale','Le fait que la route comporte deux sens de circulation'],correct:0,explanation:'Avant de dépasser, le conducteur doit vérifier qu’aucun véhicule venant en sens inverse ne sera mis en danger. Un véhicule lent ne suffit jamais pour commencer un dépassement.'},
{type:'scenario',visualId:'M4_OVERTAKE_REAR_CHECK_01',title:'Regarder aussi derrière',body:'La route devant la voiture rouge est libre, mais le véhicule gris derrière a déjà commencé à se déporter.',question:'La voiture rouge peut-elle commencer son dépassement ?',options:['Oui, car aucun véhicule n’arrive en sens inverse','Non, car le véhicule derrière a déjà commencé à dépasser','Oui, si elle accélère avant le véhicule gris'],correct:1,explanation:'Regarder devant ne suffit pas. Avant de se déplacer vers la gauche, le conducteur doit vérifier qu’un véhicule derrière lui n’a pas déjà commencé son dépassement.'},
{type:'scenario',visualId:'M4_OVERTAKE_RETURN_SPACE_01',title:'Penser au rabattement',body:'La voiture rouge doit aussi penser à la fin de sa manœuvre avant de la commencer.',question:'Quel problème doit-elle anticiper avant de commencer son dépassement ?',options:['Elle risque de ne pas disposer d’un espace suffisant pour se rabattre à droite','Elle devra obligatoirement dépasser les deux véhicules en une seule fois','Elle doit rester sur la gauche après avoir dépassé le premier véhicule'],correct:0,explanation:'Le conducteur doit penser à la fin du dépassement avant même de le commencer. Il doit pouvoir revenir à droite sans gêner les autres conducteurs.'},
{type:'text',visualId:'M4_OVERTAKE_SEQUENCE_01',title:'Rétroviseur → angle mort → clignotant',body:'Observe la circulation, contrôle le rétroviseur gauche, contrôle l’angle mort, mets le clignotant gauche, puis déplace-toi vers la gauche si la situation le permet.',callout:'CLIGNOTANT ≠ PRIORITÉ'},
{type:'text',visualId:'M4_OVERTAKE_INDICATOR_01',title:'Le clignotant pendant le dépassement',body:'Le clignotant annonce le déplacement latéral. Pour revenir à droite : contrôle, clignotant droit, rabattement.',callout:'LE CLIGNOTANT N’ACCORDE AUCUNE PRIORITÉ.'},
{type:'scenario',visualId:'M4_OVERTAKEN_ACCELERATION_RISK_01',title:'Le véhicule dépassé',body:'La voiture rouge est déjà en train de dépasser la bleue.',question:'Quelle action rend principalement cette situation dangereuse ?',options:['La voiture rouge poursuit son dépassement','La voiture bleue augmente son allure alors qu’elle est dépassée','La voiture rouge circule momentanément à gauche'],correct:1,explanation:'Lorsqu’un conducteur est dépassé, il doit conserver la même allure et ne pas accélérer. Accélérer allonge inutilement la durée nécessaire au dépassement.'},
{type:'scenario',visualId:'M4_OVERTAKE_HIDDEN_ROAD_01',title:'Route cachée',body:'Aucun véhicule venant en sens inverse n’est visible, mais une partie importante de la route est cachée.',question:'Cette observation suffit-elle pour commencer le dépassement ?',options:['Oui, puisqu’aucun véhicule n’est actuellement visible','Non, car une partie de la route devant le conducteur n’est pas visible','Oui, si la voiture devant roule nettement plus lentement'],correct:1,explanation:'Ne pas voir de véhicule ne signifie pas que la route est libre. Si une partie de la chaussée est cachée, un véhicule peut s’y trouver sans être visible.'},
{type:'scenario',visualId:'M4_OVERTAKE_MULTI_ANALYSIS_01',title:'Piège multi-informations',body:'La ligne est discontinue et aucun véhicule n’arrive en face, mais une voiture derrière a commencé à dépasser.',question:'Quel détail change la décision ?',options:['La ligne centrale est discontinue','La voiture devant roule lentement','Un conducteur derrière a déjà commencé à dépasser'],correct:2,explanation:'La ligne discontinue et l’absence de circulation opposée ne suffisent pas. Le conducteur doit aussi contrôler ce qui se passe derrière lui.'},
{type:'scenario',visualId:'M4_OVERTAKE_DECISION_01',title:'Question de raisonnement',body:'La route présente une partie cachée malgré une ligne discontinue.',question:'Quel raisonnement est incorrect ?',options:['Je dois tenir compte de la partie de route que je ne peux pas voir','La ligne est discontinue, donc le dépassement est automatiquement sûr','Je dois vérifier que je pourrai terminer le dépassement sans danger'],correct:1,explanation:'Une ligne discontinue ne garantit jamais qu’un dépassement peut être effectué en sécurité. Il faut toujours analyser la visibilité et l’ensemble de la circulation.'},
{type:'summary',title:'Méthode PermisHub',items:['Regarde loin.','Vérifie la circulation en sens inverse.','Regarde derrière et contrôle ton angle mort.','Vérifie l’espace pour te rabattre.','Vérifie la signalisation.','Décide ensuite.']}
],quiz:[
{visualId:'M4_OVERTAKE_ONCOMING_01',question:'Quel risque rend le dépassement dangereux dans cette situation ?',options:['Le véhicule venant en sens inverse','La vitesse lente du véhicule bleu','La ligne centrale'],correct:0,explanation:'Le véhicule venant en sens inverse serait mis en danger.'},
{visualId:'M4_OVERTAKE_REAR_CHECK_01',question:'Pourquoi la voiture rouge doit-elle attendre ?',options:['Le véhicule gris derrière a déjà commencé son dépassement','La voiture bleue est trop lente','La route a deux sens'],correct:0,explanation:'Un dépassement déjà engagé derrière toi doit être pris en compte.'},
{visualId:'M4_OVERTAKE_RETURN_SPACE_01',question:'Quel contrôle doit précéder la manœuvre ?',options:['Vérifier l’espace pour revenir à droite','Prévoir de rester à gauche','Dépasser le premier véhicule puis décider'],correct:0,explanation:'Il faut pouvoir terminer et se rabattre sans gêner.'},
{visualId:'M4_OVERTAKEN_ACCELERATION_RISK_01',question:'Quel comportement de la voiture bleue complique la manœuvre ?',options:['Elle garde son allure','Elle accélère pendant qu’elle est dépassée','Elle reste à droite'],correct:1,explanation:'Le véhicule dépassé ne doit pas accélérer.'},
{visualId:'M4_OVERTAKE_HIDDEN_ROAD_01',question:'Pourquoi l’absence de véhicule visible ne suffit-elle pas ?',options:['La partie cachée de la route peut contenir un véhicule','La voiture bleue est lente','La ligne est discontinue'],correct:0,explanation:'Une route cachée n’est pas nécessairement libre.'},
{visualId:'M4_OVERTAKE_MULTI_ANALYSIS_01',question:'Quel élément interdit de commencer la manœuvre malgré une route qui semble libre ?',options:['Le véhicule derrière déjà engagé à gauche','La ligne discontinue','La vitesse lente du véhicule bleu'],correct:0,explanation:'Le conducteur doit contrôler ce qui se passe derrière lui.'},
{visualId:'M4_OVERTAKE_FINAL_COMPLEX_01',question:'Quel élément permet surtout de conclure que la situation est compatible avec un dépassement ?',options:['Le véhicule devant roule lentement','L’ensemble des contrôles montre une voie libre et un espace suffisant pour effectuer puis terminer la manœuvre','La ligne centrale est discontinue'],correct:1,explanation:'Aucun élément isolé ne suffit : il faut analyser l’ensemble de la situation.'}
],nextLessonLabel:'Suivant : Quand le dépassement est interdit →',resultMessages:{perfect:'Excellent. Tu analyses toute la situation avant de dépasser.',good:'Bon travail. Revois les contrôles devant, derrière et l’espace de rabattement.',low:'Reprends la méthode : regarde loin, contrôle derrière, vérifie l’espace, puis décide.'}}
