import type { LearningLesson } from './types'

export const LESSON_3: LearningLesson = {
  id: 'feux-particuliers-et-fleches', moduleId: 'signalisation', title: 'Feux particuliers & flèches', description: 'Comprendre les flèches vertes, les signaux d’évacuation et les feux au-dessus des bandes.', xp: 20,
  steps: [
    { type: 'scenario', title: 'Un feu rouge… mais tu peux quand même passer ?', body: 'Tu connais les feux classiques. Mais certaines situations sont plus piégeuses : feu rouge + flèche verte, flèche d’évacuation, flèche au-dessus d’une bande, croix rouge et orange clignotant particulier. Illustration : feu rouge accompagné d’une flèche verte vers la droite.', question: 'Ton feu principal est rouge mais une flèche verte vers la droite est allumée. Peux-tu tourner ?', options: ['Non, un feu rouge interdit toujours tout passage', 'Oui, uniquement dans la direction de la flèche et en cédant le passage', 'Oui, et je suis prioritaire'], correct: 1, explanation: 'La flèche verte autorise sa direction, mais tu dois céder le passage.' },
    { type: 'text', title: '🔴 + ➡️ La flèche verte', body: 'FEU ROUGE + FLÈCHE VERTE = passage possible dans la direction de la flèche. Suis uniquement cette direction et cède le passage aux piétons, cyclistes et autres véhicules.', callout: '🧠 Flèche verte = autorisation, pas priorité absolue.' },
    { type: 'scenario', title: 'Le piège du piéton', body: '🔴 Feu rouge + ➡️ flèche verte vers la droite. Un piéton traverse la chaussée dans laquelle tu veux tourner. Illustration : piéton devant la trajectoire.', question: 'Que fais-tu ?', options: ['Je passe car j’ai une flèche verte', 'Je cède le passage au piéton puis je tourne', 'Je klaxonne pour qu’il s’arrête'], correct: 1, explanation: 'La flèche autorise à tourner, mais ne supprime pas l’obligation de céder le passage.' },
    { type: 'compare', title: '↩️ La flèche d’évacuation', body: 'Elle facilite l’évacuation d’un carrefour et concerne les véhicules déjà engagés.', items: [{ label: 'Voiture déjà engagée', result: '→ Peut terminer son mouvement' }, { label: 'Voiture avant le carrefour', result: '→ Respecte son feu rouge' }] },
    { type: 'text', title: 'Flèche d’évacuation allumée', body: 'Tu es déjà engagé pour tourner à gauche. Les véhicules en sens inverse sont arrêtés par leur feu rouge : tu peux terminer ton mouvement. Illustration : voiture engagée, trajectoire à gauche, circulation opposée arrêtée.', callout: '⚠️ Elle ne donne pas une autorisation générale d’entrer dans le carrefour.' },
    { type: 'compare', title: 'Et si la flèche est éteinte ?', body: 'Si les conducteurs venant en face circulent également, tu dois leur céder le passage avant de terminer ton changement de direction.', items: [{ label: 'FLÈCHE ALLUMÉE', result: 'Circulation opposée arrêtée' }, { label: 'FLÈCHE ÉTEINTE', result: 'Attention aux conducteurs en face' }] },
    { type: 'scenario', title: 'Le gros piège', body: 'Tu n’es pas encore engagé dans le carrefour. Ton feu est rouge. Une flèche d’évacuation est visible dans le carrefour.', question: 'Peux-tu entrer grâce à cette flèche ?', options: ['Oui', 'Non'], correct: 1, explanation: 'La flèche concerne les véhicules déjà engagés. Tu respectes ton feu rouge.' },
    { type: 'hierarchy', title: 'Regarde au-dessus de ta bande', body: 'Les signaux au-dessus des bandes indiquent quelles voies utiliser ou quitter.', items: ['⬇️ Flèche verte — bande utilisable', '↘️ Flèche orange — quitte cette bande', '❌ Croix rouge — bande interdite'], memory: 'Verte = utilise · Orange = quitte · Rouge = interdit' },
    { type: 'scenario', title: 'Question interactive bandes', body: 'Tu roules sur une route à trois bandes. Au-dessus de ta bande apparaît une flèche orange.', question: 'Que dois-tu faire ?', options: ['Continuer normalement', 'Quitter cette bande', 'T’arrêter immédiatement sur la bande'], correct: 1, explanation: 'La flèche orange indique que tu dois quitter cette bande.' },
    { type: 'text', title: '❌ Croix rouge = bande interdite', body: 'Une croix rouge au-dessus d’une bande signifie que tu ne peux pas circuler sur cette bande.', callout: 'À ne pas confondre : flèche orange = quitte la bande. Croix rouge = bande interdite.' },
    { type: 'compare', title: '🟠 Regarde où se trouve l’orange clignotant', body: 'La position du signal change sa signification dans la situation étudiée.', items: [{ label: 'Orange clignotant au milieu', result: 'Feu en panne → priorités' }, { label: 'Orange clignotant en bas', result: 'Feu fonctionnel → franchir avec prudence' }] },
    { type: 'summary', title: 'À retenir', items: ['🔴 + ➡️ verte : suis la flèche et cède le passage', '↩️ Flèche d’évacuation : véhicules déjà engagés', '⬇️ Verte au-dessus d’une bande : bande utilisable', '↘️ Orange : quitte la bande', '❌ Rouge : bande interdite', '🟠 Clignotant : observe sa position et respecte les priorités'] },
  ],
  quiz: [
    { question: 'Feu rouge + flèche verte vers la droite. Que peux-tu faire ?', options: ['Rien', 'Tourner à droite en cédant le passage', 'Aller dans n’importe quelle direction'], correct: 1, explanation: 'La flèche autorise uniquement sa direction, avec obligation de céder le passage.' },
    { question: 'Tu tournes avec une flèche verte mais un piéton traverse.', options: ['Je passe avant lui', 'Je lui cède le passage', 'Je klaxonne'], correct: 1, explanation: 'La flèche verte ne supprime pas la priorité du piéton.' },
    { question: 'Tu es encore avant le carrefour, feu rouge, flèche d’évacuation allumée.', options: ['J’entre dans le carrefour', 'Je respecte mon feu rouge'], correct: 1, explanation: 'La flèche concerne les véhicules déjà engagés.' },
    { question: 'Tu es déjà engagé pour tourner à gauche et la flèche d’évacuation est allumée.', options: ['Les véhicules venant en face sont arrêtés', 'Je fais marche arrière', 'Je coupe le moteur'], correct: 0, explanation: 'Tu peux terminer ton mouvement pendant que le sens opposé est arrêté.' },
    { question: 'Une flèche orange apparaît au-dessus de ta bande.', options: ['Je dois quitter cette bande', 'Je peux y rester', 'Je dois stationner'], correct: 0, explanation: 'La flèche orange indique qu’il faut quitter la bande.' },
    { question: 'Une croix rouge apparaît au-dessus de ta bande.', options: ['Bande conseillée', 'Bande réservée aux dépassements', 'Circulation interdite sur cette bande'], correct: 2, explanation: 'La croix rouge interdit la circulation sur cette bande.' },
  ],
  resultMessages: { perfect: 'Excellent, les feux particuliers n’ont plus de secret pour toi.', good: 'Bien joué. Revois les situations où tu as hésité.', low: 'Ces feux sont piégeux. Revois tes erreurs avant de continuer.' },
}
