import type { LearningLesson } from './types'
export const LESSON_29: LearningLesson = {
  id:'manoeuvres-et-situations-complexes', moduleId:'manoeuvres-overtaking', title:'Manœuvres & situations complexes', description:'Observer, signaler et agir sans couper dangereusement une trajectoire.', xp:25,
  steps:[
    {type:'text',visualId:'M4_MANEUVER_OVERVIEW_01',title:'Avant d’effectuer un mouvement',body:'Avant de tourner ou de changer de position, observe la circulation, repère les autres usagers et les trajectoires qui peuvent se croiser. Signale ton intention lorsque nécessaire, puis agis seulement si la situation le permet.',callout:'OBSERVER → AUTRES USAGERS → SIGNALER → AGIR SI C’EST SÛR'},
    {type:'text',visualId:'M4_MANEUVER_CHECK_SEQUENCE_01',title:'Le clignotant annonce, il ne décide pas',body:'Le clignotant sert à annoncer ton intention. Il ne permet pas d’ignorer un usager présent ni une trajectoire que ton mouvement va couper.',callout:'CLIGNOTANT ≠ PRIORITÉ'},
    {type:'compare',visualId:'M4_TURN_RIGHT_LEFT_COMPARE_01',title:'Tourner change ta trajectoire',body:'À droite, la trajectoire est serrée. À gauche, elle est plus large et adaptée au changement de direction. Dans les deux cas, regarde les usagers que ton mouvement peut concerner.',items:[{label:'TOURNER À DROITE',result:'Observer la trajectoire à droite'},{label:'TOURNER À GAUCHE',result:'Observer la circulation en face'}]},
    {type:'text',visualId:'M4_LEFT_TURN_ONCOMING_01',title:'Tourner à gauche et couper une trajectoire',body:'Un véhicule arrive en sens inverse et continue tout droit. Avant de tourner à gauche, le conducteur doit tenir compte de cette trajectoire qui croise la sienne.',callout:'AVANT DE COUPER UNE TRAJECTOIRE, REGARDE QUI ARRIVE EN FACE.'},
    {type:'scenario',visualId:'M4_LEFT_TURN_ONCOMING_01',title:'Trafic venant en face',body:'La voiture rouge veut tourner à gauche. La voiture bleue arrive en sens inverse et continue tout droit.',question:'Quelle décision est correcte ?',options:['La rouge tourne d’abord parce que son clignotant est activé','La rouge tient compte du véhicule venant en sens inverse avant de tourner','Les deux véhicules peuvent toujours passer simultanément'],correct:1,explanation:'Le clignotant ne crée pas de priorité. La voiture rouge ne peut pas couper dangereusement la trajectoire du véhicule venant en face.'},
    {type:'text',visualId:'M4_TURN_CYCLIST_01',title:'Ne regarde pas seulement les voitures',body:'Un cycliste peut continuer tout droit à côté de la voiture pendant que celle-ci veut tourner. Sa trajectoire peut alors être coupée.',callout:'LE CYCLISTE FAIT PARTIE DE LA SITUATION.'},
    {type:'scenario',visualId:'M4_TURN_CYCLIST_01',title:'Tourner avec un cycliste',body:'La voiture veut tourner tandis que le cycliste continue sa trajectoire.',question:'Que doit faire le conducteur avant de tourner ?',options:['Tenir compte du cycliste et ne pas lui couper la trajectoire','Tourner immédiatement car le clignotant est activé','Klaxonner pour que le cycliste ralentisse'],correct:0,explanation:'Le clignotant annonce l’intention du conducteur, mais ne lui donne pas automatiquement le passage.'},
    {type:'text',visualId:'M4_TURN_PEDESTRIAN_01',title:'Regarde aussi après le virage',body:'La chaussée dans laquelle tu t’engages peut contenir un piéton. Regarde au-delà du volant et de la première partie du virage.',callout:'TA TRAJECTOIRE PEUT AUSSI CROISER CELLE D’UN PIÉTON.'},
    {type:'scenario',visualId:'M4_TURN_PEDESTRIAN_01',title:'Piéton dans la rue où tu entres',body:'Un piéton traverse la chaussée dans laquelle la voiture souhaite s’engager.',question:'Quel élément doit retenir l’attention du conducteur ?',options:['Le piéton dont la trajectoire peut être coupée','Uniquement la voiture derrière','La couleur du marquage au sol'],correct:0,explanation:'Le conducteur doit observer la chaussée dans laquelle il va s’engager et les usagers dont il peut couper la trajectoire.'},
    {type:'text',visualId:'M4_INDICATOR_NOT_PRIORITY_01',title:'Le piège du clignotant',body:'Avoir signalé un mouvement ne le rend pas automatiquement réalisable. Les autres usagers restent présents et les règles de sécurité restent applicables.',callout:'SIGNALER ≠ AVOIR LA PRIORITÉ'},
    {type:'text',visualId:'M4_LANE_CHANGE_COMPLEX_01',title:'Changer de bande ou de position',body:'Avant de changer de bande, observe ce qui arrive, vérifie la zone concernée, signale ton intention et change de position uniquement lorsque cela peut être fait sans danger.',callout:'UNE VOITURE PEUT DÉJÀ ÊTRE PRÉSENTE SUR LA BANDE VISÉE.'},
    {type:'scenario',visualId:'M4_MANEUVER_CYCLIST_COMPLEX_01',title:'Observer toute la scène',body:'La voiture approche d’un carrefour. Plusieurs trajectoires sont proches sans qu’un danger soit annoncé dans le texte.',question:'Avant d’agir, qu’est-ce qui doit attirer ton attention ?',options:['Les usagers et trajectoires que le mouvement risque de croiser','Uniquement le clignotant de la voiture','Seulement la voie où se trouve la voiture'],correct:0,explanation:'Dans une situation complexe, il faut repérer les autres usagers et les trajectoires qui peuvent entrer en conflit avec le mouvement prévu.'},
    {type:'scenario',visualId:'M4_MANEUVER_LEFT_COMPLEX_01',title:'Situation complexe finale',body:'La voiture veut tourner à gauche. Un véhicule arrive en face et un piéton est présent dans la rue où elle veut entrer.',question:'Quel raisonnement est correct ?',options:['Vérifier uniquement le véhicule venant en face','Tourner dès que le véhicule est passé, sans regarder la rue où l’on entre','Tenir compte du véhicule venant en face puis du piéton avant de terminer le mouvement'],correct:2,explanation:'Une seule manœuvre peut nécessiter plusieurs contrôles successifs : le trafic que tu coupes, puis la chaussée dans laquelle tu t’engages.'},
    {type:'summary',title:'À retenir',items:['Observer avant d’agir.','Anticiper les trajectoires qui peuvent se croiser.','Tenir compte du trafic venant en face avant de tourner à gauche.','Ne pas oublier cyclistes et piétons.','Changer de position seulement lorsque la situation le permet.','Clignotant ≠ priorité.']}
  ],
  quiz:[
    {visualId:'M4_LEFT_TURN_ONCOMING_01',question:'Avant de tourner à gauche, quelle trajectoire faut-il analyser dans cette scène ?',options:['Celle du véhicule venant en sens inverse','Seulement celle de la voiture derrière','Aucune si le clignotant est activé'],correct:0,explanation:'Le véhicule venant en face peut continuer tout droit et croiser ta trajectoire.'},
    {visualId:'M4_TURN_CYCLIST_01',question:'Pourquoi le cycliste doit-il être pris en compte ?',options:['Sa trajectoire peut être coupée par le virage','Il doit toujours s’arrêter pour la voiture','Il est hors de la situation'],correct:0,explanation:'Le changement de direction de la voiture peut couper la trajectoire du cycliste.'},
    {visualId:'M4_TURN_PEDESTRIAN_01',question:'Quel regard complète l’observation avant le virage ?',options:['Regarder la chaussée dans laquelle on s’engage','Regarder uniquement le rétroviseur intérieur','Regarder uniquement le feu arrière de la voiture'],correct:0,explanation:'La chaussée où tu entres peut contenir un piéton ou un autre usager.'},
    {visualId:'M4_INDICATOR_NOT_PRIORITY_01',question:'Ton clignotant est activé. Que signifie-t-il ?',options:['Il annonce ton intention','Il te donne la priorité','Il rend le mouvement automatiquement sûr'],correct:0,explanation:'Le clignotant annonce ton intention. Il ne supprime pas les autres usagers.'},
    {visualId:'M4_LANE_CHANGE_COMPLEX_01',question:'Avant de changer de bande, quel raisonnement est correct ?',options:['Observer la bande visée et agir seulement si le déplacement est sûr','Se déporter dès que le clignotant est activé','Ignorer un véhicule déjà présent sur la bande'],correct:0,explanation:'Le changement de position doit tenir compte des autres usagers présents dans la zone concernée.'},
    {visualId:'M4_MANEUVER_LEFT_COMPLEX_01',question:'Quel piège contient la situation finale ?',options:['Ne regarder qu’un seul élément et oublier la suite de la trajectoire','Mettre le clignotant trop tôt','Ne pas connaître la couleur du véhicule venant en face'],correct:0,explanation:'La scène demande plusieurs contrôles : trafic opposé et chaussée dans laquelle la voiture entre.'}
  ],nextLessonLabel:'Retour au module 4 →',resultMessages:{perfect:'Module 4 terminé. Tu sais maintenant analyser une situation avant de changer de direction ou de position.',good:'Module 4 terminé. Revois les scènes où plusieurs trajectoires se croisent.',low:'Module 4 terminé. Reprends la méthode : observer, identifier les trajectoires, signaler puis agir seulement si la situation est sûre.'}
}
