import type { LearningLesson } from './types'

const normalQuestion = { visualId: 'M4_TRAM_RIGHT_OVERTAKE_01', question: 'La voiture rouge souhaite dépasser le tram. Quelle trajectoire correspond à la règle normale ?', options: ['Passer à droite du tram.', 'Passer systématiquement à gauche comme pour une voiture.', 'Choisir librement le côté le plus large.'], correct: 0, explanation: 'Un véhicule sur rails se dépasse normalement par la droite.' }
const blockedQuestion = { visualId: 'M4_TRAM_RIGHT_BLOCKED_CAR_01', question: 'Quel élément change ici l’application de la règle normale ?', options: ['Le véhicule stationné qui empêche le passage à droite.', 'La vitesse du tram.', 'La couleur du marquage des rails.'], correct: 0, explanation: 'Un véhicule stationné qui bloque la droite fait partie des exceptions permettant d’envisager la gauche.' }
const oncomingQuestion = { visualId: 'M4_TRAM_LEFT_ONCOMING_01', question: 'Quelle décision est correcte ?', options: ['Passer immédiatement à gauche puisque la droite est bloquée.', 'Attendre : l’exception permet d’envisager la gauche mais pas de mettre en danger l’usager venant en sens inverse.', 'Commencer le dépassement : le véhicule venant en sens inverse doit céder le passage.'], correct: 1, explanation: 'L’exception ne rend pas la manœuvre automatiquement sûre. Il faut attendre que la gauche soit sûre.' }

export const LESSON_28_TRAINING_BANK = [
  { visualId: 'M4_TRAM_RIGHT_TOO_NARROW_01', question: 'Que signifie un passage à droite trop étroit ?', options: ['Une exception permet d’envisager la gauche.', 'La gauche devient toujours obligatoire.', 'Le tram se dépasse de chaque côté.'], correct: 0, explanation: 'Le manque d’espace à droite est une exception précise.' },
  { visualId: 'M4_TRAM_FIXED_OBSTACLE_01', question: 'Que change l’obstacle fixe à droite ?', options: ['Il permet d’envisager la gauche.', 'Il donne une priorité automatique.', 'Il interdit toujours tout passage.'], correct: 0, explanation: 'L’obstacle peut changer le côté envisageable, pas les conditions de sécurité.' },
  { visualId: 'M4_TRAM_LEFT_VISIBILITY_01', question: 'Aucun véhicule n’est visible, mais la route est masquée. Que faire ?', options: ['Commencer.', 'Attendre : la visibilité est insuffisante.', 'Klaxonner puis passer.'], correct: 1, explanation: 'Ne rien voir ne signifie pas que personne n’arrive.' },
  { visualId: 'M4_CAR_VS_TRAM_OVERTAKE_01', question: 'Pourquoi la trajectoire diffère-t-elle pour un tram ?', options: ['Le tram suit une règle liée aux rails.', 'La couleur de la voiture décide.', 'La vitesse suffit à décider.'], correct: 0, explanation: 'Le véhicule sur rails suit une règle particulière.' },
  { visualId: 'M4_TRAM_FALSE_EXCEPTION_01', question: 'La droite est libre et la gauche plus confortable. Peut-on choisir la gauche ?', options: ['Oui.', 'Non, aucune exception ne le justifie.', 'Oui, si le tram roule lentement.'], correct: 1, explanation: 'Le confort n’est pas une exception.' },
  { visualId: 'M4_TRAM_COMPLEX_01', question: 'Un obstacle bloque la droite et une voiture arrive en face. Que faire ?', options: ['Passer immédiatement.', 'Attendre que la gauche soit sûre.', 'Forcer le passage.'], correct: 1, explanation: 'Exception et sécurité sont deux contrôles distincts.' },
  { visualId: 'M4_TRAM_FINAL_ANALYSIS_01', question: 'Une voiture stationnée bloque la droite et un véhicule arrive en face. Que faire ?', options: ['Dépasser immédiatement.', 'Attendre une manœuvre sans danger.', 'Le véhicule opposé doit céder.'], correct: 1, explanation: 'L’exception n’accorde aucune priorité automatique.' }
]

export const LESSON_28: LearningLesson = {
  id: 'tram-et-vehicules-sur-rails', moduleId: 'manoeuvres-overtaking', title: 'Tram et véhicules sur rails', description: 'Comprendre les particularités du tram, ses règles et les décisions sûres.', xp: 25,
  steps: [
    { type: 'text', visualId: 'M4_TRAM_CHARACTERISTICS_01', title: 'Un tram n’est pas une voiture', body: 'Un véhicule sur rails suit une trajectoire imposée. Il ne peut pas se déporter comme une voiture : anticipe sa présence et ses mouvements.', callout: 'RAILS → TRAJECTOIRE IMPOSÉE' },
    { type: 'text', visualId: 'M4_TRAM_PRIORITY_01', title: 'Un régime particulier', body: 'Le tram ne se traite pas comme une voiture ordinaire dans les règles de priorité. Observe toujours l’intersection et les indications présentes.', callout: 'NE TRANSFORME PAS CETTE RÈGLE EN AUTOMATISME.' },
    { type: 'text', visualId: 'M4_TRAM_IN_ROAD_01', title: 'Des rails dans ta trajectoire', body: 'Les rails peuvent être intégrés directement dans la chaussée. Garde une lecture active de l’espace autour du tram.' },
    { type: 'text', visualId: 'M4_TRAM_RULE_COMPARE_01', title: 'La règle qui change', body: 'Une voiture ordinaire se dépasse normalement par la gauche. Un véhicule sur rails se dépasse normalement par la droite.', callout: 'VOITURE : GAUCHE · TRAM : DROITE' },
    { type: 'scenario', title: 'Question 1', body: 'Le passage à droite du tram est libre, large et sans obstacle.', ...normalQuestion },
    { type: 'text', visualId: 'M4_TRAM_EXCEPTIONS_01', title: 'Trois exceptions à reconnaître', body: 'Le passage à gauche peut être envisagé si le passage à droite est trop étroit, si un véhicule arrêté ou stationné le bloque, ou si un obstacle fixe l’empêche.', callout: 'ENVISAGER LA GAUCHE ≠ POUVOIR PASSER IMMÉDIATEMENT.' },
    { type: 'scenario', title: 'Question 2', body: 'Une voiture stationnée bloque le passage à droite. La gauche est dégagée et visible.', ...blockedQuestion },
    { type: 'scenario', title: 'Question 3', body: 'La droite est bloquée, mais un véhicule arrive en sens inverse.', ...oncomingQuestion },
    { type: 'text', visualId: 'M4_TRAM_FALSE_EXCEPTION_01', title: 'Une préférence n’est pas une exception', body: 'Lorsque le passage à droite est libre et suffisamment large, choisir la gauche parce qu’elle paraît plus confortable ne justifie pas d’abandonner la règle normale.', callout: 'LE CONFORT N’EST PAS UNE EXCEPTION.' },
    { type: 'scenario', visualId: 'M4_TRAM_COMPLEX_01', title: 'Situation complexe', body: 'Un obstacle bloque la droite et un véhicule arrive en face. Il faut distinguer le côté que l’on peut envisager du moment où la manœuvre est réellement sûre.', question: 'Quelle décision est correcte ?', options: ['Passer immédiatement à gauche', 'Attendre que la gauche soit sûre', 'Forcer le véhicule opposé à s’arrêter'], correct: 1, explanation: 'L’obstacle crée une exception au côté normal, mais la circulation opposée peut empêcher de passer maintenant.' },
    { type: 'text', visualId: 'M4_TRAM_LEFT_VISIBILITY_01', title: 'Révision : visibilité et sécurité', body: 'Une exception ne supprime jamais les conditions générales de sécurité du dépassement. Sans visibilité suffisante, tu ne peux pas vérifier la gauche.', callout: 'JE NE VOIS PERSONNE ≠ PERSONNE N’ARRIVE' },
    { type: 'scenario', visualId: 'M4_TRAM_FINAL_ANALYSIS_01', title: 'Décision finale', body: 'Une voiture stationnée bloque la droite et un véhicule arrive en sens inverse.', question: 'Quelle analyse est correcte ?', options: ['La voiture rouge peut dépasser immédiatement', 'Elle attend une manœuvre sans danger', 'Le véhicule opposé doit céder'], correct: 1, explanation: 'La voiture stationnée permet d’envisager un autre côté, mais ne donne aucune priorité automatique.' },
    { type: 'summary', title: 'À retenir', items: ['Tram : trajectoire imposée par les rails.', 'Règles particulières de priorité.', 'Dépassement normalement par la droite.', 'Gauche seulement dans certaines situations précises.', 'Exception ≠ priorité.', 'Toujours vérifier visibilité, trafic opposé et sécurité.'] }
  ],
  quiz: [normalQuestion, blockedQuestion, oncomingQuestion],
  nextLessonLabel: 'Suivant : Manœuvres & situations complexes →',
  resultMessages: { perfect: 'Excellent. Tu distingues la règle, l’exception et la sécurité réelle.', good: 'Bon travail. Revois la différence entre gauche possible et gauche sûre.', low: 'Reprends la méthode : règle à droite, exception précise, puis contrôle de la gauche.' }
}
