import type { LearningLesson } from './types'

export const LESSON_25: LearningLesson = {
  id: 'quand-le-depassement-est-interdit',
  moduleId: 'manoeuvres-overtaking',
  title: 'Quand le dépassement est interdit',
  description: 'Apprends à analyser le lieu, la visibilité, le marquage, la signalisation et l’usager dépassé.',
  xp: 25,
  steps: [
    { type: 'text', visualId: 'M4_FORBIDDEN_OVERTAKE_OVERVIEW_01', title: 'Dépasser par la gauche : parfois interdit', body: 'Même si la route semble libre, certaines situations interdisent le dépassement par la gauche. L’interdiction peut dépendre du lieu, du véhicule dépassé et de la signalisation.', callout: 'ANALYSE LA SITUATION ET L’USAGER QUE TU VEUX DÉPASSER.' },
    { type: 'text', title: 'Le bon raisonnement', body: 'Ne retiens pas « endroit dangereux = je ne dépasse jamais personne ». Observe le marquage, ce que tu vois devant, les panneaux et qui se trouve devant toi.', callout: 'QUI + OÙ + SIGNALISATION + VISIBILITÉ' },
    { type: 'scenario', visualId: 'M4_MARKING_MIXED_LINES_01', title: 'Deux lignes accolées', body: 'La voiture rouge suit la bleue. La ligne discontinue est du côté de la voiture rouge ; la ligne continue est du côté opposé.', question: 'Quel marquage la voiture rouge doit-elle prendre en considération pour savoir si elle peut franchir l’axe ?', options: ['La ligne discontinue située de son côté', 'La ligne continue située du côté opposé', 'Les deux lignes interdisent automatiquement le dépassement'], correct: 0, explanation: 'Lorsqu’une ligne continue et une ligne discontinue sont accolées, le conducteur tient compte de la ligne située de son côté. Une ligne discontinue peut être franchie si les autres conditions sont aussi remplies.' },
    { type: 'scenario', visualId: 'M4_DASHED_NOT_PERMISSION_01', title: 'Une ligne discontinue ne suffit pas', body: 'La voiture rouge suit un véhicule lent. La ligne est discontinue, mais un sommet masque complètement la route après la crête.', question: 'La voiture rouge peut-elle commencer son dépassement ?', options: ['Oui, car une ligne discontinue autorise toujours le dépassement', 'Non, car la visibilité vers l’avant est insuffisante', 'Oui, si elle utilise son clignotant'], correct: 1, explanation: 'Une ligne discontinue permet de franchir le marquage, mais elle ne garantit ni que le dépassement est autorisé, ni qu’il est sûr. La visibilité doit être suffisante.' },
    { type: 'scenario', visualId: 'M4_FORBIDDEN_HILL_01', title: 'Sommet de côte : ce qui compte', body: 'Aucun véhicule n’est visible en face, mais la route derrière le sommet est cachée.', question: 'Pourquoi l’absence de véhicule visible ne suffit-elle pas ici ?', options: ['Un véhicule peut être caché derrière le sommet', 'Il est toujours interdit de dépasser dans une montée', 'Une voiture ne peut jamais dépasser sur une route à double sens'], correct: 0, explanation: 'Le problème n’est pas la montée en elle-même : c’est la visibilité insuffisante à l’approche du sommet. Un véhicule venant en sens inverse peut être caché.' },
    { type: 'scenario', visualId: 'M4_FORBIDDEN_CURVE_01', title: 'Virage sans visibilité', body: 'La voiture rouge suit une voiture bleue. La végétation et le bâti masquent la suite du virage.', question: 'Quel élément est déterminant dans cette situation ?', options: ['La voiture bleue roule lentement', 'Le virage masque une partie de la route', 'Aucun véhicule venant en sens inverse n’est actuellement visible'], correct: 1, explanation: 'Dans ou à l’approche d’un virage où la visibilité est insuffisante, l’absence de véhicule visible ne prouve pas que la voie opposée est libre.' },
    { type: 'scenario', visualId: 'M4_FORBIDDEN_INTERSECTION_01', title: 'Carrefour : analyse précise', body: 'La ligne est discontinue et la route semble libre. La voiture rouge arrive toutefois à un carrefour où la priorité de droite s’applique.', question: 'Quel élément doit empêcher le conducteur de raisonner uniquement sur la ligne et la route libre ?', options: ['Le carrefour où la priorité de droite s’applique', 'La voiture devant possède quatre roues', 'Il n’y a aucun feu de circulation'], correct: 0, explanation: 'Les règles de dépassement dépendent aussi du type de carrefour. À un carrefour où la priorité de droite s’applique, certaines catégories de véhicules ne peuvent pas être dépassées par la gauche.' },
    { type: 'scenario', visualId: 'M4_LEVEL_CROSSING_COMPARE_01', title: 'Passage à niveau : observer son équipement', body: 'Deux passages à niveau peuvent avoir une configuration différente, par exemple avec ou sans barrières.', question: 'Pourquoi ces situations ne doivent-elles pas être analysées de la même manière ?', options: ['La réglementation tient notamment compte des barrières ou de la signalisation', 'Un passage avec barrières devient une autoroute', 'Une ligne discontinue annule les règles du passage à niveau'], correct: 0, explanation: 'Les règles de dépassement à un passage à niveau dépendent de sa configuration. Observe le passage à niveau lui-même, pas seulement le marquage.' },
    { type: 'scenario', visualId: 'M4_CROSSWALK_OVERTAKE_01', title: 'Passage pour piétons', body: 'La voiture bleue ralentit à l’approche du passage pour piétons. La voiture rouge la suit.', question: 'Quelle est la bonne décision de la voiture rouge ?', options: ['La dépasser avant que le piéton traverse', 'Ne pas la dépasser', 'La dépasser si la ligne centrale est discontinue'], correct: 1, explanation: 'Il est interdit de dépasser un conducteur qui approche, ralentit ou s’arrête devant un passage pour piétons, ou un passage prévu pour les cyclistes et cyclomoteurs à deux roues.' },
    { type: 'scenario', visualId: 'M4_RAISED_DEVICE_01', title: 'Dispositif surélevé', body: 'La voiture rouge veut dépasser la voiture bleue sur le dispositif surélevé.', question: 'Quelle réponse est correcte ?', options: ['Elle peut dépasser si elle reste sous 30 km/h', 'Elle ne peut pas effectuer ce dépassement', 'Elle peut dépasser si aucune voiture n’arrive en sens inverse'], correct: 1, explanation: 'Le respect de la vitesse ne suffit pas. Le dépassement par la gauche d’une voiture sur ce type de dispositif est interdit.' },
    { type: 'text', visualId: 'M4_RAISED_DEVICE_CYCLIST_01', title: 'Même lieu, autre usager', body: 'Avant de répondre, regarde qui est dépassé : voiture, motocyclette, cycliste, trottinette ou cavalier. Le type d’usager peut changer l’application de la règle.', callout: 'ENDROIT + USAGER = ANALYSE' },
    { type: 'scenario', visualId: 'M4_BAD_VISIBILITY_CYCLIST_01', title: 'Cycliste et route cachée', body: 'Un cycliste se trouve devant toi, mais un virage masque fortement la circulation opposée.', question: 'Le conducteur peut-il ignorer le problème de visibilité parce qu’il ne dépasse pas une voiture ?', options: ['Oui, un cycliste peut toujours être dépassé', 'Non, une visibilité insuffisante vers l’avant reste déterminante', 'Oui, s’il franchit seulement légèrement l’axe'], correct: 1, explanation: 'Le type d’usager n’efface pas les exigences de sécurité. Avec une visibilité insuffisante vers l’avant, le dépassement ne doit pas être entrepris.' },
    { type: 'scenario', visualId: 'M4_OVERTAKE_SIGN_SIDECAR_01', title: 'Le piège du side-car', body: 'Un panneau d’interdiction de dépasser est actif. La voiture rouge suit une motocyclette avec side-car.', question: 'La voiture rouge peut-elle dépasser cette motocyclette par la gauche ?', options: ['Oui, car il s’agit d’une motocyclette', 'Non, car avec son side-car elle possède plus de deux roues', 'Oui, si la ligne centrale est discontinue'], correct: 1, explanation: 'Le side-car est décisif : la motocyclette possède alors trois roues et entre dans la catégorie des véhicules à plus de deux roues visée par l’interdiction.' },
    { type: 'scenario', visualId: 'M4_TRUCK_OVERTAKE_SIGN_01', title: 'Panneau spécifique aux véhicules lourds', body: 'Certains signaux visent les véhicules ou trains de véhicules affectés au transport de choses dont la MMA dépasse 3 500 kg.', question: 'Une voiture particulière est-elle automatiquement concernée par ce signal ?', options: ['Oui, il concerne tous les véhicules', 'Non, il vise la catégorie de véhicules indiquée par la règle', 'Oui, dès qu’un véhicule devant possède plus de deux roues'], correct: 1, explanation: 'Ce signal ne vise pas automatiquement toutes les voitures particulières. Il concerne la catégorie de véhicules définie par la règle.' },
    { type: 'scenario', visualId: 'M4_TRIPLE_OVERTAKE_01', title: 'Tripler sur une route à double sens', body: 'La voiture bleue dépasse déjà une voiture grise. La voiture rouge envisage de dépasser la bleue.', question: 'La voiture rouge peut-elle dépasser la voiture bleue dans cette configuration ?', options: ['Oui, si aucun véhicule n’arrive en sens inverse', 'Non, dans cette configuration', 'Oui, si les trois véhicules restent sous la limitation'], correct: 1, explanation: 'Sur cette chaussée à double sens, la voiture rouge ne peut pas dépasser une voiture qui est elle-même en train d’en dépasser une autre. Avec au moins trois bandes dans le même sens, la situation peut être différente.' },
    { type: 'summary', title: 'Avant de dépasser, pose-toi six questions', items: ['Qui est-ce que je dépasse ?', 'Où suis-je ?', 'Que dit le marquage ?', 'Y a-t-il un panneau ?', 'Est-ce que je vois suffisamment loin ?', 'Existe-t-il une exception ?'] }
  ],
  quiz: [
    { visualId: 'M4_MARKING_MIXED_LINES_01', question: 'Quelle ligne doit guider la décision de la voiture rouge ?', options: ['La discontinue de son côté', 'La continue du côté opposé', 'Les deux sans distinction'], correct: 0, explanation: 'Le conducteur tient compte de la ligne située de son côté.' },
    { visualId: 'M4_DASHED_NOT_PERMISSION_01', question: 'Pourquoi la ligne discontinue ne suffit-elle pas ici ?', options: ['La visibilité après le sommet est insuffisante', 'Le clignotant est inutile', 'La voiture bleue est lente'], correct: 0, explanation: 'Le sommet cache la circulation qui peut arriver en face.' },
    { visualId: 'M4_FORBIDDEN_CURVE_01', question: 'Pourquoi l’absence de véhicule visible ne suffit-elle pas ?', options: ['Le virage cache une partie de la route', 'La voiture bleue roule lentement', 'La ligne est discontinue'], correct: 0, explanation: 'Une route cachée n’est pas nécessairement libre.' },
    { visualId: 'M4_FORBIDDEN_INTERSECTION_01', question: 'Quel élément faut-il aussi analyser ?', options: ['Le carrefour à priorité de droite', 'La couleur de la voiture devant', 'L’absence de feu'], correct: 0, explanation: 'Le type de carrefour change l’analyse du dépassement.' },
    { visualId: 'M4_LEVEL_CROSSING_COMPARE_01', question: 'Quelle information est déterminante au passage à niveau ?', options: ['Sa configuration et son équipement', 'La couleur du véhicule suivi', 'La présence d’une ligne discontinue seule'], correct: 0, explanation: 'Observe notamment les barrières et la signalisation du passage.' },
    { visualId: 'M4_CROSSWALK_OVERTAKE_01', question: 'La voiture bleue ralentit devant le passage. Que fais-tu ?', options: ['Je ne la dépasse pas', 'Je la dépasse rapidement', 'Je décide uniquement grâce à la ligne'], correct: 0, explanation: 'Le ralentissement devant le passage interdit ce dépassement.' },
    { visualId: 'M4_RAISED_DEVICE_CYCLIST_01', question: 'Pourquoi une situation avec un cycliste ne se lit-elle pas automatiquement comme celle avec une voiture ?', options: ['Le type d’usager change l’application de la règle', 'Le marquage n’a plus aucune importance', 'Un cycliste peut toujours être dépassé'], correct: 0, explanation: 'Il faut analyser à la fois le lieu et l’usager dépassé.' },
    { visualId: 'M4_BAD_VISIBILITY_CYCLIST_01', question: 'Que reste-t-il décisif devant le cycliste ?', options: ['La visibilité vers l’avant', 'Le fait qu’il ait deux roues', 'L’absence de véhicule visible'], correct: 0, explanation: 'La visibilité insuffisante interdit de se fier à une voie opposée cachée.' },
    { visualId: 'M4_OVERTAKE_SIGN_SIDECAR_01', question: 'Pourquoi le panneau s’applique-t-il à la motocyclette avec side-car ?', options: ['Elle possède plus de deux roues', 'Toutes les motos sont concernées', 'La ligne est discontinue'], correct: 0, explanation: 'Avec son side-car, elle possède trois roues.' },
    { visualId: 'M4_FINAL_FORBIDDEN_ANALYSIS_01', question: 'La visibilité est excellente et la ligne discontinue. Quel élément interdit néanmoins le dépassement ?', options: ['Le véhicule devant roule lentement', 'Le véhicule devant ralentit à l’approche du passage pour piétons', 'L’absence de circulation venant en sens inverse'], correct: 1, explanation: 'Une bonne visibilité et une ligne discontinue ne suffisent pas lorsque le véhicule devant ralentit à l’approche d’un passage pour piétons.' }
  ],
  nextLessonLabel: 'Suivant : Panneaux liés au dépassement →',
  resultMessages: { perfect: 'Excellent. Tu analyses le lieu, la visibilité, le marquage et l’usager avant de dépasser.', good: 'Bon travail. Revois les situations où un détail apparent ne suffit pas à autoriser le dépassement.', low: 'Reprends la méthode : qui, où, marquage, panneau, visibilité, exception.' }
}
