import type { LearningLesson } from './types'

export const LESSON_5: LearningLesson = {
  id: 'les-panneaux-de-danger', moduleId: 'signalisation', title: 'Les panneaux de danger', description: 'Reconnaître les principaux dangers et adapter ta conduite plutôt que mémoriser une liste.', xp: 25,
  steps: [
    { type: 'scenario', title: '⚠️ Quel danger t’attend ?', body: 'Un panneau de danger avertit qu’un danger arrive. Ton réflexe : identifier le danger, regarder la situation et adapter ta conduite. Visuel : placeholder « panneau de chaussée glissante ».', question: 'Que t’annonce ce panneau ?', options: ['Stationnement interdit', 'Risque de chaussée glissante', 'Route obligatoire'], correct: 1, explanation: 'Un panneau de danger t’avertit d’un risque à anticiper.' },
    { type: 'compare', title: 'Le danger n’est pas forcément juste après le panneau', body: 'En principe, les signaux de danger sont placés à une distance approximative de 150 m de l’endroit dangereux. Cette distance peut varier.', items: [{ label: '⚠️ PANNEAU', result: '≈ 150 m en principe' }, { label: '⚠️ DANGER', result: 'Regarde la route et anticipe' }] },
    { type: 'scenario', title: 'Et si tu vois « 200 m » dessous ?', body: 'Visuel : placeholder panneau de danger + panneau additionnel « 200 m ».', question: 'Où se trouve le danger ?', options: ['Pendant 200 m', 'Environ 200 m plus loin', 'Le panneau prend fin dans 200 m'], correct: 1, explanation: 'Le panneau additionnel indique ici la distance approximative jusqu’au danger.' },
    { type: 'compare', title: 'Attention : distance ou longueur ?', body: 'Ne confonds pas l’endroit où commence le danger et la longueur de la section dangereuse.', items: [{ label: '⚠️ + 200 m', result: 'Danger environ 200 m plus loin' }, { label: '⚠️ + longueur', result: 'Danger présent sur la longueur indiquée' }] },
    { type: 'scenario', title: '↪️ Lis le premier virage', body: 'Dans une succession de virages, le symbole indique notamment le sens du premier virage. Visuel : placeholder panneau de succession de virages.', question: 'Le premier virage dangereux est dans quel sens ?', options: ['Gauche', 'Droite'], correct: 0, explanation: 'Le premier virage représenté est à gauche.' },
    { type: 'compare', title: '⛰️ Ça monte ou ça descend ?', body: 'Reconnais immédiatement ce que le panneau annonce, sans mélanger avec la mécanique du véhicule.', items: [{ label: 'DESCENTE DANGEREUSE', result: 'La route descend' }, { label: 'MONTÉE À FORTE INCLINAISON', result: 'La route monte' }] },
    { type: 'compare', title: 'De quel côté la route se rétrécit-elle ?', body: 'Lis le dessin du panneau : le rétrécissement peut être des deux côtés, à gauche ou à droite. Visuels : placeholders des trois variantes.', items: [{ label: '↘️ Deux côtés', result: 'La chaussée se rétrécit des deux côtés' }, { label: '↙️ Gauche', result: 'Rétrécissement à gauche' }, { label: '↘️ Droite', result: 'Rétrécissement à droite' }] },
    { type: 'scenario', title: '🌧️ Ta voiture peut perdre de l’adhérence', body: 'Ce panneau annonce un risque de chaussée glissante. Il pleut et tu l’aperçois.', question: 'Quelle attitude est cohérente ?', options: ['Anticiper et adapter ma conduite', 'Accélérer pour sortir rapidement', 'Ignorer le panneau'], correct: 0, explanation: 'Le bon réflexe est d’anticiper et d’adapter ta conduite.' },
    { type: 'compare', title: 'Tous les dangers ne viennent pas des autres usagers', body: 'Galerie de placeholders interactifs : touche une carte pour afficher sa signification.', items: [{ label: 'Cassis / dos d’âne', result: 'Relief sur la chaussée' }, { label: 'Chutes de pierres', result: 'Pierres pouvant tomber sur la route' }, { label: 'Pont mobile', result: 'Ouvrage pouvant se déplacer' }, { label: 'Quai ou berge', result: 'Débouché dangereux' }] },
    { type: 'compare', title: '👀 Usagers vulnérables', body: 'Ces panneaux annoncent un danger : ils ne fixent pas automatiquement une limitation de vitesse précise.', items: [{ label: '🚶 Passage pour piétons', result: 'Anticipe les traversées' }, { label: '🧒 Enfants', result: 'Danger ≠ limitation automatique' }, { label: '🚲 Cyclistes', result: 'Anticipe leur débouché' }] },
    { type: 'compare', title: '🐄 ou 🦌 ? Regarde bien', body: 'Les silhouettes indiquent des dangers différents.', items: [{ label: 'TRAVERSÉE DE BÉTAIL', result: 'Animaux domestiques' }, { label: 'TRAVERSÉE DE GROS GIBIER', result: 'Animaux sauvages' }] },
    { type: 'scenario', title: '🚧 Travaux', body: 'Visuel : placeholder chantier, cônes et chaussée partiellement occupée. Il annonce la présence de travaux.', question: 'Que dois-tu comprendre en premier ?', options: ['La route est obligatoirement fermée', 'Des travaux constituent un danger à anticiper', 'Je suis automatiquement prioritaire'], correct: 1, explanation: 'Les travaux annoncent un danger : anticipe la situation.' },
    { type: 'compare', title: '🚆 Attention au passage à niveau', body: 'Observe bien la différence entre les deux panneaux. Visuels : placeholders côte à côte.', items: [{ label: 'PASSAGE À NIVEAU AVEC BARRIÈRES', result: 'Barrières présentes' }, { label: 'PASSAGE À NIVEAU SANS BARRIÈRES', result: 'Sans barrières' }] },
    { type: 'summary', title: 'À retenir', items: ['⚠️ Un danger possible arrive', '📏 En principe, environ 150 m avant le danger', '➕ Un panneau additionnel peut préciser distance ou longueur', '👀 Regarde le symbole pour connaître le danger', '🚗 Anticipe et adapte ta conduite'] },
  ],
  quiz: [
    { question: 'En principe, à quelle distance approximative le signal de danger est-il placé ?', options: ['15 m', '50 m', '150 m'], correct: 2, explanation: 'En principe, environ 150 m, sauf autre distance indiquée.' },
    { question: 'Un panneau de danger est accompagné de « 200 m ». Que signifie cette indication ?', options: ['Le danger se trouve environ 200 m plus loin', 'Le danger dure obligatoirement 200 m', 'La vitesse maximale est 200 km/h'], correct: 0, explanation: 'Le panneau précise la distance approximative jusqu’au danger.' },
    { question: 'Quel danger annonce le panneau de chaussée glissante ?', options: ['Chaussée glissante', 'Travaux', 'Vent'], correct: 0, explanation: 'Il annonce un risque de perte d’adhérence.' },
    { question: 'Que t’annonce un panneau de rétrécissement à droite ?', options: ['La chaussée se rétrécit à droite', 'Virage obligatoire à droite', 'Stationnement interdit à droite'], correct: 0, explanation: 'Le dessin indique le côté du rétrécissement.' },
    { question: 'Le panneau « enfants » fixe-t-il à lui seul une limitation de vitesse précise ?', options: ['Oui', 'Non'], correct: 1, explanation: 'Il annonce un danger et demande d’adapter la conduite.' },
    { question: 'Quel danger annonce le panneau de gros gibier ?', options: ['Traversée de bétail', 'Traversée de gros gibier', 'Animaux interdits'], correct: 1, explanation: 'La silhouette correspond au gros gibier.' },
    { question: 'Lequel annonce un passage à niveau sans barrières ?', options: ['Le panneau avec barrières', 'Le panneau sans barrières'], correct: 1, explanation: 'Observe la présence ou l’absence de barrières sur le symbole.' },
    { question: 'Un panneau triangulaire annonçant un danger appartient à quelle famille ?', options: ['Obligation', 'Danger', 'Indication'], correct: 1, explanation: 'La forme triangulaire annonce un danger.' },
  ],
  resultMessages: { perfect: 'Excellent. Tu reconnais les principaux dangers.', good: 'Très bien. Quelques panneaux méritent encore une révision.', low: 'Revois les panneaux que tu as confondus avant de continuer.' },
}
