export type ModuleTwoChallengeQuestion = { id: string; visualId: string; topic: string; question: string; options: string[]; correct: number; explanation: string }

export const MODULE_TWO_FINAL_CHALLENGE: ModuleTwoChallengeQuestion[] = [
  { id:'M2_FINAL_Q01', visualId:'M2_PRIORITY_RIGHT_01', topic:'Priorité de droite', question:'Aucun agent, feu ou signal de priorité ne règle ce carrefour. Une voiture arrive de ta droite. Que fais-tu ?', options:['Je passe avant elle','Je lui cède le passage','Je passe si je continue tout droit'], correct:1, explanation:'Lorsque la priorité de droite s’applique, tu cèdes le passage au conducteur venant de ta droite.' },
  { id:'M2_FINAL_Q02', visualId:'M2_PRIORITY_RIGHT_02', topic:'Priorité de droite', question:'Dans cette situation, quel conducteur doit te céder le passage ?', options:['Le conducteur placé à ma gauche','Le conducteur qui arrive à ma droite','Tous les conducteurs'], correct:0, explanation:'Tu te trouves à droite de l’autre conducteur : il doit te céder le passage.' },
  { id:'M2_FINAL_Q03', visualId:'M2_YIELD_01', topic:'STOP / Cédez', question:'Aucun véhicule ne t’empêche actuellement de t’engager. Que t’impose ce signal ?', options:['Un arrêt complet obligatoire dans tous les cas','Céder le passage et m’arrêter si nécessaire','La priorité sur les véhicules venant de gauche'], correct:1, explanation:'Le cédez le passage impose de céder ; l’arrêt est nécessaire seulement si la situation l’exige.' },
  { id:'M2_FINAL_Q04', visualId:'M2_STOP_01', topic:'STOP / Cédez', question:'La route transversale semble libre. Peux-tu franchir ce carrefour sans immobiliser ton véhicule ?', options:['Oui','Non','Oui si je roule au pas'], correct:1, explanation:'Non. Le STOP impose un arrêt complet avant l’engagement.' },
  { id:'M2_FINAL_Q05', visualId:'M2_PRIORITY_EXCEPTION_PARKING_01', topic:'Exceptions', question:'La voiture arrive physiquement de ta droite. Quel élément change ton raisonnement ?', options:['Elle sort d’un parking','Sa direction','Sa couleur'], correct:0, explanation:'Le piège est son origine : un véhicule qui sort d’un parking ne bénéficie pas ici de la priorité de droite.' },
  { id:'M2_FINAL_Q06', visualId:'M2_PRIORITY_EXCEPTION_DIRTROAD_01', topic:'Exceptions', question:'La voiture vient de droite mais débouche d’un chemin de terre. Peut-elle réclamer la priorité de droite dans cette situation ?', options:['Oui','Non','Seulement si elle continue tout droit'], correct:1, explanation:'Non. Le conducteur qui débouche d’un chemin de terre ne bénéficie pas ici de la priorité de droite.' },
  { id:'M2_FINAL_Q07', visualId:'M2_PRIORITY_ROAD_END_01', topic:'Voie prioritaire', question:'Que peux-tu conclure avec certitude en voyant ce signal ?', options:['Je dois céder à tous les véhicules','Le régime de voie prioritaire prend fin','La priorité de droite s’applique immédiatement'], correct:1, explanation:'Le panneau indique la fin de la voie prioritaire. Il faut ensuite analyser les règles du carrefour.' },
  { id:'M2_FINAL_Q08', visualId:'M2_NARROW_YIELD_01', topic:'Panneaux de priorité', question:'Tu es arrivé avant le véhicule venant en sens inverse. Qui doit néanmoins céder selon la signalisation ?', options:['Moi','L’autre véhicule','Celui qui est le plus proche du rétrécissement'], correct:0, explanation:'Le panneau B19 t’oblige à céder au trafic venant en sens inverse, même si tu arrives le premier.' },
  { id:'M2_FINAL_Q09', visualId:'M2_NARROW_PRIORITY_01', topic:'Panneaux de priorité', question:'Que dois-tu comprendre de la signalisation dans cette situation ?', options:['Je dois céder au véhicule venant en face','J’ai priorité de passage par rapport au véhicule venant en face','Les deux véhicules doivent s’arrêter'], correct:1, explanation:'Le panneau B21 indique une priorité de passage sur les conducteurs venant en sens opposé.' },
  { id:'M2_FINAL_Q10', visualId:'M2_PRIORITY_EXCEPTION_TRAM_01', topic:'Tram', question:'Le tram arrive de ta gauche. Quelle erreur dois-tu éviter ?', options:['Penser que je peux passer uniquement parce qu’il vient de gauche','Regarder les rails','Ralentir à l’approche du carrefour'], correct:0, explanation:'Un véhicule sur rails ne se traite pas comme une voiture ordinaire dans le raisonnement de priorité.' },
  { id:'M2_FINAL_Q11', visualId:'M2_PRIORITY_ROAD_01', topic:'Voie prioritaire', question:'Une voiture se présente à droite. Quel élément organise d’abord cette situation ?', options:['Le panneau de voie prioritaire','La couleur de la voiture','L’ordre d’arrivée'], correct:0, explanation:'La signalisation de voie prioritaire est la première règle à analyser.' },
  { id:'M2_FINAL_Q12', visualId:'M2_PRIORITY_EXCEPTION_DIRTROAD_02', topic:'Exceptions', question:'Les derniers mètres de la voie de droite sont goudronnés. Quel contrôle évite une mauvaise conclusion ?', options:['Observer l’origine complète de la voie','Regarder seulement les derniers mètres','Choisir selon la vitesse'], correct:0, explanation:'La voie débouche d’un chemin de terre : quelques mètres goudronnés ne changent pas automatiquement son origine.' },
  { id:'M2_FINAL_Q13', visualId:'M2_PRIORITY_RIGHT_03', topic:'Carrefours complexes', question:'Avant de déterminer un ordre de passage, quelle règle dois-tu analyser dans cette scène ?', options:['La priorité de droite','Le véhicule le plus proche','Le véhicule qui accélère le plus'], correct:0, explanation:'Sans agent, feux ni signalisation de priorité, la priorité de droite organise le carrefour.' },
  { id:'M2_FINAL_Q14', visualId:'M2_TRAM_BLOCKING_01', topic:'Tram', question:'La circulation est bloquée après le carrefour. Quelle décision évite de gêner le tram ?', options:['Attendre avant les rails si je ne peux pas les dégager','M’engager même si je reste sur les rails','Suivre la voiture devant sans vérifier'], correct:0, explanation:'Ne t’engage pas si tu risques de rester immobilisé sur les rails.' },
  { id:'M2_FINAL_Q15', visualId:'M2_STOP_TRAFFIC_01', topic:'Carrefours complexes', question:'Quelle règle dois-tu appliquer avant de chercher l’ordre complet de passage ?', options:['Le STOP : arrêt obligatoire, puis observation de la circulation','La priorité de droite uniquement','L’ordre d’arrivée des voitures'], correct:0, explanation:'Le STOP t’impose d’abord un arrêt. Ensuite, tu observes les autres usagers et tu cèdes si nécessaire.' },
]
