export type ModuleThreeChallengeQuestion = { id: string; visualId: string; topic: string; question: string; options: string[]; correct: number; explanation: string }

export const MODULE_THREE_FINAL_CHALLENGE: ModuleThreeChallengeQuestion[] = [
  {id:'M3_FINAL_Q01',visualId:'M3_SPEED_SIGN_50_01',topic:'Limitations',question:'Quelle vitesse maximale s’applique après ce panneau ?',options:['30 km/h','50 km/h','70 km/h'],correct:1,explanation:'Le panneau indique une limitation à 50 km/h. Elle s’applique au-delà du signal.'},
  {id:'M3_FINAL_Q02',visualId:'M3_SPEED_AGGLO_ENTRY_01',topic:'Limitations',question:'Que t’indique ce signal ?',options:['Le début d’une agglomération','Le début d’une autoroute','Une zone de stationnement'],correct:0,explanation:'Ce signal indique le début d’une agglomération.'},
  {id:'M3_FINAL_Q03',visualId:'M3_ZONE_CYCLING_01',topic:'Zones',question:'Quelle est la vitesse maximale dans cette zone ?',options:['20 km/h','30 km/h','50 km/h'],correct:1,explanation:'Dans une zone cyclable, la vitesse maximale est de 30 km/h.'},
  {id:'M3_FINAL_Q04',visualId:'M3_POSITION_RIGHT_01',topic:'Position',question:'Sur cette route à double sens, où dois-tu normalement te positionner ?',options:['À droite','Au milieu','À gauche'],correct:0,explanation:'En règle générale, tu dois tenir ta droite.'},
  {id:'M3_FINAL_Q05',visualId:'M3_ADAPT_CHILDREN_01',topic:'Adaptation de l’allure',question:'Ce panneau impose-t-il, à lui seul, une limitation à 30 km/h ?',options:['Oui','Non','Seulement en semaine'],correct:1,explanation:'Le panneau signale un endroit spécialement fréquenté par des enfants. Il ne crée pas à lui seul une limitation à 30 km/h.'},
  {id:'M3_FINAL_Q06',visualId:'M3_ADAPT_SLIPPERY_01',topic:'Adaptation de l’allure',question:'Tu respectes déjà la limitation, mais la chaussée est glissante. Quelle attitude est correcte ?',options:['Maintenir obligatoirement la vitesse maximale','Adapter mon allure aux conditions','Accélérer pour quitter rapidement la zone'],correct:1,explanation:'Respecter la limitation ne suffit pas toujours. Ton allure doit aussi être adaptée aux conditions rencontrées.'},
  {id:'M3_FINAL_Q07',visualId:'M3_POSITION_DIVIDED_01',topic:'Position',question:'Tu ne dépasses personne et la bande de droite est libre. Quel est le problème ?',options:['Ma vitesse','Ma position','Aucun'],correct:1,explanation:'Tu dois normalement tenir ta droite. Une vitesse correcte ne rend pas une mauvaise position correcte.'},
  {id:'M3_FINAL_Q08',visualId:'M3_POSITION_SHOULDER_01',topic:'Position',question:'La circulation ralentit et l’accotement est libre. Peux-tu l’emprunter pour avancer ?',options:['Oui','Non','Oui si tu roules lentement'],correct:1,explanation:'L’accotement n’est pas une bande normale que tu peux utiliser pour dépasser la file.'},
  {id:'M3_FINAL_Q09',visualId:'M3_LANES_BUS_01',topic:'Bandes',question:'Ta bande est encombrée mais la bande réservée aux bus est vide. Peux-tu l’emprunter pour avancer ?',options:['Oui','Non','Oui pendant quelques mètres'],correct:1,explanation:'Une bande réservée ne devient pas accessible simplement parce qu’elle est vide.'},
  {id:'M3_FINAL_Q10',visualId:'M3_LANES_RED_CROSS_01',topic:'Bandes',question:'La bande sous la croix rouge est vide. Peux-tu l’emprunter ?',options:['Oui','Non','Oui si les autres bandes sont encombrées'],correct:1,explanation:'Une croix rouge interdit de circuler sur la bande concernée.'},
  {id:'M3_FINAL_Q11',visualId:'M3_CROSSING_OBSTACLE_OWN_01',topic:'Croisement',question:'L’obstacle est de ton côté et un véhicule arrive en sens inverse. Que dois-tu faire ?',options:['Forcer le passage parce que l’obstacle est devant toi','Attendre si nécessaire avant de contourner l’obstacle','Emprunter l’accotement'],correct:1,explanation:'L’obstacle t’oblige à modifier ta trajectoire. Tu ne dois pas forcer le passage face au véhicule venant en sens inverse.'},
  {id:'M3_FINAL_Q12',visualId:'M2_NARROW_YIELD_01',topic:'Croisement',question:'Tu arrives avant le véhicule venant en face, mais ce panneau est placé de ton côté. Que dois-tu faire ?',options:['Passer parce que tu es arrivé en premier','Céder le passage','Passer si tu réduis ta vitesse'],correct:1,explanation:'Tu dois céder aux véhicules venant en sens inverse. Le fait d’arriver en premier ne supprime pas la signalisation.'},
  {id:'M3_FINAL_Q13',visualId:'M3_LANES_EVACUATION_01',topic:'Bandes',question:'Cette flèche orange est allumée au-dessus de ta bande. Que dois-tu faire ?',options:['Quitter cette bande','Continuer sur cette bande','M’arrêter immédiatement dans cette bande'],correct:0,explanation:'La flèche orange indique que tu dois quitter cette bande.'},
  {id:'M3_FINAL_Q14',visualId:'M3_CROSSING_DISTANCE_01',topic:'Croisement',question:'Tu croises ce véhicule sur cette chaussée étroite. Quelle erreur dois-tu éviter ?',options:['Passer trop près du véhicule venant en face','Tenir correctement ta droite','Observer l’espace disponible'],correct:0,explanation:'Lors du croisement, tu dois conserver une distance latérale suffisante.'},
  {id:'M3_FINAL_Q15',visualId:'M3_COMPLEX_TRAM_OBSTACLE_01',topic:'Situation particulière',question:'Un obstacle fixe empêche ici de passer le véhicule sur rails par la droite. De quel côté peux-tu passer ?',options:['Par la gauche','Uniquement par la droite','Par l’accotement'],correct:0,explanation:'Le croisement et le dépassement d’un véhicule sur rails se font normalement par la droite. Un obstacle fixe empêchant ce passage fait partie des exceptions enseignées.'},
]
