export type LearningScene = {
  id: string
  image?: string
  module: string
  topic: string
  difficulty: 'easy' | 'medium' | 'hard'
  tags: string[]
  description: string
  status?: 'ready' | 'needs-validation'
  requiredVisual?: string
  signId?: string
}

export const LEARNING_SCENES: LearningScene[] = [
  { id: 'M2_PRIORITY_RIGHT_01', image: '/learning/scenes/module-2/m2-priority-right-01.png', module: 'priorities-intersections', topic: 'priority-right', difficulty: 'easy', tags: ['intersection', 'priority-right', 'cars', 'unsignalised'], description: 'Carrefour belge sans signalisation avec un véhicule arrivant de la droite.' },
  { id: 'M2_PRIORITY_RIGHT_02', image: '/learning/scenes/module-2/m2-priority-right-02.png', module: 'priorities-intersections', topic: 'priority-right', difficulty: 'easy', tags: ['intersection', 'priority-right', 'cars', 'unsignalised'], description: 'Carrefour belge sans signalisation où le véhicule candidat se situe à droite de l’autre conducteur.' },
  { id: 'M2_PRIORITY_RIGHT_03', image: '/learning/scenes/module-2/m2-priority-right-03.png', module: 'priorities-intersections', topic: 'priority-right', difficulty: 'medium', tags: ['intersection', 'priority-right', 'multiple-cars', 'unsignalised'], description: 'Carrefour belge sans signalisation avec le véhicule candidat et deux véhicules venant des côtés.' },
  { id: 'M2_PRIORITY_EXCEPTION_PARKING_01', image: '/learning/scenes/module-2/m2-priority-exception-parking-01.png', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'easy', tags: ['priority', 'priority-right', 'parking', 'intersection'], description: 'Un véhicule sort d’un parking à droite du véhicule candidat.' },
  { id: 'M2_PRIORITY_EXCEPTION_PROPERTY_01', image: '/learning/scenes/module-2/m2-priority-exception-property-01.png', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'easy', tags: ['priority', 'priority-right', 'property', 'intersection'], description: 'Un véhicule sort d’une propriété riveraine à droite.' },
  { id: 'M2_PRIORITY_EXCEPTION_DIRTROAD_01', image: '/learning/scenes/module-2/m2-priority-exception-dirtroad-01.png', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'medium', tags: ['priority', 'priority-right', 'dirt-road', 'intersection'], description: 'Un véhicule débouche d’un chemin de terre à droite.' },
  { id: 'M2_PRIORITY_EXCEPTION_DIRTROAD_02', image: '/learning/scenes/module-2/m2-priority-exception-dirtroad-02.png', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'hard', tags: ['priority', 'priority-right', 'dirt-road', 'intersection'], description: 'Un chemin principalement non revêtu se termine par quelques mètres goudronnés avant le carrefour.' },
  { id: 'M2_PRIORITY_EXCEPTION_CYCLEPATH_01', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'hard', tags: ['priority', 'priority-right', 'cycle-path', 'intersection'], status: 'needs-validation', description: 'Situation à valider : une voiture arrive de droite et traverse une piste cyclable belge continue.', requiredVisual: 'Une vue conducteur avec la piste cyclable belge clairement séparée, son marquage, la signalisation applicable et la trajectoire exacte de la voiture et du cycliste.' },
  { id: 'M2_PRIORITY_EXCEPTION_CYCLELANE_01', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'hard', tags: ['priority', 'priority-right', 'cycle-lane', 'intersection'], status: 'needs-validation', description: 'Situation à valider : comparaison entre piste cyclable et bande cyclable suggérée.', requiredVisual: 'Deux vues juridiquement non ambiguës montrant distinctement une piste cyclable séparée et une bande cyclable suggérée sur la chaussée.' },
  { id: 'M2_PRIORITY_EXCEPTION_ONEWAY_01', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'hard', tags: ['priority', 'priority-right', 'one-way', 'intersection'], status: 'needs-validation', description: 'Situation à valider : un véhicule débouche à contresens depuis une rue à sens interdit.', requiredVisual: 'Une vue conducteur avec le panneau C1 orienté vers le candidat, la géométrie du carrefour et les éventuels panneaux additionnels entièrement lisibles.' },
  { id: 'M2_PRIORITY_EXCEPTION_ONEWAY_02', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'hard', tags: ['priority', 'priority-right', 'one-way', 'intersection'], status: 'needs-validation', description: 'Variante à valider : panneau additionnel autorisant une catégorie d’usagers.', requiredVisual: 'Même scène avec le panneau additionnel belge approprié et une trajectoire d’usager autorisée non ambiguë.' },
  { id: 'M2_PRIORITY_EXCEPTION_TRAM_01', image: '/learning/scenes/module-2/m2-priority-exception-tram-01.png', module: 'priorities-intersections', topic: 'priority-right-exceptions', difficulty: 'medium', tags: ['priority', 'priority-right', 'tram', 'intersection'], description: 'Un tram arrive de la gauche à un carrefour.' },
  { id: 'M2_YIELD_01', image: '/learning/scenes/module-2/m2-yield-01.png', module: 'priorities-intersections', topic: 'stop-yield', difficulty: 'easy', tags: ['priority', 'yield', 'intersection', 'priority-sign', 'traffic'], description: 'Arrivée à un cédez le passage avec un véhicule sur la voie abordée.' },
  { id: 'M2_STOP_01', image: '/learning/scenes/module-2/m2-stop-01.png', module: 'priorities-intersections', topic: 'stop-yield', difficulty: 'easy', tags: ['priority', 'stop', 'intersection', 'priority-sign'], description: 'Arrivée à un STOP avec ligne d’arrêt et voie transversale libre.' },
  { id: 'M2_YIELD_ADVANCE_01', image: '/learning/scenes/module-2/m2-yield-advance-01.png', module: 'priorities-intersections', topic: 'stop-yield', difficulty: 'medium', tags: ['priority', 'yield', 'intersection', 'advance-warning', 'priority-sign'], description: 'Panneau annonçant un cédez le passage plus loin.' },
  { id: 'M2_STOP_ADVANCE_01', image: '/learning/scenes/module-2/m2-stop-advance-01.png', module: 'priorities-intersections', topic: 'stop-yield', difficulty: 'medium', tags: ['priority', 'stop', 'intersection', 'advance-warning', 'priority-sign'], description: 'Panneau annonçant un STOP plus loin.' },
  { id: 'M2_STOP_TRAFFIC_01', image: '/learning/scenes/module-2/m2-stop-traffic-01.png', module: 'priorities-intersections', topic: 'stop-yield', difficulty: 'medium', tags: ['priority', 'stop', 'intersection', 'traffic', 'priority-sign'], description: 'STOP avec une circulation transversale qui impose d’attendre après l’arrêt.' },
  { id: 'M2_NARROW_YIELD_01', image: '/learning/scenes/module-2/m2-narrow-yield-01.png', module: 'priorities-intersections', topic: 'narrow-passage', difficulty: 'medium', tags: ['priority', 'B19', 'narrow-passage', 'exam-ready'], description: 'Panneau B19 imposant de céder le passage aux véhicules venant en sens inverse.' },
  { id: 'M2_NARROW_PRIORITY_01', image: '/learning/scenes/module-2/m2-narrow-priority-01.png', module: 'priorities-intersections', topic: 'narrow-passage', difficulty: 'medium', tags: ['priority', 'B21', 'narrow-passage', 'exam-ready'], description: 'Panneau B21 indiquant la priorité sur les véhicules venant en sens inverse.' },
  { id: 'M3_SPEED_OVERVIEW_01', image: '/learning/scenes/module-3/m3-speed-overview-01.png', module: 'speed-road-position', topic: 'speed-limits', difficulty: 'easy', tags: ['speed', 'road-sign', 'exam-ready'], description: 'Vue conducteur sur route belge avec signalisation et environnement à observer.' },
  { id: 'M3_SPEED_SIGN_50_01', image: '/learning/scenes/module-3/m3-speed-sign-50-01.png', module: 'speed-road-position', topic: 'speed-limits', difficulty: 'easy', tags: ['speed', 'speed-limit', 'road-sign', 'exam-ready'], description: 'Panneau C43 de limitation à 50 km/h sur une route belge.' },
  { id: 'M3_SPEED_AGGLO_ENTRY_01', image: '/learning/scenes/module-3/m3-speed-agglo-entry-01.png', module: 'speed-road-position', topic: 'speed-limits', difficulty: 'easy', tags: ['speed', 'built-up-area', 'road-sign', 'exam-ready'], description: 'Commencement d’agglomération avec signal F1a.' },
  { id: 'M3_SPEED_AGGLO_EXIT_01', image: '/learning/scenes/module-3/m3-speed-agglo-exit-01.png', module: 'speed-road-position', topic: 'speed-limits', difficulty: 'easy', tags: ['speed', 'built-up-area', 'road-sign', 'exam-ready'], description: 'Fin d’agglomération avec signal F1b.' },
  { id: 'M3_SPEED_ROAD_TYPES_01', image: '/learning/scenes/module-3/m3-speed-road-types-01.png', module: 'speed-road-position', topic: 'speed-limits', difficulty: 'medium', tags: ['speed', 'road-type', 'central-median', 'exam-ready'], description: 'Comparaison visuelle : route ordinaire, séparation par ligne blanche, puis séparation par berme centrale.' },
  { id: 'M3_SPEED_REGIONS_01', image: '/learning/scenes/module-3/m3-speed-regions-01.png', module: 'speed-road-position', topic: 'speed-limits', difficulty: 'easy', tags: ['speed', 'region', 'belgium'], description: 'Carte pédagogique des trois régions belges.' },
  { id: 'M3_SPEED_MOTORWAY_01', image: '/learning/scenes/module-3/m3-speed-motorway-01.png', module: 'speed-road-position', topic: 'speed-limits', difficulty: 'easy', tags: ['speed', 'motorway', 'road-sign', 'exam-ready'], description: 'Circulation sur autoroute belge avec signal autoroutier.' },
  { id: 'M3_SPEED_MOTORWAY_90_01', image: '/learning/scenes/module-3/m3-speed-motorway-90-01.png', module: 'speed-road-position', topic: 'speed-limits', difficulty: 'easy', tags: ['speed', 'motorway', 'speed-limit', 'road-sign', 'exam-ready'], description: 'Autoroute belge avec panneau de limitation à 90 km/h.' },
  { id: 'M3_ZONE_OVERVIEW_01', image: '/learning/scenes/module-3/m3-zone-overview-01.png', module: 'speed-road-position', topic: 'special-zones', difficulty: 'easy', tags: ['speed', 'zone', 'exam-ready'], description: 'Présentation de plusieurs environnements de zones particulières.' },
  { id: 'M3_ZONE_PEDESTRIAN_01', image: '/learning/scenes/module-3/m3-zone-pedestrian-01.png', module: 'speed-road-position', topic: 'special-zones', difficulty: 'easy', tags: ['speed', 'pedestrian-zone', 'road-sign', 'exam-ready'], description: 'Entrée d’une zone piétonne belge avec piétons.' },
  { id: 'M3_ZONE_PLAY_STREET_01', image: '/learning/scenes/module-3/m3-zone-play-street-01.png', module: 'speed-road-position', topic: 'special-zones', difficulty: 'easy', tags: ['speed', 'play-street', 'road-sign', 'exam-ready'], description: 'Rue belge réservée au jeu.' },
  { id: 'M3_ZONE_SCHOOL_STREET_01', image: '/learning/scenes/module-3/m3-zone-school-street-01.png', module: 'speed-road-position', topic: 'special-zones', difficulty: 'medium', tags: ['speed', 'school-street', 'road-sign', 'exam-ready'], description: 'Rue scolaire belge avec accès réglementé.' },
  { id: 'M3_ZONE_RESIDENTIAL_01', image: '/learning/scenes/module-3/m3-zone-residential-01.png', module: 'speed-road-position', topic: 'special-zones', difficulty: 'easy', tags: ['speed', 'residential-zone', 'road-sign', 'exam-ready'], description: 'Zone résidentielle ou de rencontre avec espace partagé.' },
  { id: 'M3_ZONE_CYCLING_01', image: '/learning/scenes/module-3/m3-zone-cycling-01.png', module: 'speed-road-position', topic: 'special-zones', difficulty: 'medium', tags: ['speed', 'bicycle-zone', 'road-sign', 'cyclist', 'exam-ready'], description: 'Entrée de zone cyclable belge avec cycliste devant la voiture.' },
  { id: 'M3_ZONE_SPECIAL_PATH_01', image: '/learning/scenes/module-3/m3-zone-special-path-01.png', module: 'speed-road-position', topic: 'special-zones', difficulty: 'medium', tags: ['speed', 'special-path', 'road-sign', 'exam-ready'], description: 'Chemin particulier réservé aux usagers indiqués par le signal.' },
  { id: 'M3_ZONE_RAISED_DEVICE_01', image: '/learning/scenes/module-3/m3-zone-raised-device-01.png', module: 'speed-road-position', topic: 'special-zones', difficulty: 'medium', tags: ['speed', 'raised-device', 'road-marking', 'exam-ready'], description: 'Dispositif surélevé sur une route belge.' },
  { id:'M3_ADAPT_SPEED_50_01',image:'/learning/scenes/module-3/m3-adapt-speed-50-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'easy',tags:['speed','children','road-sign','exam-ready'],description:'Limitation 50 avec enfants visibles près de la chaussée.' },
  { id:'M3_ADAPT_CHILDREN_01',image:'/learning/scenes/module-3/m3-adapt-children-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'easy',tags:['speed','children','danger-sign','exam-ready'],description:'Panneau enfants et enfants près de la chaussée.' },
  { id:'M3_ADAPT_SLIPPERY_01',image:'/learning/scenes/module-3/m3-adapt-slippery-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'easy',tags:['speed','slippery-road','danger-sign','exam-ready'],description:'Chaussée mouillée avec signal chaussée glissante.' },
  { id:'M3_ADAPT_CURVE_01',image:'/learning/scenes/module-3/m3-adapt-curve-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'medium',tags:['speed','curve','visibility','exam-ready'],description:'Virage à visibilité limitée.' },
  { id:'M3_ADAPT_PEDESTRIAN_01',image:'/learning/scenes/module-3/m3-adapt-pedestrian-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'easy',tags:['speed','pedestrian','crossing','exam-ready'],description:'Piéton s’engageant sur un passage pour piétons.' },
  { id:'M3_ADAPT_CYCLIST_01',image:'/learning/scenes/module-3/m3-adapt-cyclist-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'easy',tags:['speed','cyclist','exam-ready'],description:'Cycliste devant le candidat.' },
  { id:'M3_ADAPT_SCHOOL_BUS_01',image:'/learning/scenes/module-3/m3-adapt-school-bus-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'medium',tags:['speed','school-transport','exam-ready'],description:'Véhicule de transport scolaire à l’approche.' },
  { id:'M3_ADAPT_BUS_01',image:'/learning/scenes/module-3/m3-adapt-bus-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'medium',tags:['speed','bus','passengers','exam-ready'],description:'Bus à l’arrêt avec passagers visibles.' },
  { id:'M3_ADAPT_NARROWING_01',image:'/learning/scenes/module-3/m3-adapt-narrowing-01.png',module:'speed-road-position',topic:'speed-adaptation',difficulty:'medium',tags:['speed','narrowing','exam-ready'],description:'Chaussée se rétrécissant avec véhicule opposé.' },
  {id:'M3_POSITION_RIGHT_01',image:'/learning/scenes/module-3/m3-position-right-01.png',module:'speed-road-position',topic:'road-position',difficulty:'easy',tags:['position','two-way','exam-ready'],description:'Route à double sens : véhicule correctement placé à droite.'},
  {id:'M3_POSITION_DIVIDED_01',image:'/learning/scenes/module-3/m3-position-divided-01.png',module:'speed-road-position',topic:'road-position',difficulty:'easy',tags:['position','divided-road','lanes','exam-ready'],description:'Chaussées séparées par une berme centrale avec deux bandes dans le même sens.'},
  {id:'M3_POSITION_OBSTACLE_01',image:'/learning/scenes/module-3/m3-position-obstacle-01.png',module:'speed-road-position',topic:'road-position',difficulty:'medium',tags:['position','obstacle','exam-ready'],description:'Obstacle sur le côté droit de la voie.'},
  {id:'M3_POSITION_NARROW_01',image:'/learning/scenes/module-3/m3-position-narrow-01.png',module:'speed-road-position',topic:'road-position',difficulty:'medium',tags:['position','narrow-road','exam-ready'],description:'Route étroite à double sens avec véhicule opposé.'},
  {id:'M3_POSITION_SHOULDER_01',image:'/learning/scenes/module-3/m3-position-shoulder-01.png',module:'speed-road-position',topic:'road-position',difficulty:'easy',tags:['position','shoulder','exam-ready'],description:'Accotement distinct de la chaussée.'},
  {id:'M3_LANES_BASIC_01',image:'/learning/scenes/module-3/m3-lanes-basic-01.png',module:'speed-road-position',topic:'lanes-choice',difficulty:'easy',tags:['lanes','markings','right-hand-traffic','exam-ready'],description:'Deux bandes clairement séparées dans le sens du candidat.'},
  {id:'M3_LANES_BUS_01',image:'/learning/scenes/module-3/m3-lanes-bus-01.png',module:'speed-road-position',topic:'lanes-choice',difficulty:'easy',tags:['lanes','bus-lane','reserved-lane','exam-ready'],description:'Bande urbaine clairement réservée aux bus.'},
  {id:'M3_LANES_SSF_01',image:'/learning/scenes/module-3/m3-lanes-ssf-01.png',module:'speed-road-position',topic:'lanes-choice',difficulty:'medium',tags:['lanes','special-crossable-site','tram','exam-ready'],description:'Site spécial franchissable distinct d’une bande de circulation ordinaire.'},
  {id:'M3_LANES_DIRECTION_ARROWS_01',image:'/learning/scenes/module-3/m3-lanes-direction-arrows-01.png',module:'speed-road-position',topic:'lanes-choice',difficulty:'easy',tags:['lanes','direction-arrows','intersection','exam-ready'],description:'Deux bandes avec flèche gauche à gauche et flèche tout droit à droite.'},
  {id:'M3_LANES_RED_CROSS_01',image:'/learning/scenes/module-3/m3-lanes-red-cross-01.png',module:'speed-road-position',topic:'lanes-choice',difficulty:'medium',tags:['lanes','red-cross','lane-control','exam-ready'],description:'Signal lumineux : croix rouge au-dessus de la bande gauche et flèches vertes au-dessus des autres bandes.'},
  {id:'M3_LANES_EVACUATION_01',image:'/learning/scenes/module-3/m3-lanes-evacuation-01.png',module:'speed-road-position',topic:'lanes-choice',difficulty:'medium',tags:['lanes','evacuation-arrow','lane-control','exam-ready'],description:'Flèche lumineuse d’évacuation orientée vers la droite avec bande de destination ouverte.'},  {id:'M3_CROSSING_BASIC_01',image:'/learning/scenes/module-3/m3-crossing-basic-01.png',module:'speed-road-position',topic:'crossing',difficulty:'easy',tags:['crossing','two-way','right-hand-traffic','exam-ready'],description:'Croisement normal de deux voitures sur une route belge à double sens.'},
  {id:'M3_CROSSING_DISTANCE_01',image:'/learning/scenes/module-3/m3-crossing-distance-01.png',module:'speed-road-position',topic:'crossing',difficulty:'easy',tags:['crossing','lateral-distance','two-way','exam-ready'],description:'Croisement sur route étroite avec espace latéral suffisant visible.'},
  {id:'M3_CROSSING_OBSTACLE_OWN_01',image:'/learning/scenes/module-3/m3-crossing-obstacle-own-01.png',module:'speed-road-position',topic:'crossing',difficulty:'medium',tags:['crossing','obstacle','candidate-side','parked-cars','exam-ready'],description:'Véhicules stationnés du côté du candidat, nécessitant un déport vers le sens inverse.'},
  {id:'M3_CROSSING_OBSTACLE_OTHER_01',image:'/learning/scenes/module-3/m3-crossing-obstacle-other-01.png',module:'speed-road-position',topic:'crossing',difficulty:'medium',tags:['crossing','obstacle','opposite-side','parked-cars','exam-ready'],description:'Véhicules stationnés du côté du véhicule venant en sens inverse.'},  {id:'M3_COMPLEX_TRAM_OBSTACLE_01',image:'/learning/scenes/module-3/m3-complex-tram-obstacle-01.png',module:'speed-road-position',topic:'complex-situations',difficulty:'hard',tags:['tram','fixed-obstacle','left-passing-exception','exam-ready'],description:'Tram sur rails avec obstacle fixe empêchant le passage par la droite et passage disponible par la gauche.'},
  {id:'M4_OVERTAKE_OVERVIEW_01',image:'/learning/scenes/module-4/m4-overtake-overview-01.png',module:'manoeuvres-overtaking',topic:'overtaking-basics',difficulty:'easy',tags:['overtaking','same-direction','red-car','blue-car','exam-ready'],description:'Voiture rouge commençant à dépasser une voiture bleue circulant dans le même sens.'},
  {id:'M4_OVERTAKE_VS_CROSSING_01',image:'/learning/scenes/module-4/m4-overtake-vs-crossing-01.png',module:'manoeuvres-overtaking',topic:'overtaking-basics',difficulty:'easy',tags:['overtaking','crossing','comparison','exam-ready'],description:'Comparaison visuelle entre croisement en sens opposés et dépassement dans le même sens.'},
  {id:'M4_OVERTAKE_LEFT_01',image:'/learning/scenes/module-4/m4-overtake-overview-01.png',module:'manoeuvres-overtaking',topic:'overtaking-basics',difficulty:'easy',tags:['overtaking','left','exam-ready'],description:'Voiture rouge dépassant la voiture bleue par la gauche.'},
  {id:'M4_OVERTAKE_DISTANCE_COMPARE_01',image:'/learning/scenes/module-4/m4-overtake-distance-compare-01.png',module:'manoeuvres-overtaking',topic:'overtaking-basics',difficulty:'medium',tags:['overtaking','lateral-distance','comparison','exam-ready'],description:'Comparaison entre distance latérale insuffisante et suffisante pendant un dépassement.'},
  {id:'M4_OVERTAKEN_BEHAVIOR_01',image:'/learning/scenes/module-4/m4-overtaken-behavior-01.png',module:'manoeuvres-overtaking',topic:'overtaking-basics',difficulty:'medium',tags:['overtaking','passed-vehicle','right-position','exam-ready'],description:'Voiture bleue dépassée gardant une trajectoire prévisible à droite pendant le dépassement rouge.'},
  {id:'M4_OVERTAKEN_ACCELERATION_01',image:'/learning/scenes/module-4/m4-overtaken-acceleration-01.png',module:'manoeuvres-overtaking',topic:'overtaking-basics',difficulty:'medium',tags:['overtaking','passed-vehicle','acceleration','exam-ready'],description:'Voiture bleue accélérant pendant que la voiture rouge la dépasse.'},
  {id:'M4_OVERTAKE_WRONG_SIDE_01',image:'/learning/scenes/module-4/m4-overtake-wrong-side-01.png',module:'manoeuvres-overtaking',topic:'overtaking-basics',difficulty:'medium',tags:['overtaking','right-side','exam-ready'],description:'Voiture rouge tentant de dépasser la voiture bleue par la droite sur une route sans situation particulière.'},  {id:'M4_OVERTAKE_ANALYSIS_01',image:'/learning/scenes/module-4/m4-overtake-analysis-01.png',module:'manoeuvres-overtaking',topic:'overtaking-analysis',difficulty:'medium',tags:['overtaking','acceleration','same-direction','exam-ready'],description:'Voiture bleue accélérant pendant que la voiture rouge la dépasse correctement par la gauche.'},
  {id:'M4_OVERTAKE_ANALYSIS_02',image:'/learning/scenes/module-4/m4-overtake-analysis-02.png',module:'manoeuvres-overtaking',topic:'overtaking-analysis',difficulty:'medium',tags:['overtaking','left','insufficient-lateral-distance','exam-ready'],description:'Dépassement par la gauche avec espace latéral insuffisant.'},
  {id:'M4_OVERTAKE_ANALYSIS_03',image:'/learning/scenes/module-4/m4-overtake-analysis-03.png',module:'manoeuvres-overtaking',topic:'overtaking-analysis',difficulty:'medium',tags:['overtaking','passed-vehicle','left-deviation','exam-ready'],description:'Voiture bleue dépassée se déportant vers la gauche pendant la manœuvre.'},
  {id:'M4_OVERTAKE_ANALYSIS_04',image:'/learning/scenes/module-4/m4-overtake-analysis-04.png',module:'manoeuvres-overtaking',topic:'overtaking-analysis',difficulty:'medium',tags:['overtaking','left','insufficient-lateral-distance','exam-ready'],description:'Dépassement par la gauche où les véhicules sont trop proches latéralement.'},
  {id:'M4_OVERTAKE_ANALYSIS_05',image:'/learning/scenes/module-4/m4-overtaken-behavior-01.png',module:'manoeuvres-overtaking',topic:'overtaking-analysis',difficulty:'easy',tags:['overtaking','left','lateral-distance','passed-vehicle','exam-ready'],description:'Dépassement correct : voiture rouge à gauche, espace suffisant et voiture bleue prévisible à droite.'},  {id:'M4_SAFE_OVERTAKE_OVERVIEW_01',image:'/learning/scenes/module-4/m4-safe-overtake-overview-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'easy',tags:['overtaking','overview'],description:'Situation à analyser avant un dépassement.'},
  {id:'M4_OVERTAKE_ONCOMING_01',image:'/learning/scenes/module-4/m4-overtake-oncoming-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'medium',tags:['overtaking','oncoming-traffic'],description:'Véhicule venant en sens inverse empêchant un dépassement sûr.'},
  {id:'M4_OVERTAKE_REAR_CHECK_01',image:'/learning/scenes/module-4/m4-overtake-rear-check-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'medium',tags:['overtaking','rear-check'],description:'Véhicule derrière ayant déjà commencé son dépassement.'},
  {id:'M4_OVERTAKE_RETURN_SPACE_01',image:'/learning/scenes/module-4/m4-overtake-return-space-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'medium',tags:['overtaking','return-space'],description:'Espace de rabattement à analyser.'},
  {id:'M4_OVERTAKE_SEQUENCE_01',image:'/learning/scenes/module-4/m4-safe-overtake-overview-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'easy',tags:['overtaking','sequence'],description:'Contrôles avant déplacement latéral.'},
  {id:'M4_OVERTAKE_INDICATOR_01',image:'/learning/scenes/module-4/m4-safe-overtake-overview-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'easy',tags:['overtaking','indicator'],description:'Annonce des déplacements latéraux.'},
  {id:'M4_OVERTAKEN_ACCELERATION_RISK_01',image:'/learning/scenes/module-4/m4-overtake-analysis-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'medium',tags:['overtaking','acceleration'],description:'Véhicule dépassé accélérant pendant la manœuvre.'},
  {id:'M4_OVERTAKE_HIDDEN_ROAD_01',image:'/learning/scenes/module-4/m4-overtake-hidden-road-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'hard',tags:['overtaking','visibility'],description:'Partie de route insuffisamment visible.'},
  {id:'M4_OVERTAKE_MULTI_ANALYSIS_01',image:'/learning/scenes/module-4/m4-overtake-multi-analysis-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'hard',tags:['overtaking','rear-check'],description:'Scène à plusieurs informations avec dépassement engagé derrière.'},
  {id:'M4_OVERTAKE_DECISION_01',image:'/learning/scenes/module-4/m4-overtake-hidden-road-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'hard',tags:['overtaking','visibility','line'],description:'Ligne discontinue avec visibilité insuffisante à analyser.'},
  {id:'M4_OVERTAKE_FINAL_COMPLEX_01',image:'/learning/scenes/module-4/m4-overtake-final-complex-01.png',module:'manoeuvres-overtaking',topic:'safe-overtaking',difficulty:'hard',tags:['overtaking','full-analysis'],description:'Situation globale compatible avec un dépassement après tous les contrôles.'},  {id:'M4_FORBIDDEN_OVERTAKE_OVERVIEW_01',image:'/learning/scenes/module-4/m4-forbidden-overtake-overview-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'easy',tags:['overtaking','overview'],description:'Introduction aux situations où dépasser peut être interdit.'},
  {id:'M4_MARKING_MIXED_LINES_01',image:'/learning/scenes/module-4/m4-marking-mixed-lines-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'medium',tags:['overtaking','mixed-lines','markings'],description:'Double ligne : discontinue du côté du candidat et continue du côté opposé.'},
  {id:'M4_DASHED_NOT_PERMISSION_01',image:'/learning/scenes/module-4/m4-dashed-not-permission-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'medium',tags:['overtaking','dashed-line','visibility'],description:'Ligne discontinue avec sommet masquant la route.'},
  {id:'M4_FORBIDDEN_HILL_01',image:'/learning/scenes/module-4/m4-forbidden-hill-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','hill','visibility'],description:'Sommet de côte avec circulation opposée potentiellement cachée.'},
  {id:'M4_FORBIDDEN_CURVE_01',image:'/learning/scenes/module-4/m4-forbidden-curve-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','curve','visibility'],description:'Virage masqué malgré une ligne discontinue.'},
  {id:'M4_FORBIDDEN_INTERSECTION_01',image:'/learning/scenes/module-4/m4-forbidden-intersection-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','intersection','priority-right'],description:'Carrefour à priorité de droite à analyser avant tout dépassement.'},
  {id:'M4_LEVEL_CROSSING_COMPARE_01',image:'/learning/scenes/module-4/m4-level-crossing-compare-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','level-crossing'],description:'Configuration d’un passage à niveau à observer.'},
  {id:'M4_CROSSWALK_OVERTAKE_01',image:'/learning/scenes/module-4/m4-crosswalk-overtake-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'medium',tags:['overtaking','crosswalk','pedestrian'],description:'Voiture ralentissant devant un passage pour piétons.'},
  {id:'M4_RAISED_DEVICE_01',image:'/learning/scenes/module-4/m4-raised-device-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'medium',tags:['overtaking','raised-device','car'],description:'Dispositif surélevé avec voiture devant le candidat.'},
  {id:'M4_RAISED_DEVICE_CYCLIST_01',image:'/learning/scenes/module-4/m4-raised-device-cyclist-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','raised-device','cyclist'],description:'Dispositif surélevé avec cycliste devant le candidat.'},
  {id:'M4_BAD_VISIBILITY_CYCLIST_01',image:'/learning/scenes/module-4/m4-bad-visibility-cyclist-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','cyclist','visibility'],description:'Cycliste devant et visibilité insuffisante dans un virage.'},
  {id:'M4_OVERTAKE_SIGN_SIDECAR_01',image:'/learning/scenes/module-4/m4-overtake-sign-sidecar-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','sign','sidecar'],description:'Panneau d’interdiction de dépasser et motocyclette avec side-car.'},
  {id:'M4_TRUCK_OVERTAKE_SIGN_01',image:'/learning/scenes/module-4/m4-truck-overtake-sign-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','sign','heavy-goods'],description:'Signal spécifique aux véhicules de transport de choses lourds.'},
  {id:'M4_TRIPLE_OVERTAKE_01',image:'/learning/scenes/module-4/m4-triple-overtake-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','triple','two-way'],description:'Tentative de triplement sur chaussée à double sens.'},
  {id:'M4_FINAL_FORBIDDEN_ANALYSIS_01',image:'/learning/scenes/module-4/m4-final-forbidden-analysis-01.png',module:'manoeuvres-overtaking',topic:'forbidden-overtaking',difficulty:'hard',tags:['overtaking','crosswalk','analysis'],description:'Véhicule ralentissant à l’approche d’un passage pour piétons.'},  {id:'M4_OVERTAKE_SIGNS_OVERVIEW_01',image:'/learning/scenes/module-4/m4-overtake-sign-sidecar-01.png',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'easy',tags:['overtaking','C35','wheels'],description:'Signal C35 et véhicule à side-car.'},
  {id:'M4_OVERTAKE_SIGN_GENERAL_01',image:'/learning/signs/be-c35-no-overtaking.jpg',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'easy',tags:['C35','sign'],description:'Signal belge C35 d’interdiction générale de dépasser.'},
  {id:'M4_SIGN_CAR_01',image:'/learning/signs/be-c35-no-overtaking.jpg',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'medium',tags:['C35','car'],description:'Signal C35 à analyser avec une voiture dépassée.'},
  {id:'M4_SIGN_MOTORCYCLE_01',image:'/learning/scenes/module-4/m4-overtake-sign-sidecar-01.png',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'medium',tags:['C35','motorcycle'],description:'Signal C35 et motocyclette à analyser.'},
  {id:'M4_SIGN_BICYCLE_01',image:'/learning/scenes/module-4/m4-raised-device-cyclist-01.png',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'medium',tags:['C35','bicycle'],description:'Cycliste à analyser face au signal C35.'},
  {id:'M4_SIGN_SIDECAR_COMPARE_01',image:'/learning/scenes/module-4/m4-overtake-sign-sidecar-01.png',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'hard',tags:['C35','sidecar'],description:'Motocyclette avec side-car à trois roues.'},
  {id:'M4_SIGN_SIDECAR_SCENE_01',image:'/learning/scenes/module-4/m4-overtake-sign-sidecar-01.png',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'hard',tags:['C35','sidecar'],description:'Situation de dépassement d’une moto avec side-car.'},
  {id:'M4_OVERTAKE_SIGN_END_01',image:'/learning/signs/be-c37-end-no-overtaking.jpg',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'medium',tags:['C37','end-sign'],description:'Signal belge C37 de fin d’interdiction de dépasser.'},
  {id:'M4_OVERTAKE_SIGN_TRUCK_01',image:'/learning/signs/be-c39-heavy-goods-no-overtaking.jpg',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'medium',tags:['C39','heavy-goods'],description:'Signal belge C39 pour certains transports de choses.'},
  {id:'M4_TRUCK_SIGN_CAR_DRIVER_01',image:'/learning/signs/be-c39-heavy-goods-no-overtaking.jpg',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'hard',tags:['C39','car-driver'],description:'Signal C39 et conducteur de voiture particulière.'},
  {id:'M4_TRUCK_SIGN_WEIGHT_COMPARE_01',image:'/learning/signs/be-c39-heavy-goods-no-overtaking.jpg',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'hard',tags:['C39','MMA'],description:'MMA de 3 500 kg et de 3 501 kg à analyser.'},
  {id:'M4_TRUCK_SIGN_MOTORCYCLE_01',image:'/learning/signs/be-c39-heavy-goods-no-overtaking.jpg',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'hard',tags:['C39','motorcycle'],description:'Véhicule de transport concerné et moto solo.'},
  {id:'M4_SIGN_FINAL_ANALYSIS_01',image:'/learning/scenes/module-4/m4-overtake-sign-sidecar-01.png',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'hard',tags:['C39','sidecar','analysis'],description:'Analyse combinée du C39 et d’un side-car.'},
  {id:'M4_SIGN_CUMULATIVE_01',image:'/learning/scenes/module-4/m4-bad-visibility-cyclist-01.png',module:'manoeuvres-overtaking',topic:'overtaking-signs',difficulty:'hard',tags:['C35','cyclist','visibility'],description:'Cycliste et visibilité insuffisante à analyser.'},  {id:'M4_VULNERABLE_OVERVIEW_01',image:'/learning/scenes/module-4/m4-vulnerable-overview-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'easy',tags:['cyclist','distance'],description:'Dépassement d’un cycliste en environnement urbain avec distance pédagogique.'},
  {id:'M4_LATERAL_DISTANCE_COMPARE_01',image:'/learning/scenes/module-4/m4-lateral-distance-compare-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'easy',tags:['cyclist','distance'],description:'Distance latérale pédagogique à observer.'},
  {id:'M4_CYCLIST_URBAN_01',image:'/learning/scenes/module-4/m4-cyclist-urban-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'medium',tags:['cyclist','urban','1m'],description:'Cycliste dépassé en agglomération avec distance indiquée.'},
  {id:'M4_CYCLIST_OUTSIDE_01',image:'/learning/scenes/module-4/m4-cyclist-outside-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'medium',tags:['cyclist','outside','1m'],description:'Cycliste hors agglomération avec distance indiquée.'},
  {id:'M4_CYCLIST_NARROW_ROAD_01',image:'/learning/scenes/module-4/m4-cyclist-narrow-road-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'hard',tags:['cyclist','oncoming','1.5m'],description:'Cycliste, route étroite et véhicule opposé.'},
  {id:'M4_CYCLIST_CYCLEPATH_01',image:'/learning/scenes/module-4/m4-cyclist-cyclepath-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'hard',tags:['cyclist','cyclepath','1m'],description:'Cycliste sur piste cyclable parallèle hors agglomération.'},
  {id:'M4_PEDESTRIAN_OVERTAKE_01',image:'/learning/scenes/module-4/m4-pedestrian-overtake-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'medium',tags:['pedestrian','outside'],description:'Piéton sur la chaussée hors agglomération.'},
  {id:'M4_MOPED_OVERTAKE_01',image:'/learning/scenes/module-4/m4-moped-overtake-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'medium',tags:['moped','urban'],description:'Cyclomotoriste à dépasser en agglomération.'},
  {id:'M4_CYCLING_ZONE_01',image:'/learning/scenes/module-4/m4-cycling-zone-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'hard',tags:['cyclist','cycling-zone','F111'],description:'Situation de zone cyclable avec cycliste devant.',signId:'F111'},
  {id:'M4_CYCLEPATH_VS_CYCLINGZONE_01',image:'/learning/scenes/module-4/m4-cyclepath-vs-cyclingzone-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'hard',tags:['cyclist','cyclepath','cycling-zone'],description:'Comparaison entre piste cyclable et zone cyclable.'},
  {id:'M4_CYCLIST_COMPLEX_01',image:'/learning/scenes/module-4/m4-cyclist-complex-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'hard',tags:['cyclist','oncoming','1.5m'],description:'Distance disponible mais véhicule opposé proche.'},
  {id:'M4_CYCLIST_FINAL_ANALYSIS_01',image:'/learning/scenes/module-4/m4-cyclist-final-analysis-01.png',module:'manoeuvres-overtaking',topic:'vulnerable-road-users',difficulty:'hard',tags:['cyclist','oncoming','analysis'],description:'Analyse finale : distance latérale et circulation opposée.'},  {id:'M3_POSITION_ONEWAY_01',image:'/learning/scenes/module-3/m3-position-oneway-01.png',module:'speed-road-position',topic:'road-position',difficulty:'easy',tags:['position','one-way','exam-ready'],description:'Rue belge à sens unique.'},
  { id: 'M4_TRAM_RULE_COMPARE_01', image: '/learning/scenes/module-4/m4-tram-rule-compare-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'easy', tags: ['tram','rails','right'], description: 'Règle des véhicules sur rails.' },
  { id: 'M4_TRAM_RIGHT_OVERTAKE_01', image: '/learning/scenes/module-4/m4-tram-right-overtake-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'easy', tags: ['tram','rails','right'], description: 'Tram avec passage libre à droite.' },
  { id: 'M4_TRAM_RIGHT_TOO_NARROW_01', image: '/learning/scenes/module-4/m4-tram-right-too-narrow-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'medium', tags: ['tram','rails','narrow'], description: 'Passage à droite trop étroit.' },
  { id: 'M4_TRAM_RIGHT_BLOCKED_CAR_01', image: '/learning/scenes/module-4/m4-tram-right-blocked-car-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'medium', tags: ['tram','rails','parked-car'], description: 'Véhicule immobilisé à droite.' },
  { id: 'M4_TRAM_FIXED_OBSTACLE_01', image: '/learning/scenes/module-4/m4-tram-fixed-obstacle-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'medium', tags: ['tram','rails','fixed-obstacle'], description: 'Obstacle fixe à droite.' },
  { id: 'M4_TRAM_LEFT_ONCOMING_01', image: '/learning/scenes/module-4/m4-tram-left-oncoming-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'hard', tags: ['tram','rails','oncoming'], description: 'Trafic opposé à gauche.' },
  { id: 'M4_TRAM_LEFT_VISIBILITY_01', image: '/learning/scenes/module-4/m4-tram-left-visibility-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'hard', tags: ['tram','rails','visibility'], description: 'Visibilité insuffisante à gauche.' },
  { id: 'M4_CAR_VS_TRAM_OVERTAKE_01', image: '/learning/scenes/module-4/m4-car-vs-tram-overtake-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'medium', tags: ['tram','car','comparison'], description: 'Règles comparées pour voiture et tram.' },
  { id: 'M4_TRAM_FALSE_EXCEPTION_01', image: '/learning/scenes/module-4/m4-tram-false-exception-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'medium', tags: ['tram','rails','right'], description: 'Passage à droite disponible.' },
  { id: 'M4_TRAM_COMPLEX_01', image: '/learning/scenes/module-4/m4-tram-complex-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'hard', tags: ['tram','rails','obstacle','oncoming'], description: 'Obstacle et trafic opposé.' },
  { id: 'M4_TRAM_FINAL_ANALYSIS_01', image: '/learning/scenes/module-4/m4-tram-final-analysis-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'hard', tags: ['tram','rails','parked-car','oncoming'], description: 'Analyse finale avec voiture stationnée.' },
  { id: 'M4_TRAM_CHARACTERISTICS_01', image: '/learning/scenes/module-4/m4-tram-characteristics-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'easy', tags: ['tram','rails','trajectory'], description: 'Tram intégré dans une rue belge et trajectoire guidée par les rails.' },
  { id: 'M4_TRAM_PRIORITY_01', image: '/learning/scenes/module-4/m4-tram-priority-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'medium', tags: ['tram','rails','intersection','priority'], description: 'Intersection belge avec tram et voiture, sans instruction lumineuse explicite.' },
  { id: 'M4_TRAM_IN_ROAD_01', image: '/learning/scenes/module-4/m4-tram-in-road-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'easy', tags: ['tram','rails','roadway'], description: 'Rails intégrés à la chaussée autour du trafic.' },
  { id: 'M4_TRAM_EXCEPTIONS_01', image: '/learning/scenes/module-4/m4-tram-exceptions-01.png', module: 'manoeuvres-overtaking', topic: 'tram-rails', difficulty: 'medium', tags: ['tram','rails','narrow','parked-car','fixed-obstacle'], description: 'Contraintes physiques empêchant le passage à droite du tram.' },
  { id: 'M4_MANEUVER_OVERVIEW_01', image: '/learning/scenes/module-4/m4-maneuver-overview-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'easy', tags: ['manoeuvre','overview'], description: 'Vue globale d’une situation de manœuvre.' },
  { id: 'M4_MANEUVER_CHECK_SEQUENCE_01', image: '/learning/scenes/module-4/m4-maneuver-check-sequence-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'easy', tags: ['manoeuvre','checks'], description: 'Contrôles avant mouvement.' },
  { id: 'M4_TURN_RIGHT_LEFT_COMPARE_01', image: '/learning/scenes/module-4/m4-turn-right-left-compare-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'easy', tags: ['turn','comparison'], description: 'Trajectoires de virage comparées.' },
  { id: 'M4_LEFT_TURN_ONCOMING_01', image: '/learning/scenes/module-4/m4-left-turn-oncoming-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'medium', tags: ['turn','oncoming'], description: 'Virage à gauche avec trafic opposé.' },
  { id: 'M4_TURN_CYCLIST_01', image: '/learning/scenes/module-4/m4-turn-cyclist-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'medium', tags: ['turn','cyclist'], description: 'Virage avec cycliste.' },
  { id: 'M4_TURN_PEDESTRIAN_01', image: '/learning/scenes/module-4/m4-turn-pedestrian-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'medium', tags: ['turn','pedestrian'], description: 'Virage avec piéton.' },
  { id: 'M4_INDICATOR_NOT_PRIORITY_01', image: '/learning/scenes/module-4/m4-indicator-not-priority-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'medium', tags: ['indicator','priority'], description: 'Clignotant sans priorité.' },
  { id: 'M4_LANE_CHANGE_COMPLEX_01', image: '/learning/scenes/module-4/m4-lane-change-complex-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'medium', tags: ['lane-change','vehicle'], description: 'Changement de bande.' },
  { id: 'M4_MANEUVER_CYCLIST_COMPLEX_01', image: '/learning/scenes/module-4/m4-maneuver-cyclist-complex-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'hard', tags: ['manoeuvre','cyclist','complex'], description: 'Situation complexe avec cycliste.' },
  { id: 'M4_MANEUVER_LEFT_COMPLEX_01', image: '/learning/scenes/module-4/m4-maneuver-left-complex-01.png', module: 'manoeuvres-overtaking', topic: 'complex-manoeuvres', difficulty: 'hard', tags: ['manoeuvre','oncoming','pedestrian','complex'], description: 'Situation complexe finale.' },]

export const getLearningScene = (id?: string) => LEARNING_SCENES.find((scene) => scene.id === id)


























