import type { Question } from '@/domain/quiz'

export const SIGNALISATION_PRIORITES_QUESTIONS: Question[] = [
  {
    id: 'sp11-q1',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Il pleut fort en plein après-midi, visibilité 150 m. Devez-vous allumer vos feux ?', nl: 'Het regent hard in de namiddag, zicht 150 m. Moet u uw lichten aansteken?' },
    options: [
      { id: 'a', text: { fr: 'Non, il fait jour', nl: 'Nee, het is dag' }, correct: false },
      { id: 'b', text: { fr: 'Oui, la visibilité est sous 200 m', nl: 'Ja, het zicht is onder 200 m' }, correct: true },
    ],
    explanation: { fr: "Dès que la visibilité descend sous 200 m — même en plein jour — les feux doivent être allumés.", nl: 'Zodra het zicht onder 200 m zakt — ook overdag — moeten de lichten aan.' },
    factIds: ['sp11-feux-quand'],
    difficulty: 'moyen',
  },
  {
    id: 'sp11-q2',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Pouvez-vous allumer les warnings pour vous garer un instant en double file ?', nl: 'Mag u de alarmlichten aansteken om even dubbel te parkeren?' },
    options: [
      { id: 'a', text: { fr: 'Oui, c’est courant', nl: 'Ja, dat is gebruikelijk' }, correct: false },
      { id: 'b', text: { fr: 'Non, c’est une infraction supplémentaire', nl: 'Nee, dat is een bijkomende overtreding' }, correct: true },
    ],
    explanation: { fr: "Les warnings ne sont réservés qu'aux pannes et aux dangers imminents — les utiliser pour excuser un stationnement gênant est une infraction en soi.", nl: 'Alarmlichten zijn enkel voorbehouden voor pech en dreigend gevaar — ze gebruiken om hinderlijk parkeren te excuseren is op zich een overtreding.' },
    factIds: ['sp11-warnings'],
    difficulty: 'facile',
  },
  {
    id: 'sp18-q1',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Le feu est vert mais le carrefour est complètement encombré. Devez-vous vous engager ?', nl: 'Het licht is groen maar het kruispunt is helemaal verstopt. Moet u oprijden?' },
    options: [
      { id: 'a', text: { fr: 'Oui, le feu vert m’y oblige', nl: 'Ja, het groene licht verplicht mij' }, correct: false },
      { id: 'b', text: { fr: 'Non, il faut attendre que ça se dégage', nl: 'Nee, ik moet wachten tot het vrijkomt' }, correct: true },
    ],
    explanation: { fr: "Un feu vert n'autorise à s'engager que si le carrefour est réellement dégagé — sinon, il faut attendre.", nl: 'Een groen licht laat enkel oprijden toe als het kruispunt écht vrij is — anders moet je wachten.' },
    factIds: ['sp18-feu-rouge-vert'],
    difficulty: 'moyen',
  },
  {
    id: 'sp18-q2',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Une flèche verte est allumée à côté d’un feu rouge. Êtes-vous prioritaire dans cette direction ?', nl: 'Een groene pijl brandt naast een rood licht. Heeft u voorrang in die richting?' },
    options: [
      { id: 'a', text: { fr: 'Oui, totalement', nl: 'Ja, volledig' }, correct: false },
      { id: 'b', text: { fr: 'Non, je dois céder le passage à tous les autres usagers', nl: 'Nee, ik moet voorrang verlenen aan alle andere weggebruikers' }, correct: true },
    ],
    explanation: { fr: "La flèche verte autorise à avancer dans cette direction, mais en cédant le passage à tous les usagers venant des autres directions.", nl: 'De groene pijl staat toe in die richting te rijden, maar met voorrang aan alle weggebruikers uit andere richtingen.' },
    factIds: ['sp18-fleche-verte-rouge'],
    difficulty: 'difficile',
  },
  {
    id: 'sp19-q1',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Sur une voie prioritaire, pouvez-vous dépasser par la gauche dans un carrefour ?', nl: 'Mag u op een voorrangsweg links inhalen in een kruispunt?' },
    options: [
      { id: 'a', text: { fr: 'Oui, si c’est sûr', nl: 'Ja, als het veilig kan' }, correct: true },
      { id: 'b', text: { fr: 'Non, jamais dans un carrefour', nl: 'Nee, nooit in een kruispunt' }, correct: false },
    ],
    explanation: { fr: "Sur une voie prioritaire, le dépassement par la gauche reste possible dans un carrefour si la manœuvre peut se faire en toute sécurité.", nl: 'Op een voorrangsweg blijft links inhalen mogelijk in een kruispunt als de manoeuvre veilig kan gebeuren.' },
    factIds: ['sp19-voie-prioritaire'],
    difficulty: 'moyen',
  },
  {
    id: 'sp19-q2',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Devant un signal STOP, la voie semble parfaitement libre. Devez-vous quand même vous arrêter ?', nl: 'Voor een STOP-bord lijkt de weg helemaal vrij. Moet u toch stoppen?' },
    options: [
      { id: 'a', text: { fr: 'Non, ce n’est pas utile', nl: 'Nee, dat is niet nodig' }, correct: false },
      { id: 'b', text: { fr: 'Oui, l’arrêt est toujours obligatoire', nl: 'Ja, stoppen is altijd verplicht' }, correct: true },
    ],
    explanation: { fr: "Contrairement au triangle sur pointe, le STOP impose un arrêt total, même si aucun conducteur n'arrive des directions prioritaires.", nl: 'In tegenstelling tot de driehoek op de punt verplicht de STOP een volledige stop, ook al komt er niemand uit de voorrangsrichtingen.' },
    factIds: ['sp19-triangle-stop'],
    difficulty: 'moyen',
  },
  {
    id: 'sp20-q1',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Un conducteur vient de droite mais ralentit fortement. Perd-il sa priorité ?', nl: 'Een bestuurder komt van rechts maar vertraagt sterk. Verliest hij zijn voorrang?' },
    options: [
      { id: 'a', text: { fr: 'Oui, je peux passer en premier', nl: 'Ja, ik mag eerst gaan' }, correct: false },
      { id: 'b', text: { fr: 'Non, il conserve sa priorité', nl: 'Nee, hij behoudt zijn voorrang' }, correct: true },
    ],
    explanation: { fr: "Ralentir ou s'arrêter ne fait pas perdre la priorité de droite : ce conducteur peut toujours s'engager le premier.", nl: 'Vertragen of stoppen doet de voorrang van rechts niet verliezen: die bestuurder mag nog steeds eerst vertrekken.' },
    factIds: ['sp20-regle-generale'],
    difficulty: 'facile',
  },
  {
    id: 'sp20-q2',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Vous quittez un parking privé pour rejoindre la chaussée. Avez-vous la priorité de droite ?', nl: 'U verlaat een privéparking om de rijbaan op te rijden. Heeft u voorrang van rechts?' },
    options: [
      { id: 'a', text: { fr: 'Oui, comme partout', nl: 'Ja, zoals overal' }, correct: false },
      { id: 'b', text: { fr: 'Non, je dois céder le passage à tous', nl: 'Nee, ik moet iedereen voorrang verlenen' }, correct: true },
    ],
    explanation: { fr: "La priorité de droite ne s'applique pas en quittant un accès privé ou une place de stationnement : c'est une manœuvre, tu cèdes toujours le passage.", nl: 'De voorrang van rechts geldt niet bij het verlaten van een privéoprit of parkeerplaats: dit is een manoeuvre, je verleent altijd voorrang.' },
    factIds: ['sp20-exceptions'],
    difficulty: 'moyen',
  },
  {
    id: 'sp23-q1',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Un cycliste peut-il franchir un signal de sens interdit classique ?', nl: 'Mag een fietser een klassiek verbodsbord voor verboden richting oversteken?' },
    options: [
      { id: 'a', text: { fr: 'Oui, les vélos ne sont pas concernés', nl: 'Ja, fietsen zijn niet betrokken' }, correct: false },
      { id: 'b', text: { fr: 'Non, sauf panneau additionnel qui l’autorise', nl: 'Nee, tenzij een onderbord dit toelaat' }, correct: true },
    ],
    explanation: { fr: "Le sens interdit s'applique à tous les conducteurs, cyclistes compris, sauf exception explicite par panneau additionnel.", nl: 'De verboden richting geldt voor alle bestuurders, ook fietsers, behalve uitdrukkelijke uitzondering via onderbord.' },
    factIds: ['sp23-sens-interdit-simple'],
    difficulty: 'facile',
  },
  {
    id: 'sp23-q2',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Vous passez votre examen pratique dans une rue « excepté circulation locale ». Pouvez-vous y entrer ?', nl: 'U rijdt uw praktijkexamen in een straat "uitgezonderd plaatselijk verkeer". Mag u er binnenrijden?' },
    options: [
      { id: 'a', text: { fr: 'Oui, l’examinateur compte comme circulation locale', nl: 'Ja, de examinator telt als plaatselijk verkeer' }, correct: false },
      { id: 'b', text: { fr: 'Non, jamais lors d’un examen pratique', nl: 'Nee, nooit tijdens een praktijkexamen' }, correct: true },
    ],
    explanation: { fr: "Un candidat à l'examen pratique n'entre jamais dans une rue « excepté circulation locale », quelle que soit la raison invoquée.", nl: 'Een examenkandidaat rijdt nooit een straat "uitgezonderd plaatselijk verkeer" binnen, om welke reden dan ook.' },
    factIds: ['sp23-sens-interdit-double'],
    difficulty: 'moyen',
  },
  {
    id: 'sp24-q1',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Un rond bleu avec une flèche vers le haut, sans autre indication : que devez-vous faire ?', nl: 'Een blauwe cirkel met pijl naar boven, zonder verdere aanduiding: wat moet u doen?' },
    options: [
      { id: 'a', text: { fr: 'Je peux choisir ma direction', nl: 'Ik mag zelf mijn richting kiezen' }, correct: false },
      { id: 'b', text: { fr: 'Je dois obligatoirement continuer tout droit', nl: 'Ik moet verplicht rechtdoor rijden' }, correct: true },
    ],
    explanation: { fr: "Un rond bleu à flèche est un signal d'obligation : il impose réellement de suivre la direction indiquée.", nl: 'Een blauwe cirkel met pijl is een gebodsbord: het legt écht de aangeduide richting op.' },
    factIds: ['sp24-obligation-vs-indication'],
    difficulty: 'moyen',
  },
  {
    id: 'sp24-q2',
    themeSlug: 'signalisation-priorites',
    region: 'BE',
    prompt: { fr: 'Pouvez-vous circuler sur un îlot directionnel peint au sol s’il est large ?', nl: 'Mag u op een geschilderd verkeerseiland rijden als het breed is?' },
    options: [
      { id: 'a', text: { fr: 'Oui, s’il est assez large', nl: 'Ja, als het breed genoeg is' }, correct: false },
      { id: 'b', text: { fr: 'Non, jamais, il faut le contourner', nl: 'Nee, nooit, u moet het omzeilen' }, correct: true },
    ],
    explanation: { fr: "Un îlot directionnel, peint ou construit, ne se traverse jamais : il se contourne toujours par la droite.", nl: 'Een verkeerseiland, geschilderd of aangelegd, wordt nooit overgestoken: het wordt altijd langs rechts omzeild.' },
    factIds: ['sp24-ilot'],
    difficulty: 'facile',
  },
]
