import type { Question } from '@/domain/quiz'

export const SECURITE_COMPORTEMENT_QUESTIONS: Question[] = [
  {
    id: 'sc28-q1',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Un passager (pas le conducteur) peut-il être soumis à un contrôle d’alcoolémie ?', nl: 'Kan een passagier (niet de bestuurder) aan een ademtest worden onderworpen?' },
    options: [
      { id: 'a', text: { fr: 'Non, seuls ceux qui conduisent ou s’apprêtent à conduire le peuvent', nl: 'Nee, enkel wie rijdt of op het punt staat te rijden' }, correct: true },
      { id: 'b', text: { fr: 'Oui, n’importe quel occupant du véhicule', nl: 'Ja, elke inzittende van het voertuig' }, correct: false },
    ],
    explanation: { fr: "Seule la personne qui conduit, s'apprête à conduire, ou est l'auteur présumé d'un accident peut être contrôlée — pas un simple passager.", nl: 'Enkel wie rijdt, op het punt staat te rijden, of vermoedelijke veroorzaker van een ongeval is, kan gecontroleerd worden — niet een gewone passagier.' },
    factIds: ['sc28-qui-controle'],
    difficulty: 'facile',
  },
  {
    id: 'sc28-q2',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Que signifie un résultat « A » au test d’haleine ?', nl: 'Wat betekent een resultaat "A" bij de ademtest?' },
    options: [
      { id: 'a', text: { fr: 'Alarme : une analyse de l’haleine suit', nl: 'Alarm: een ademanalyse volgt' }, correct: true },
      { id: 'b', text: { fr: 'Le conducteur peut repartir immédiatement', nl: 'De bestuurder mag onmiddellijk verder rijden' }, correct: false },
    ],
    explanation: { fr: "« A » (alarme, 0,22 à 0,35 mg/l) déclenche, comme « P », une analyse de l'haleine pour un résultat précis.", nl: '"A" (alarm, 0,22 tot 0,35 mg/l) leidt, net als "P", tot een ademanalyse voor een precies resultaat.' },
    factIds: ['sc28-test-haleine'],
    difficulty: 'facile',
  },
  {
    id: 'sc28-q3',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'À partir de quel taux le retrait immédiat du permis (6h légales, 15 jours en pratique) s’applique-t-il ?', nl: 'Vanaf welk gehalte geldt de onmiddellijke intrekking van het rijbewijs (wettelijk 6u, in de praktijk 15 dagen)?' },
    options: [
      { id: 'a', text: { fr: '0,35 mg/l d’air alvéolaire', nl: '0,35 mg/l alveolaire lucht' }, correct: true },
      { id: 'b', text: { fr: '0,22 mg/l d’air alvéolaire', nl: '0,22 mg/l alveolaire lucht' }, correct: false },
    ],
    explanation: { fr: "0,35 mg/l est le seuil légal de retrait (6h), mais en pratique les parquets retirent le permis 15 jours — c'est devenu la norme actuelle.", nl: '0,35 mg/l is de wettelijke drempel voor intrekking (6u), maar in de praktijk trekt het parket het rijbewijs 15 dagen in — dat is de huidige norm geworden.' },
    factIds: ['sc28-analyse-sanctions'],
    difficulty: 'moyen',
  },
  {
    id: 'sc28-q4',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'À partir de quel taux l’éthylotest antidémarrage devient-il obligatoire (sauf décision motivée contraire) ?', nl: 'Vanaf welk gehalte wordt het alcoholslot verplicht (behoudens andersluidende gemotiveerde beslissing)?' },
    options: [
      { id: 'a', text: { fr: '1,8 ‰', nl: '1,8 ‰' }, correct: true },
      { id: 'b', text: { fr: '0,8 ‰', nl: '0,8 ‰' }, correct: false },
    ],
    explanation: { fr: "Un juge PEUT imposer l'antidémarrage dès 0,8 ‰, mais il devient obligatoire à partir de 1,8 ‰ (sauf décision motivée contraire).", nl: 'Een rechter KAN het alcoholslot opleggen vanaf 0,8 ‰, maar het wordt verplicht vanaf 1,8 ‰ (behoudens andersluidende gemotiveerde beslissing).' },
    factIds: ['sc28-antidemarrage'],
    difficulty: 'difficile',
  },
  {
    id: 'sc28-q5',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Un test salivaire de dépistage de drogue peut-il être imposé sans raison particulière, hors accident ?', nl: 'Kan een speekseltest voor drugs worden opgelegd zonder bijzondere reden, buiten een ongeval?' },
    options: [
      { id: 'a', text: { fr: 'Non, il faut un soupçon objectif', nl: 'Nee, er moet een objectief vermoeden zijn' }, correct: true },
      { id: 'b', text: { fr: 'Oui, à tout moment et sans motif', nl: 'Ja, op elk moment en zonder reden' }, correct: false },
    ],
    explanation: { fr: "Le test salivaire n'est imposé que sur soupçon objectif de drogue, ou automatiquement en cas d'accident.", nl: 'De speekseltest wordt enkel opgelegd bij objectief vermoeden van drugsgebruik, of automatisch bij een ongeval.' },
    factIds: ['sc28-drogues'],
    difficulty: 'moyen',
  },
  {
    id: 'sc29-q1',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'À quelle distance place-t-on le triangle de danger sur autoroute ?', nl: 'Op welke afstand plaatst u de gevarendriehoek op de autosnelweg?' },
    options: [
      { id: 'a', text: { fr: '100 mètres', nl: '100 meter' }, correct: true },
      { id: 'b', text: { fr: '30 mètres', nl: '30 meter' }, correct: false },
    ],
    explanation: { fr: "30 m suffisent sur route ordinaire, mais il faut 100 m sur autoroute, où les vitesses sont bien plus élevées.", nl: '30 m volstaat op een gewone weg, maar op de autosnelweg is 100 m nodig, waar de snelheden veel hoger liggen.' },
    factIds: ['sc29-sans-blesses'],
    difficulty: 'facile',
  },
  {
    id: 'sc29-q2',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Une fois le constat européen d’accident signé par les deux parties, peut-on encore le modifier ?', nl: 'Kan het Europees aanrijdingsformulier nog worden gewijzigd nadat beide partijen het hebben ondertekend?' },
    options: [
      { id: 'a', text: { fr: 'Non, plus rien ne peut y être modifié', nl: 'Nee, er kan niets meer aan gewijzigd worden' }, correct: true },
      { id: 'b', text: { fr: 'Oui, tant que l’assurance n’a pas reçu le document', nl: 'Ja, zolang de verzekering het document nog niet ontvangen heeft' }, correct: false },
    ],
    explanation: { fr: "La face avant, une fois remplie et signée par les deux parties, devient définitive — c'est pourquoi il faut la relire avant de signer.", nl: 'De voorzijde is, eens ingevuld en door beide partijen ondertekend, definitief — daarom moet u ze herlezen vóór u tekent.' },
    factIds: ['sc29-constat'],
    difficulty: 'moyen',
  },
  {
    id: 'sc29-q3',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'En cas d’accident avec blessés, la police doit-elle systématiquement intervenir ?', nl: 'Moet de politie bij een ongeval met gewonden altijd tussenkomen?' },
    options: [
      { id: 'a', text: { fr: 'Oui, toujours', nl: 'Ja, altijd' }, correct: true },
      { id: 'b', text: { fr: 'Non, seulement si les parties ne s’entendent pas', nl: 'Nee, enkel als de partijen het oneens zijn' }, correct: false },
    ],
    explanation: { fr: "Contrairement à un accident matériel sans blessé, la présence de blessés impose toujours l'intervention de la police.", nl: 'In tegenstelling tot een louter materieel ongeval, vereist de aanwezigheid van gewonden altijd de tussenkomst van de politie.' },
    factIds: ['sc29-avec-blesses'],
    difficulty: 'facile',
  },
  {
    id: 'sc29-q4',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Faut-il retirer le casque d’un motard blessé inconscient au sol ?', nl: 'Moet u de helm van een bewusteloze gewonde motorrijder afzetten?' },
    options: [
      { id: 'a', text: { fr: 'Non, sauf s’il a des difficultés respiratoires', nl: 'Nee, tenzij hij ademhalingsproblemen heeft' }, correct: true },
      { id: 'b', text: { fr: 'Oui, systématiquement, pour l’identifier', nl: 'Ja, altijd, om hem te identificeren' }, correct: false },
    ],
    explanation: { fr: "Retirer un casque peut aggraver une blessure à la nuque — on ne le fait qu'en cas de réelle difficulté respiratoire.", nl: 'Een helm afzetten kan een nekletsel verergeren — dat doet u enkel bij echte ademhalingsmoeilijkheden.' },
    factIds: ['sc29-blesses-gestes'],
    difficulty: 'moyen',
  },
  {
    id: 'sc29-q5',
    themeSlug: 'securite-comportement',
    region: 'BE',
    prompt: { fr: 'Un conducteur quitte les lieux d’un accident sans être sûr d’en être responsable, pour éviter des ennuis. Est-ce un délit de fuite ?', nl: 'Een bestuurder verlaat de plaats van een ongeval zonder zeker te zijn dat hij aansprakelijk is, om problemen te vermijden. Is dit vluchtmisdrijf?' },
    options: [
      { id: 'a', text: { fr: 'Oui, le doute n’excuse pas la fuite volontaire', nl: 'Ja, twijfel verontschuldigt de vrijwillige vlucht niet' }, correct: true },
      { id: 'b', text: { fr: 'Non, seule une certitude de responsabilité compte', nl: 'Nee, enkel zekerheid over aansprakelijkheid telt' }, correct: false },
    ],
    explanation: { fr: "Le délit de fuite se caractérise dès qu'on quitte volontairement les lieux en sachant ou en doutant avoir causé l'accident, pour échapper aux constatations.", nl: 'Vluchtmisdrijf is er al zodra u vrijwillig de plaats verlaat terwijl u weet of vermoedt het ongeval te hebben veroorzaakt, om de vaststellingen te ontlopen.' },
    factIds: ['sc29-delit-fuite'],
    difficulty: 'difficile',
  },
]
