import type { Question } from '@/domain/quiz'

export const VEHICULE_TECHNIQUE_QUESTIONS: Question[] = [
  {
    id: 'vt9-q1',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Avec un permis B, quelle est la MMA maximale que vous pouvez conduire ?', nl: 'Met een rijbewijs B, wat is de maximale MTM die u mag besturen?' },
    options: [
      { id: 'a', text: { fr: '3 500 kg', nl: '3 500 kg' }, correct: true },
      { id: 'b', text: { fr: '5 000 kg', nl: '5 000 kg' }, correct: false },
    ],
    explanation: { fr: "Un permis B permet de conduire des véhicules dont la MMA n'excède pas 3 500 kg.", nl: 'Een rijbewijs B laat toe voertuigen te besturen met een MTM van maximaal 3 500 kg.' },
    factIds: ['vt9-mma-def'],
    difficulty: 'facile',
  },
  {
    id: 'vt9-q2',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Où doit se trouver le gilet de sécurité réfléchissant ?', nl: 'Waar moet het fluorescerende veiligheidsvest zich bevinden?' },
    options: [
      { id: 'a', text: { fr: 'Dans le coffre', nl: 'In de koffer' }, correct: false },
      { id: 'b', text: { fr: 'Dans l’habitacle, à portée de main', nl: 'In de passagiersruimte, binnen handbereik' }, correct: true },
    ],
    explanation: { fr: "Le gilet doit être dans l'habitacle, car le conducteur doit pouvoir l'enfiler avant de sortir du véhicule.", nl: 'Het vest moet in de passagiersruimte liggen, want de bestuurder moet het kunnen aandoen vóór hij uitstapt.' },
    factIds: ['vt9-documents-obligatoires'],
    difficulty: 'moyen',
  },
  {
    id: 'vt10-q1',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Un chargement peut-il dépasser l’avant de la carrosserie ?', nl: 'Mag een lading vooraan de carrosserie overschrijden?' },
    options: [
      { id: 'a', text: { fr: 'Oui, jusqu’à 1 mètre', nl: 'Ja, tot 1 meter' }, correct: false },
      { id: 'b', text: { fr: 'Non, jamais', nl: 'Nee, nooit' }, correct: true },
    ],
    explanation: { fr: "Un chargement ne peut en aucun cas dépasser à l'avant du véhicule — l'exception d'1 m (ou 3 m) ne concerne que l'arrière.", nl: 'Een lading mag in geen geval vooraan het voertuig uitsteken — de uitzondering van 1 m (of 3 m) geldt enkel achteraan.' },
    factIds: ['vt10-longueur'],
    difficulty: 'moyen',
  },
  {
    id: 'vt10-q2',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Avec un permis B provisoire, pouvez-vous tracter une remorque de 500 kg ?', nl: 'Mag u met een voorlopig rijbewijs B een aanhangwagen van 500 kg trekken?' },
    options: [
      { id: 'a', text: { fr: 'Oui, sous 750 kg c’est toujours permis', nl: 'Ja, onder 750 kg is dat altijd toegelaten' }, correct: false },
      { id: 'b', text: { fr: 'Non, aucune remorque avec un permis provisoire', nl: 'Nee, geen enkele aanhangwagen met een voorlopig rijbewijs' }, correct: true },
    ],
    explanation: { fr: "Un permis B provisoire ne permet de tracter aucune remorque, quelle que soit sa MMA.", nl: 'Een voorlopig rijbewijs B laat geen enkele aanhangwagen toe, ongeacht de MTM.' },
    factIds: ['vt10-remorque'],
    difficulty: 'moyen',
  },
  {
    id: 'vt31-q1',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Le minimum légal de 1,6 mm de rainure garantit-il une sécurité optimale ?', nl: 'Garandeert het wettelijke minimum van 1,6 mm profieldiepte optimale veiligheid?' },
    options: [
      { id: 'a', text: { fr: 'Oui, c’est suffisant', nl: 'Ja, dat volstaat' }, correct: false },
      { id: 'b', text: { fr: 'Non, le risque d’aquaplaning augmente déjà sous 2 mm', nl: 'Nee, het risico op aquaplaning stijgt al onder 2 mm' }, correct: true },
    ],
    explanation: { fr: "1,6 mm est le minimum légal, mais la sécurité réelle est déjà compromise en dessous de 2 mm.", nl: '1,6 mm is het wettelijke minimum, maar de echte veiligheid is al in het gedrang onder 2 mm.' },
    factIds: ['vt31-pneus-legal'],
    difficulty: 'moyen',
  },
  {
    id: 'vt31-q2',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'L’arrière de votre voiture décroche dans un virage. Que faites-vous ?', nl: 'De achterkant van uw auto glijdt weg in een bocht. Wat doet u?' },
    options: [
      { id: 'a', text: { fr: 'Je freine fort', nl: 'Ik rem hard' }, correct: false },
      { id: 'b', text: { fr: 'Je contre-braque et je lâche l’accélérateur', nl: 'Ik stuur tegen en laat het gas los' }, correct: true },
    ],
    explanation: { fr: "En cas de survirage (dérapage arrière), il faut contre-braquer dans le sens du dérapage et lâcher l'accélérateur — jamais freiner fort.", nl: 'Bij overstuur (achterste slip) moet u tegensturen in de richting van de slip en het gas loslaten — nooit hard remmen.' },
    factIds: ['vt31-freins-derapage'],
    difficulty: 'moyen',
  },
  {
    id: 'vt31-q3',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Vous êtes arrêté à un feu rouge. Pouvez-vous consulter votre GPS sur votre smartphone tenu en main ?', nl: 'U staat stil aan een rood licht. Mag u uw GPS raadplegen op uw handgehouden smartphone?' },
    options: [
      { id: 'a', text: { fr: 'Oui, je suis à l’arrêt', nl: 'Ja, ik sta stil' }, correct: false },
      { id: 'b', text: { fr: 'Non, un feu rouge ne compte pas comme « être à l’arrêt »', nl: 'Nee, een rood licht telt niet als "stilstaan"' }, correct: true },
    ],
    explanation: { fr: "S'arrêter à un feu rouge ou dans un embouteillage n'est pas considéré comme « être à l'arrêt » pour cette règle — le téléphone doit rester dans son support.", nl: 'Stoppen aan een rood licht of in een file wordt niet beschouwd als "stilstaan" voor deze regel — de telefoon moet in zijn houder blijven.' },
    factIds: ['vt31-appareils-electroniques'],
    difficulty: 'difficile',
  },
  {
    id: 'vt30-q1',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Une galerie de toit vide augmente-t-elle la consommation de carburant ?', nl: 'Verhoogt een lege dakdrager het brandstofverbruik?' },
    options: [
      { id: 'a', text: { fr: 'Oui, à cause de la résistance à l’air', nl: 'Ja, door de luchtweerstand' }, correct: true },
      { id: 'b', text: { fr: 'Non, elle est trop légère pour avoir un effet', nl: 'Nee, ze is te licht om invloed te hebben' }, correct: false },
    ],
    explanation: { fr: "Une galerie de toit, même vide, augmente la résistance à l'air et donc la consommation — mieux vaut la retirer.", nl: 'Een dakdrager, zelfs leeg, verhoogt de luchtweerstand en dus het verbruik — beter verwijderen.' },
    factIds: ['vt30-poids-vitres'],
    difficulty: 'facile',
  },
  {
    id: 'vt30-q2',
    themeSlug: 'vehicule-technique',
    region: 'BE',
    prompt: { fr: 'Les conditions d’accès aux zones de basses émissions sont-elles identiques dans toutes les villes belges ?', nl: 'Zijn de toegangsvoorwaarden voor lage-emissiezones identiek in alle Belgische steden?' },
    options: [
      { id: 'a', text: { fr: 'Oui, une règle nationale unique', nl: 'Ja, één nationale regel' }, correct: false },
      { id: 'b', text: { fr: 'Non, chaque ville fixe ses propres règles', nl: 'Nee, elke stad bepaalt haar eigen regels' }, correct: true },
    ],
    explanation: { fr: "Chaque ville belge avec une zone de basses émissions (Anvers, Bruxelles, Gand...) fixe ses propres conditions d'accès.", nl: 'Elke Belgische stad met een lage-emissiezone (Antwerpen, Brussel, Gent...) bepaalt haar eigen toegangsvoorwaarden.' },
    factIds: ['vt30-couper-moteur-emissions'],
    difficulty: 'moyen',
  },
]
