import type { ReactNode } from 'react'
import { Link } from '@/i18n/navigation'

export type FaqItem = { question: string; keywords?: string; answer: ReactNode }
export type FaqCategory = { id: string; title: string; items: FaqItem[] }

const official = {
  brussels: 'https://be.brussels/fr/transport-mobilite/permis-de-conduire-et-immatriculation/obtenir-son-permis/formation-la-conduite-et-examens-pour-le-permis-de-conduire-b',
  walloniaTheory: 'https://wallonie.be/fr/demarches/passer-le-permis-de-conduire-theorique-categorie-b',
  walloniaPractice: 'https://www.wallonie.be/fr/demarches/passer-le-permis-de-conduire-pratique-categorie-b',
  walloniaPermit: 'https://www.wallonie.be/fr/demarches/demander-votre-permis-de-conduire-aupres-de-votre-commune',
  flandersTheory: 'https://www.vlaanderen.be/mobiliteit-en-openbare-werken/auto-en-motor/rijbewijzen-en-rijopleiding/rijbewijs-b/theorie-examen-voor-rijbewijs-b',
  flandersPractice: 'https://www.vlaanderen.be/mobiliteit-en-openbare-werken/auto-en-motor/rijbewijzen-en-rijopleiding/rijbewijs-b/praktijkexamen-rijbewijs-b',
  flandersPermit: 'https://www.vlaanderen.be/mobiliteit-en-openbare-werken/auto-en-motor/rijbewijzen-en-rijopleiding/rijbewijs-b/oefenperiode-voorlopig-rijbewijs-b',
  unaVia: 'https://www.vlaanderen.be/vlaamse-regering/beslissingen-van-de-vlaamse-regering/una-via-regeling-rijbewijs-voor-voertuigen-praktijk-en-theorie-in-zelfde-gewest',
}

function Source({ href, children }: { href: string; children: ReactNode }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className="font-semibold text-forest underline decoration-1 underline-offset-4 hover:text-brick">{children}</a>
}

const steps: FaqCategory = {
  id: 'parcours', title: 'Obtenir le permis B', items: [
    { question: 'Quelles sont les étapes pour obtenir le permis B en Belgique ?', keywords: 'parcours démarche comment passer', answer: <><p>Le parcours dépend de la Région dans laquelle tu passes ton permis et de la filière d’apprentissage choisie.</p><ol className="my-3 list-decimal space-y-1 pl-5"><li>Apprendre le Code de la route et réussir l’examen théorique.</li><li>Choisir une filière pratique et commencer la période d’apprentissage lorsqu’elle est requise.</li><li>Réussir le test de perception des risques lorsque la procédure régionale le prévoit.</li><li>Réussir l’examen pratique, puis demander le permis définitif à ta commune.</li></ol><div className="my-4 rounded-xl border-l-4 border-forest bg-[#e5f1ec] p-4"><strong>À retenir selon la région</strong><ul className="mt-2 list-disc space-y-1 pl-5"><li><strong>Wallonie :</strong> depuis le 1<sup>er</sup> janvier 2026, le parcours menant au pratique wallon doit être réalisé en Wallonie.</li><li><strong>Bruxelles :</strong> le parcours pratique suit ses propres filières et exige notamment la théorie dans la Région.</li><li><strong>Flandre :</strong> la période de pratique est d’au moins cinq mois. Une règle dite Una Via est annoncée à partir du 1<sup>er</sup> janvier 2027 ; elle n’est pas encore en vigueur à la date de vérification.</li></ul></div><p>Avant de réserver, confirme les détails auprès de l’administration : <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.walloniaPractice}>Wallonie</Source> · <Source href={official.flandersPractice}>Flandre</Source> · <Source href={official.unaVia}>évolution prévue en Flandre</Source>.</p><p className="mt-2 text-xs text-ink/55">Règles consultées le 24 septembre 2026.</p></> },
  ]
}

const theory: FaqCategory = {
  id: 'theorie', title: 'Examen théorique', items: [
    { question: 'Comment se déroule l’examen théorique du permis B ?', answer: <>Il se passe sur ordinateur dans un centre d’examen. Les trois régions décrivent une épreuve de 50 questions à choix multiples, mais les modalités d’inscription, les langues et certaines règles de parcours peuvent varier. Lis la procédure officielle de ta région : <Source href={official.walloniaTheory}>Wallonie</Source>, <Source href={official.brussels}>Bruxelles</Source>, <Source href={official.flandersTheory}>Flandre</Source>.</> },
    { question: 'Combien de questions y a-t-il à l’examen théorique ?', answer: <>Les informations officielles consultées pour Bruxelles, la Wallonie et la Flandre indiquent <strong>50 questions</strong> pour la catégorie B. Vérifie les modalités et éventuelles sessions adaptées auprès du centre de ta région : <Source href={official.walloniaTheory}>Wallonie</Source> · <Source href={official.flandersTheory}>Flandre</Source> · <Source href={official.brussels}>Bruxelles</Source>.</> },
    { question: 'Combien faut-il obtenir pour réussir l’examen théorique ?', answer: <>En Wallonie et en Flandre, le seuil publié est de <strong>41 points sur 50</strong>. Bruxelles publie également ce seuil dans ses informations officielles sur l’examen B. Les fautes graves ont une pénalité spécifique : atteindre 41 points ne suffit donc pas toujours si tu as commis trop de fautes graves. <Source href={official.walloniaTheory}>Règles wallonnes</Source> · <Source href={official.flandersTheory}>Règles flamandes</Source>.</> },
    { question: 'Qu’est-ce qu’une faute grave à l’examen théorique ?', answer: <>C’est une erreur portant sur une infraction grave définie par les règles de l’examen. En Wallonie et en Flandre, elle retire cinq points, contre un point pour une erreur ordinaire. La liste et les modalités sont à vérifier sur la page officielle de ta région : <Source href={official.walloniaTheory}>Wallonie</Source> ou <Source href={official.flandersTheory}>Flandre</Source>.</> },
    { question: 'Combien de fautes graves peut-on faire ?', answer: <>En Wallonie, une seule faute grave est compatible avec la réussite si tu obtiens aussi le score requis ; deux fautes graves entraînent l’échec. En Flandre, une faute de cinq points est déduite du résultat et le total doit rester au moins égal à 41. Pour Bruxelles, vérifie la règle en vigueur sur la page régionale avant ta session. <Source href={official.walloniaTheory}>Source Wallonie</Source> · <Source href={official.flandersTheory}>Source Flandre</Source>.</> },
    { question: 'À partir de quel âge peut-on passer l’examen théorique B ?', answer: <>Les pages officielles de la Wallonie et de la Flandre indiquent un âge minimum de <strong>17 ans</strong>. Pour Bruxelles ou une situation particulière, confirme les conditions d’inscription auprès de la région et du centre concernés. <Source href={official.walloniaTheory}>Wallonie</Source> · <Source href={official.flandersTheory}>Flandre</Source> · <Source href={official.brussels}>Bruxelles</Source>.</> },
    { question: 'Combien de temps l’examen théorique reste-t-il valable ?', answer: <>La réussite reste valable <strong>trois ans</strong> dans les procédures décrites par les régions consultées. Une échéance peut avoir des conséquences sur les tests à repasser et l’accès à la pratique : vérifie la date de ton attestation et la procédure locale. <Source href={official.walloniaTheory}>Wallonie</Source> · <Source href={official.flandersTheory}>Flandre</Source> · <Source href={official.brussels}>Bruxelles</Source>.</> },
    { question: 'Que se passe-t-il après deux échecs à l’examen théorique ?', answer: <>En Wallonie et en Flandre, deux échecs consécutifs imposent de suivre une formation théorique en auto-école avant une nouvelle présentation. La durée et les conditions doivent être confirmées auprès de ta région avant une nouvelle inscription. <Source href={official.walloniaTheory}>Wallonie</Source> · <Source href={official.flandersTheory}>Flandre</Source>.</> },
    { question: 'Peut-on passer la théorie dans une région et la pratique dans une autre ?', answer: <>Ne pars pas du principe que les épreuves peuvent être réparties librement entre régions. Depuis le 1<sup>er</sup> janvier 2026, la Wallonie exige que le parcours d’examen menant à la pratique en Wallonie (théorie et test de perception des risques, plus le test de capacité technique dans le cas M18) ait été réalisé en Wallonie. Bruxelles et la Flandre ont leurs propres conditions. Consulte les règles avant de changer de région : <Source href={official.walloniaPractice}>Wallonie</Source> · <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.flandersPractice}>Flandre</Source>.</> },
  ]
}

const learning: FaqCategory = {
  id: 'apprentissage', title: 'Apprendre avec PermisHub', items: [
    { question: 'Comment apprendre la théorie avec PermisHub ?', answer: <>Tu peux parcourir les modules et leçons interactives disponibles dans <Link className="font-semibold text-forest underline underline-offset-4" href="/apprendre">l’espace d’apprentissage</Link>. Les leçons abordent progressivement des thèmes du permis B. Vérifie les modules actuellement publiés sur cette page.</> },
    { question: 'Que contiennent les leçons interactives PermisHub ?', answer: <>Les leçons publiées comprennent des explications, des questions d’entraînement et, selon le contenu, des visuels pédagogiques. Le contenu varie d’une leçon à l’autre ; ouvre la leçon concernée dans <Link className="font-semibold text-forest underline underline-offset-4" href="/apprendre">Apprendre</Link> pour voir ce qui est disponible.</> },
    { question: 'À quoi sert le résumé PermisHub ?', answer: <>Le <Link className="font-semibold text-forest underline underline-offset-4" href="/resume">résumé PermisHub</Link> est un support PDF de révision vendu séparément. Sa page présente son contenu et ses conditions avant achat ; il ne remplace pas le Code officiel ni la pratique des questions.</> },
    { question: 'Comment fonctionnent les examens blancs PermisHub ?', answer: <>La page <Link className="font-semibold text-forest underline underline-offset-4" href="/examen-blanc">Examens blancs</Link> permet de consulter les séries actuellement proposées et leur accès. Les examens blancs sont un outil d’entraînement créé par PermisHub : ils ne sont pas l’épreuve officielle et ne garantissent pas la réussite.</> },
    { question: 'Les examens blancs PermisHub reproduisent-ils l’examen officiel ?', answer: <>Ils servent à t’entraîner aux connaissances théoriques. Ils ne constituent pas une copie officielle, et PermisHub ne garantit pas que les mêmes questions apparaîtront le jour de l’examen. Consulte les règles et exemples fournis par ta région en complément.</> },
    { question: 'Puis-je refaire les examens blancs plusieurs fois ?', answer: <>Les séries et leurs conditions d’accès sont présentées sur la page <Link className="font-semibold text-forest underline underline-offset-4" href="/examen-blanc">Examens blancs</Link>. Vérifie cette page avant l’achat pour connaître les modalités correspondant à l’offre disponible actuellement.</> },
    { question: 'Comment savoir quels thèmes je dois encore travailler ?', answer: <>Reprends les questions auxquelles tu hésites dans les leçons et révise le thème correspondant. Les pages d’apprentissage présentent les contenus disponibles ; je ne présente pas ici de tableau de progression ou de diagnostic automatique qui n’est pas confirmé comme disponible.</> },
  ]
}

const risks: FaqCategory = {
  id: 'risques', title: 'Perception des risques', items: [
    { question: 'Qu’est-ce que le test de perception des risques ?', answer: <>C’est une épreuve qui évalue ta capacité à repérer des situations dangereuses dans la circulation. Le format exact dépend de la région ; il faut suivre les instructions du centre d’examen et les règles officielles locales.</> },
    { question: 'Comment se déroule le test de perception des risques ?', answer: <>À Bruxelles, l’épreuve utilisée à l’examen pratique comprend cinq séquences vidéo dans la documentation régionale consultée. Le format a récemment évolué dans certains centres. Ne transpose pas automatiquement cette présentation à la Wallonie ou à la Flandre : suis les instructions de ton centre. <Source href={official.brussels}>Informations de Bruxelles</Source>.</> },
    { question: 'Quand faut-il passer la perception des risques ?', answer: <>Le moment et les conditions dépendent de la région et de la filière. En Wallonie, le test est requis pour accéder à l’examen pratique ; sa réussite doit être effectuée en Wallonie depuis le 1<sup>er</sup> janvier 2026 pour un examen pratique wallon. Consulte la page de ta région : <Source href={official.walloniaPractice}>Wallonie</Source> · <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.flandersPractice}>Flandre</Source>.</> },
    { question: 'Comment réussir la perception des risques ?', answer: <>Observe la scène dans son ensemble, repère les usagers vulnérables et les changements de situation, puis réponds selon les consignes du test. Entraîne-toi à identifier le danger assez tôt plutôt qu’à cliquer au hasard. Le barème et le format officiels sont ceux de ta région.</> },
    { question: 'Comment s’entraîner à la perception des risques avec PermisHub ?', answer: <>PermisHub propose un entraînement dédié sur la page <Link className="font-semibold text-forest underline underline-offset-4" href="/perception-risques">Perception des risques</Link>. Elle présente le contenu disponible ; la préparation ne remplace pas l’épreuve officielle ni les consignes du centre.</> },
    { question: 'Combien de temps le test de perception des risques reste-t-il valable ?', answer: <>La validité dépend de la procédure régionale. Les pages officielles consultées indiquent notamment une validité d’un an à Bruxelles et en Flandre ; en Wallonie, vérifie que la réussite satisfait les conditions actuelles d’accès au pratique et de parcours régional. <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.flandersPractice}>Flandre</Source> · <Source href={official.walloniaPractice}>Wallonie</Source>.</> },
  ]
}

const provisional: FaqCategory = {
  id: 'provisoire', title: 'Permis provisoire et apprentissage', items: [
    { question: 'Comment obtenir un permis provisoire B ?', answer: <>Après avoir réussi la théorie, tu choisis une filière et demandes le permis provisoire correspondant à ta situation, généralement auprès de ta commune. Les modèles, conditions d’âge, présence d’un guide et durée varient. Consulte la page officielle de ta région : <Source href={official.walloniaPermit}>Wallonie</Source> · <Source href={official.flandersPermit}>Flandre</Source> · <Source href={official.brussels}>Bruxelles</Source>.</> },
    { question: 'Quelle est la différence entre un permis provisoire avec guide et sans guide ?', answer: <>Avec un modèle accompagné, tu conduis sous les conditions et avec les guides autorisés par ton permis. Le modèle sans guide impose d’autres prérequis, parfois une formation en auto-école. Les codes, conditions et durées ne sont pas identiques partout ; compare les options officielles de ta région avant de choisir.</> },
    { question: 'Combien de temps faut-il s’entraîner avant l’examen pratique ?', answer: <>La période minimale dépend de la filière et de la région. Par exemple, la Flandre indique une période de pratique d’au moins cinq mois ; Bruxelles et la Wallonie prévoient plusieurs filières avec des durées distinctes. Vérifie ta filière précise sur la source régionale : <Source href={official.flandersPermit}>Flandre</Source> · <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.walloniaPractice}>Wallonie</Source>.</> },
    { question: 'Peut-on conduire seul avec un permis provisoire ?', answer: <>Cela dépend du modèle. En Wallonie, la filière libre se pratique avec un guide et ne permet pas de conduire seul ; certaines voies avec auto-école donnent accès à une période sans guide sous conditions. Les règles sont propres au modèle et à la région : <Source href={official.walloniaPractice}>consulte la procédure wallonne</Source> ou la source de ta région.</> },
    { question: 'Que faire si mon permis provisoire expire ?', answer: <>Ne conduis plus sur la base d’un permis expiré. Les possibilités de renouvellement ou de changement de filière dépendent du modèle, de la date d’expiration et de la région. Contacte ta commune ou consulte la procédure officielle avant de reprendre la conduite : <Source href={official.walloniaPermit}>Wallonie</Source> · <Source href={official.flandersPermit}>Flandre</Source>.</> },
  ]
}

const practical: FaqCategory = {
  id: 'pratique', title: 'Examen pratique', items: [
    { question: 'Comment se déroule l’examen pratique du permis B ?', answer: <>L’examen vérifie que tu peux conduire de façon sûre et autonome, selon les exigences de ta région. La procédure peut comprendre une vérification des documents, des manœuvres et un trajet sur route ; l’ordre et les conditions varient. Lis les consignes officielles avant ton rendez-vous : <Source href={official.walloniaPractice}>Wallonie</Source> · <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.flandersPractice}>Flandre</Source>.</> },
    { question: 'À partir de quel âge peut-on passer l’examen pratique B ?', answer: <>L’âge minimum annoncé est de <strong>18 ans</strong> dans les procédures officielles consultées pour les trois régions. D’autres conditions de stage, de cours ou d’épreuves doivent aussi être remplies avant de réserver. <Source href={official.walloniaPractice}>Wallonie</Source> · <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.flandersPractice}>Flandre</Source>.</> },
    { question: 'Que faut-il apporter le jour de l’examen pratique ?', answer: <>Les documents dépendent de ta filière, du véhicule et de la région. Prévois au minimum ta pièce d’identité et les justificatifs exigés par le centre ; en Wallonie, la liste distingue notamment les candidats qui se présentent avec leur propre véhicule. Vérifie ta convocation et la liste officielle avant le jour J. <Source href={official.walloniaPractice}>Liste wallonne</Source>.</> },
    { question: 'Quelles manœuvres peuvent être demandées ?', answer: <>Les manœuvres et la façon dont elles sont évaluées dépendent des règles de la région. Consulte la page consacrée à l’examen pratique de ton lieu de passage et entraîne-toi avec ton guide ou ton école. <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.walloniaPractice}>Wallonie</Source> · <Source href={official.flandersPractice}>Flandre</Source>.</> },
    { question: 'Que se passe-t-il si j’échoue à l’examen pratique ?', answer: <>Tu devras réserver une nouvelle présentation selon les conditions en vigueur. Après deux échecs consécutifs, Bruxelles et la Flandre exigent une formation pratique de six heures ; vérifie les modalités et les exigences wallonnes correspondant à ta filière auprès du SPW et de ton centre. <Source href={official.brussels}>Bruxelles</Source> · <Source href={official.flandersPractice}>Flandre</Source> · <Source href={official.walloniaPractice}>Wallonie</Source>.</> },
    { question: 'Comment choisir son centre d’examen ?', answer: <>Choisis un centre qui accepte la catégorie B et la procédure correspondant à ta région. Les rendez-vous, langues, véhicules acceptés et documents peuvent varier d’un centre à l’autre. Tu peux consulter les centres et leurs informations PermisHub depuis <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">la sélection des centres</Link>.</> },
    { question: 'Peut-on changer de centre d’examen ?', answer: <>Les conditions pratiques de changement de centre sont à confirmer auprès du centre où tu veux présenter l’épreuve. Avant de déplacer un rendez-vous, vérifie aussi que le changement ne modifie pas les exigences régionales liées à ta théorie, à ton test de perception des risques ou à ta filière.</> },
    { question: 'Comment se préparer aux routes autour de son centre ?', answer: <>Repère les quartiers et types de situations sans chercher à mémoriser un seul trajet. Entraîne-toi à appliquer les règles, lire la signalisation et t’adapter aux conditions réelles. Les <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">pages de centres PermisHub</Link> donnent accès aux informations locales publiées et aux circuits payants disponibles.</> },
  ]
}

const centers: FaqCategory = {
  id: 'centres', title: 'Centres d’examen', items: [
    { question: 'Quels centres d’examen sont disponibles sur PermisHub ?', answer: <>Le hub présente actuellement Anderlecht, Schaerbeek, Cuesmes, Mariembourg, Lobbes, Braine-le-Comte, Couillet et Louvain-la-Neuve. Ouvre <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">la page Centres d’examen</Link> pour accéder aux fiches réellement publiées et voir les informations propres à chaque centre.</> },
    { question: 'Comment trouver les informations sur mon centre d’examen ?', answer: <>Sélectionne ton centre dans le <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">hub des centres</Link>. Lorsqu’une fiche existe, elle indique les informations locales et renvoie vers les circuits PermisHub associés lorsqu’ils sont disponibles.</> },
    { question: 'Comment connaître l’adresse et les horaires de mon centre ?', answer: <>Les coordonnées et horaires ne sont pas identiques pour tous les centres ni pour les examens théoriques et pratiques. Consulte la page officielle de l’opérateur du centre pour préparer ton rendez-vous ; les fiches PermisHub peuvent aussi reprendre certaines informations pratiques vérifiées.</> },
    { question: 'Comment préparer mon examen dans mon centre ?', answer: <>Commence par vérifier les instructions, l’adresse et les documents requis auprès du centre officiel. Ensuite, utilise les ressources PermisHub réellement disponibles pour ce lieu. La fiche locale et les circuits s’ouvrent depuis <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">le hub des centres</Link>.</> },
  ]
}

const circuits: FaqCategory = {
  id: 'circuits', title: 'Circuits PermisHub', items: [
    { question: 'Que sont les circuits d’examen PermisHub ?', answer: <>Ce sont des parcours d’entraînement associés à certains centres. Ils permettent de découvrir le secteur avec des itinéraires Google Maps lorsqu’un circuit est disponible. Ils restent des supports de préparation et ne garantissent pas le trajet qui sera choisi le jour de l’examen. Choisis ton centre dans <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">le hub</Link>.</> },
    { question: 'Les circuits PermisHub sont-ils payants ?', answer: <>Oui. Tous les circuits PermisHub sont payants. Le prix affiché sur la page du centre est celui à vérifier avant l’achat ; il peut dépendre de l’offre présentée au moment de ta visite.</> },
    { question: 'Comment acheter les circuits de mon centre ?', answer: <>Ouvre la fiche du centre dans <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">Centres d’examen</Link>, puis suis le bouton de déblocage affiché sur cette page. Le parcours d’achat existant te présente les conditions avant de confirmer le paiement.</> },
    { question: 'Combien de circuits sont disponibles pour mon centre ?', answer: <>Le nombre varie selon le centre et l’offre publiée. Il est affiché sur la fiche correspondante dans <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">le hub PermisHub</Link> ; consulte cette fiche pour obtenir le compte à jour.</> },
    { question: 'Comment ouvrir un circuit avec Google Maps ?', answer: <>Après déblocage, ouvre le circuit depuis l’interface PermisHub et utilise son lien vers Google Maps. Les liens détaillés ne sont communiqués qu’à l’utilisateur autorisé, après vérification de son accès.</> },
    { question: 'Puis-je utiliser les circuits sur mon téléphone ?', answer: <>Oui, les pages et liens Google Maps peuvent être consultés sur téléphone. Prépare ton itinéraire à l’arrêt ; ne manipule jamais ton téléphone en conduisant et respecte le Code de la route.</> },
    { question: 'Puis-je refaire les circuits plusieurs fois ?', answer: <>Les circuits déverrouillés restent consultables depuis l’espace d’accès correspondant. Les modalités exactes affichées au moment de l’achat font foi ; vérifie-les sur la fiche du centre avant de payer.</> },
    { question: 'Combien de temps ai-je accès aux circuits après l’achat ?', answer: <>La durée applicable doit être celle précisée dans l’offre au moment de l’achat. Je ne l’indique pas ici tant qu’une durée unique et actuelle n’est pas clairement vérifiée dans le parcours affiché.</> },
    { question: 'Que faire si mon centre n’est pas encore disponible ?', answer: <>Vérifie le <Link className="font-semibold text-forest underline underline-offset-4" href="/centres-examen">hub des centres</Link> : seuls les centres et circuits affichés comme disponibles peuvent être achetés. Je n’annonce pas de date de sortie pour un centre qui n’est pas encore publié.</> },
    { question: 'Comment retrouver mes circuits après mon achat ?', answer: <>Utilise <Link className="font-semibold text-forest underline underline-offset-4" href="/restaurer-acces">Restaurer mon accès</Link> avec l’adresse e-mail utilisée lors de l’achat pour recevoir un lien de connexion. Les données des circuits ne sont renvoyées qu’après validation de l’accès.</> },
  ]
}

const payment: FaqCategory = {
  id: 'paiement', title: 'Paiement et achats', items: [
    { question: 'Quels moyens de paiement PermisHub accepte-t-il ?', answer: <>Le paiement proposé sur le parcours Stripe accepte les cartes bancaires et Bancontact. Les moyens disponibles sont affichés dans la page de paiement au moment de l’achat.</> },
    { question: 'Le paiement est-il sécurisé ?', answer: <>Le paiement est traité par Stripe, qui ouvre son parcours de paiement lorsque tu lances un achat sur PermisHub. Vérifie le récapitulatif de commande avant de confirmer et consulte la <Link className="font-semibold text-forest underline underline-offset-4" href="/confidentialite">politique de confidentialité</Link> pour savoir comment le site traite les données personnelles.</> },
    { question: 'Quand mon accès est-il activé après paiement ?', answer: <>Après validation du paiement, le parcours de confirmation vérifie la transaction avant d’ouvrir l’accès à l’achat concerné. Si l’accès n’apparaît pas, restaure-le avec la même adresse e-mail via <Link className="font-semibold text-forest underline underline-offset-4" href="/restaurer-acces">la page de récupération</Link>.</> },
    { question: 'J’ai payé mais je n’ai pas accès à mon achat : que faire ?', answer: <>Vérifie d’abord que tu utilises l’adresse e-mail saisie lors de l’achat, puis demande un lien sur <Link className="font-semibold text-forest underline underline-offset-4" href="/restaurer-acces">Restaurer mon accès</Link>. Si l’accès reste indisponible, conserve le reçu de paiement et les détails de la commande.</> },
    { question: 'Comment fonctionne la garantie de remboursement ?', answer: <>Les conditions dépendent de l’offre concernée. Elles doivent être consultées sur la page de vente et au moment du paiement. Je ne présente pas une garantie générale sans conditions vérifiées applicables à tous les produits PermisHub.</> },
    { question: 'Puis-je payer depuis mon téléphone ?', answer: <>Oui, le paiement Stripe et les moyens affichés, dont Bancontact et les cartes, sont accessibles depuis le navigateur d’un téléphone. Vérifie les détails de la commande avant de confirmer.</> },
  ]
}

const account: FaqCategory = {
  id: 'acces', title: 'Compte et accès', items: [
    { question: 'Ai-je besoin d’un compte PermisHub ?', answer: <>Pour retrouver un achat, tu peux utiliser le lien de connexion envoyé par e-mail sur <Link className="font-semibold text-forest underline underline-offset-4" href="/restaurer-acces">Restaurer mon accès</Link>. Saisis l’adresse utilisée au moment du paiement. Le site ne te demande pas de créer un mot de passe pour cette récupération.</> },
    { question: 'Comment retrouver mes achats sur un autre appareil ?', answer: <>Sur ton nouvel appareil, ouvre <Link className="font-semibold text-forest underline underline-offset-4" href="/restaurer-acces">Restaurer mon accès</Link> et demande un lien avec l’adresse e-mail liée à l’achat. Ouvre ensuite le lien reçu sur l’appareil où tu veux accéder à tes contenus.</> },
    { question: 'Puis-je utiliser PermisHub sur plusieurs appareils ?', answer: <>Les pages publiques fonctionnent dans un navigateur. Pour les achats, utilise le lien de récupération d’accès avec l’adresse associée à la commande. Les limites éventuelles de connexion ou de partage dépendent des conditions de l’offre affichées au moment de l’achat.</> },
    { question: 'Je n’arrive pas à accéder à mon achat : que faire ?', answer: <>Demande un nouveau lien sur <Link className="font-semibold text-forest underline underline-offset-4" href="/restaurer-acces">Restaurer mon accès</Link>, en vérifiant l’adresse utilisée lors du paiement et le dossier courrier indésirable. Garde le reçu si tu dois ensuite faire vérifier la commande.</> },
  ]
}

export const FAQ_CATEGORIES: FaqCategory[] = [steps, theory, learning, risks, provisional, practical, centers, circuits, payment, account]
