/** Presentation copy only; commercial data stays in its existing sources. */
const fr = {
  eyebrow: 'Ton permis de conduire en Belgique', title: 'Prépare ton permis.', accent: 'Prends confiance.',
  lead: 'Fais le point sur ta théorie, révise l’essentiel et entraîne-toi sur les circuits de ton centre d’examen.',
  primary: 'Tester mon niveau', secondary: 'Trouver mon centre', ctaNote: 'Test gratuit · correction de tes réponses',
  preview: 'Un aperçu du test', question: 'Question', correction: 'La correction pour comprendre',
  proof: 'Leurs mots. Leurs résultats.', proofLink: 'Voir les témoignages',
  journeyEyebrow: 'Une préparation qui a du sens', journeyTitle: 'Savoir où tu en es. Et quoi travailler.',
  steps: [
    { title: 'Fais le point', body: 'Le test de niveau t’aide à repérer ce que tu maîtrises et les points à revoir.', link: 'Tester mon niveau', href: '/test-de-niveau' },
    { title: 'Va à l’essentiel', body: 'Retrouve le Résumé sans blabla et le guide de perception des risques, selon tes besoins.', link: 'Découvrir les supports', href: '/#packs' },
    { title: 'Prends tes repères', body: 'Entraîne-toi sur les itinéraires disponibles autour de ton centre d’examen.', link: 'Trouver mon centre', href: '/#circuits' },
  ],
  circuitsEyebrow: 'Du repère sur la carte à la pratique', circuitsTitle: 'Ton centre. Tes repères.',
  circuitsLead: 'Découvre les circuits d’entraînement de ton centre et parcours les zones avant ton examen pratique.',
  available: 'centres disponibles', routes: 'circuits d’entraînement', region: 'Centre d’examen', routeArt: 'Illustration de navigation',
  realRoutes: 'Itinéraires disponibles sur Google Maps', centerLink: 'Consulter le centre', previous: 'Précédent', next: 'Suivant',
  swipe: 'Fais glisser pour découvrir les centres', unavailable: 'Prochainement',
  otherCityBody: 'Ton centre n’est pas encore disponible ? Laisse ton email pour être informé.',
  email: 'Ton adresse email', emailError: 'L’envoi a échoué. Réessaie dans un instant.',
  reviewsEyebrow: 'Les retours des candidats', reviewsTitle: 'Le permis, raconté par ceux qui l’ont passé.',
  reviewsLead: 'Des témoignages sur la théorie, le résumé et les circuits. Avec les photos partagées par les candidats.',
  photoLink: 'Agrandir la photo', reviewsSwipe: 'Fais glisser pour lire les autres témoignages',
  offersEyebrow: 'À chaque étape, le bon support', offersTitle: 'Choisis ta préparation.',
  offersLead: 'Théorie ou pratique : retrouve les supports disponibles, selon ce que tu veux travailler.',
  faqTitle: 'Avant de commencer', faqEyebrow: 'Tes questions, simplement',
  faqs: [
    { q: 'Par quoi commencer ?', a: 'Le test de niveau gratuit te permet de faire le point sur tes connaissances théoriques. Tu passes d’abord par quelques questions sur ta préparation et la saisie de ton email, puis tu accèdes au test et à sa correction.' },
    { q: 'Comment utiliser les circuits ?', a: 'Choisis un centre disponible. Le déblocage donne accès aux circuits de ce centre, à ouvrir sur Google Maps pour t’entraîner. Tu peux aussi consulter la page du centre avant de choisir.' },
    { q: 'Est-ce le parcours garanti de mon examen ?', a: 'Les circuits servent à préparer les zones autour du centre. Le parcours choisi le jour de ton examen peut être différent.' },
    { q: 'Comment accéder aux supports après l’achat ?', a: 'Après validation du paiement, la page de confirmation donne accès au PDF acheté ou aux circuits débloqués. Le résumé et la perception des risques sont des supports distincts.' },
  ],
  finalEyebrow: 'Le premier pas, maintenant', finalTitle: 'Et si tu commençais par faire le point ?',
  finalLead: 'Teste tes connaissances et repère ce qu’il te reste à travailler.',
}
const nl: typeof fr = {
  eyebrow: 'Je rijbewijs voorbereiden in België', title: 'Bereid je rijbewijs voor.', accent: 'Met vertrouwen.',
  lead: 'Test je theoriekennis, herhaal de essentie en oefen op de routes rond je examencentrum.',
  primary: 'Test mijn niveau', secondary: 'Vind mijn centrum', ctaNote: 'Gratis test · correctie van je antwoorden',
  preview: 'Een voorproefje van de test', question: 'Vraag', correction: 'De uitleg bij het antwoord',
  proof: 'Hun woorden. Hun resultaten.', proofLink: 'Lees de ervaringen',
  journeyEyebrow: 'Gericht voorbereiden', journeyTitle: 'Weet waar je staat. En wat je kunt oefenen.',
  steps: [
    { title: 'Test je kennis', body: 'Ontdek met de niveautest wat je al beheerst en wat je nog moet herhalen.', link: 'Test mijn niveau', href: '/test-de-niveau' },
    { title: 'Focus op de essentie', body: 'Ontdek de Samenvatting zonder blabla en de gids voor gevaarherkenning.', link: 'Ontdek het materiaal', href: '/#packs' },
    { title: 'Leer de omgeving kennen', body: 'Oefen op de beschikbare routes rond je examencentrum.', link: 'Vind mijn centrum', href: '/#circuits' },
  ],
  circuitsEyebrow: 'Van de kaart naar de praktijk', circuitsTitle: 'Jouw centrum. Jouw voorbereiding.',
  circuitsLead: 'Ontdek de oefenroutes van je centrum en verken de omgeving vóór je praktijkexamen.',
  available: 'beschikbare centra', routes: 'oefenroutes', region: 'Examencentrum', routeArt: 'Navigatie-illustratie',
  realRoutes: 'Routes beschikbaar op Google Maps', centerLink: 'Bekijk het centrum', previous: 'Vorige', next: 'Volgende',
  swipe: 'Veeg om de centra te ontdekken', unavailable: 'Binnenkort',
  otherCityBody: 'Is je centrum nog niet beschikbaar? Laat je e-mailadres achter om op de hoogte te blijven.',
  email: 'Je e-mailadres', emailError: 'Verzenden mislukt. Probeer het straks opnieuw.',
  reviewsEyebrow: 'Ervaringen van kandidaten', reviewsTitle: 'Het rijbewijs, door de ogen van kandidaten.',
  reviewsLead: 'Ervaringen met de theorie, de samenvatting en de circuits. Met foto’s gedeeld door de kandidaten.',
  photoLink: 'Vergroot de foto', reviewsSwipe: 'Veeg om de andere ervaringen te lezen',
  offersEyebrow: 'Voor elke stap het juiste materiaal', offersTitle: 'Kies je voorbereiding.',
  offersLead: 'Theorie of praktijk: ontdek het beschikbare materiaal voor wat jij wilt oefenen.',
  faqTitle: 'Voor je begint', faqEyebrow: 'Antwoorden op je vragen',
  faqs: [
    { q: 'Waar begin ik?', a: 'Met de gratis niveautest ontdek je hoe goed je de theorie kent. Je beantwoordt eerst enkele vragen over je voorbereiding en vult je e-mailadres in. Daarna krijg je toegang tot de test en de correctie.' },
    { q: 'Hoe gebruik ik de circuits?', a: 'Kies een beschikbaar centrum. Na ontgrendeling krijg je toegang tot de circuits van dat centrum, die je in Google Maps kunt openen om te oefenen. Je kunt eerst ook de pagina van het centrum bekijken.' },
    { q: 'Is dit gegarandeerd mijn examenroute?', a: 'De circuits helpen je de omgeving van het centrum te verkennen. De route op de dag van je examen kan verschillen.' },
    { q: 'Hoe krijg ik toegang na aankoop?', a: 'Na bevestiging van de betaling geeft de bevestigingspagina toegang tot de gekochte pdf of de ontgrendelde circuits. De samenvatting en gevaarherkenning zijn afzonderlijke producten.' },
  ],
  finalEyebrow: 'Zet vandaag de eerste stap', finalTitle: 'Klaar om te ontdekken waar je staat?',
  finalLead: 'Test je kennis en ontdek wat je nog kunt oefenen.',
}
export function landingCopy(locale: string) { return locale === 'nl' ? nl : fr }
