'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { MODULE_TWO_FINAL_CHALLENGE } from '@/content/learning/module-2-final-challenge'
import { getLearningScene } from '@/content/learning/scenes'

const KEY = 'permishub.module-2-final-challenge.v1'

export function ModuleTwoFinalChallenge() {
  const [started, setStarted] = useState(false)
  const [index, setIndex] = useState(0)
  const [answers, setAnswers] = useState<Record<number, number>>({})
  const [done, setDone] = useState(false)
  const [review, setReview] = useState(false)
  const [best, setBest] = useState(0)
  useEffect(() => { const raw = localStorage.getItem(KEY); if (!raw) return; const saved = JSON.parse(raw); setBest(saved.best || 0); if (saved.answers && !saved.done) { setAnswers(saved.answers); setIndex(saved.index || 0); setStarted(true) } }, [])
  const score = useMemo(() => MODULE_TWO_FINAL_CHALLENGE.reduce((total, q, i) => total + (answers[i] === q.correct ? 1 : 0), 0), [answers])
  const select = (answer: number) => { setAnswers((current) => { const next = { ...current, [index]: answer }; localStorage.setItem(KEY, JSON.stringify({ best, answers: next, index, done: false })); return next }) }
  const finish = () => { const nextBest = Math.max(best, score); setBest(nextBest); localStorage.setItem(KEY, JSON.stringify({ best: nextBest, answers, done: true })); setDone(true) }
  const reset = () => { localStorage.removeItem(KEY); setStarted(true); setIndex(0); setAnswers({}); setDone(false); setReview(false) }
  const totals = MODULE_TWO_FINAL_CHALLENGE.reduce<Record<string, { total: number; score: number }>>((all, q, i) => { const item = all[q.topic] || { total: 0, score: 0 }; item.total++; if (answers[i] === q.correct) item.score++; all[q.topic] = item; return all }, {})
  if (!started) return <main className="learn-shell"><section className="learn-result"><span className="learn-kicker">DÉFI FINAL · PRIORITÉS & CARREFOURS</span><h1>Es-tu prêt à analyser un carrefour ?</h1><p>15 situations · 7 leçons évaluées · +50 XP</p><p>Identifie d’abord la règle qui organise chaque situation.</p><button className="learn-primary" onClick={() => setStarted(true)}>Commencer le défi →</button></section></main>
  if (done) { const errors = MODULE_TWO_FINAL_CHALLENGE.map((q, i) => ({ q, i })).filter(({ q, i }) => answers[i] !== q.correct); return <main className="learn-shell"><section className="learn-result"><span className="learn-kicker">DÉFI TERMINÉ</span><h1>{score} / 15</h1><h2>{score >= 12 ? 'Très solide' : score >= 9 ? 'Bon niveau' : 'Révision recommandée'}</h2><p className="learn-kicker">{Math.round(score / 15 * 100)} % · +50 XP</p><div className="learn-summary">{Object.entries(totals).map(([topic, value]) => <div key={topic}><b>{topic}</b><span>{value.score}/{value.total}</span></div>)}</div><div className="learn-result-actions"><button className="learn-secondary" onClick={() => setReview(!review)}>Revoir mes erreurs</button><button className="learn-primary" onClick={reset}>Recommencer le défi</button><Link className="learn-secondary" href="/apprendre">Retour au module</Link></div>{review && <div className="learn-summary">{errors.length ? errors.map(({ q, i }) => { const scene = getLearningScene(q.visualId); return <div key={q.id}><b>Question {i + 1}</b>{scene?.image ? <img className="learn-scene-image" src={scene.image} alt={scene.description} /> : null}<span><strong>{q.question}</strong><br/>Ta réponse : {q.options[answers[i]]}<br/>Bonne réponse : {q.options[q.correct]}<br/>{q.explanation}</span></div> }) : <div><span>Aucune erreur à revoir.</span></div>}</div>}{best > 0 && <p>Meilleur score : <strong>{best}/15</strong></p>}</section></main> }
  const question = MODULE_TWO_FINAL_CHALLENGE[index]; const scene = getLearningScene(question.visualId); const selected = answers[index]; const complete = Object.keys(answers).length === MODULE_TWO_FINAL_CHALLENGE.length
  return <main className="learn-shell"><section className="learn-player"><div className="learn-player-top"><span>QUESTION {String(index + 1).padStart(2, '0')} / 15</span><strong>{Math.round((index + 1) / 15 * 100)}%</strong></div><div className="learn-progress"><i style={{ width: `${(index + 1) / 15 * 100}%` }} /></div><article className="learn-card"><div className="learn-kicker">{question.topic}</div>{scene?.image ? <div className="learn-challenge-visual"><img className="learn-scene-image" src={scene.image} alt={scene.description} /></div> : null}<h2>{question.question}</h2><div className="learn-options">{question.options.map((option, optionIndex) => <button key={option} className={selected === optionIndex ? 'is-selected' : ''} onClick={() => select(optionIndex)}>{String.fromCharCode(65 + optionIndex)} <span>{option}</span></button>)}</div></article><p className="learn-challenge-note">{selected === undefined ? 'Choisis une réponse pour continuer.' : 'Réponse enregistrée. La correction sera affichée à la fin.'}</p><div className="learn-nav"><button disabled={index === 0} onClick={() => setIndex((value) => value - 1)}>← Précédent</button><span>{selected === undefined ? 'Réponse à enregistrer' : 'Réponse enregistrée'}</span>{index < 14 ? <button disabled={selected === undefined} onClick={() => setIndex((value) => value + 1)}>Suivant →</button> : <button className="learn-primary" disabled={!complete} onClick={finish}>Voir mon résultat →</button>}</div></section></main>
}
